### ISSUE TITLE
Add checksum to all disk IO in TiFlash

### ISSUE THREAD

**Issue by flowbehappy** [pingcap/tiflash#1955]
Currently, only PageStorage uses checksum to detect disk errors. Other components should also add checksum.

- DTFile
- schema.sql
-

**Comment by JaySon-Huang** [comment]
Done by these PRs

* https://github.com/pingcap/tiflash/pull/2640
* https://github.com/pingcap/tiflash/pull/2696
* https://github.com/pingcap/tiflash/pull/2697
* https://github.com/pingcap/tiflash/pull/2699
* https://github.com/pingcap/tiflash/pull/2708

And already released as the default format version in
* https://github.com/pingcap/tiflash/pull/4010/files
