### ISSUE TITLE
release-build: tiflash_cluster_manager will not overwrite existed content.

### ISSUE THREAD

**Issue by LittleFall** [pingcap/tiflash#2031]
When compiling cluster_manager by running `tics/release-centos7/build/build-cluster-manager.sh`, if the folder already exists, it will not be overwritten.

```sh
+ cp -r dist/flash_cluster_manager /data2/qizhi/zto-hotfix/tics/release-centos7/tiflash/flash_cluster_manager
cp: cannot overwrite non-directory ‘/data2/qizhi/zto-hotfix/tics/release-centos7/tiflash/flash_cluster_manager/flash_cluster_manager’ with directory ‘dist/flash_cluster_manager’
```

This may cause the tiflash build success but the cluster_manager build fails during build-release.sh, thus produce an incompatible package.

**Comment by zanmato1984** [comment]
Should have gone. Closing.
