### ISSUE TITLE
The new scaled-out tiflash store size and region count have almost not increased when add shuffle region scheduler

### ISSUE THREAD

**Issue by lilinghai** [pingcap/tiflash#2124]
Mini reproduce:
```
scheduler add shuffle-region-scheduler
TiUP scale-out a tiflash node
```

The new tiflash store size and region count have almost not increased. In the test cluster ,The new tiflash region count increases to about 20 after 1 hour.

**Comment by flowbehappy** [comment]
Expected behavior.
