### ISSUE TITLE
Build issue with apple M1

### ISSUE THREAD

**Issue by jiaqizho** [pingcap/tiflash#2303]
with build tics with M1 cpu.

error : 
```
/xxxx/tics/contrib/poco/Foundation/src/Environment.cpp:136:9: error: use of undeclared identifier 'POCO_ARCH_ARM64'
        return POCO_ARCH;
               ^
/xxxx/tics/contrib/poco/Foundation/include/Poco/Platform.h:191:20: note: expanded from macro 'POCO_ARCH'
        #define POCO_ARCH POCO_ARCH_ARM64
                          ^
```

similar with issue https://github.com/pingcap/tics/pull/2302

in submodule https://github.com/pingcap/poco need **rebase**.

or you just cherry-pick this fix : [fix iOS by adding missing ARM64 arch def](https://github.com/pocoproject/poco/commit/883728ec198b688fe5585a4fa07a148e882b5ace#diff-45e68511f7aa1e1c53944d08fe91c14ccd04f0bee5012fdf25fcca5404d90098)

M1 use the same marco `__arm64__` , this marco is missing in our repo version.

**Comment by zanmato1984** [comment]
Should have gone. Closing.
