### ISSUE TITLE
The cluster manager cores when tiup patch tiflash

### ISSUE THREAD

**Issue by lilinghai** [pingcap/tiflash#3177]
![image](https://user-images.githubusercontent.com/7677963/135255384-a3c77edc-7dde-4cb2-b5ee-0c6d993e9aad.png)

**Comment by JaySon-Huang** [comment]
close as we have removed the "cluster manager" in TiFlash and made it a part of TiDB since 6.0.
And for the older versions, failing to start cluster manager when tiup patch is moderate since we will try to start it again by timer.
