### ISSUE TITLE
TiFlash get stuck occasionally when mem-profiling is actived

### ISSUE THREAD

**Issue by JaySon-Huang** [pingcap/tiflash#3236]
Branch: https://github.com/JaySon-Huang/tics/tree/add_mem_prof

Start a TiFlash compiled with `-DENABLE_JEMALLOC_PROF=1`, and start tiflash with env `export MALLOC_CONF="prof:true,prof_active:true,lg_prof_interval:33"`, TiFlash get stuck occasionally. The stacks are as below:
[stuck-stacks-log.tar.gz](https://github.com/pingcap/tics/files/7352662/stuck-stacks-log.tar.gz)

**Comment by flowbehappy** [comment]
Change severity to minor since we don't do mem profile currently.
