### ISSUE TITLE
The return type of plus, minus, and multiply is different from tidb

### ISSUE THREAD

**Issue by fuzhe1989** [pingcap/tiflash#3474]
TiFlash:

https://github.com/pingcap/tics/blob/3893c2ac05f57d9c7542755c1673462c4f6c6d78/dbms/src/DataTypes/NumberTraits.h#L72-L75

[MySQL doc](https://dev.mysql.com/doc/refman/8.0/en/arithmetic-functions.html):
- In the case of -, +, and *, the result is calculated with BIGINT (64-bit) precision if both operands are integers.
- If both operands are integers and any of them are unsigned, the result is an unsigned integer. For subtraction, if the NO_UNSIGNED_SUBTRACTION SQL mode is enabled, the result is signed even if any operand is unsigned.
- If any of the operands of a +, -, /, *, % is a real or string value, the precision of the result is the precision of the operand with the maximum precision.

| operand_1 | operand_2 | TiDB | TiFlash|
|-----------|------------|------|--------|
| signed int8 | unsigned int8 | unsigned int64 | signed int16 |

also TiFlash has no overflow check for int plus/minus/multiply.

**Comment by fuzhe1989** [comment]
@windtalker does this issue still exist?

**Comment by windtalker** [comment]
Yes, I think it still exists.

**Comment by fuzhe1989** [comment]
> Yes, I think it still exists.

It could be another low-hanging fruits.
