### ISSUE TITLE
Profiling causing tiflash-proxy crash on arm

### ISSUE THREAD

**Issue by SchrodingerZhu** [pingcap/tiflash#3553]
## Bug Report

This may be hard to reproduce. use br to import data of `TPCH 100` and run profiling during the process. 

![image](https://user-images.githubusercontent.com/20108837/143556048-08f5ceba-3dde-446b-a8ed-2bc8df354a97.png)

**Comment by SchrodingerZhu** [comment]
addressed by https://github.com/pingcap/tidb-engine-ext/pull/64, https://github.com/pingcap/tidb-engine-ext/pull/65

**Comment by JaySon-Huang** [comment]
similar to https://github.com/pingcap/tiflash/issues/4172
