### ISSUE TITLE
 TiFlash does not work well in tiup playground cluster deployed in M1 Mac 

### ISSUE THREAD

**Issue by qqqdan** [pingcap/tiflash#3575]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
Use M1 Mac
1. set up a playground cluster:  tiup playground 
2. check the cluster status is good as follow
Pid   Role     Uptime
---   ----     ------
4202  pd       51.754518958s
4203  tikv     51.738899541s
4204  tidb     51.721640417s
4207  tiflash  44.548389417s
3. Run a profling in Dashboard , then tiflash does not work well. 
Pid   Role     Uptime
---   ----     ------
4202  pd       1m35.134909166s
4203  tikv     1m35.119291458s
4204  tidb     1m35.102036084s
4207  tiflash  signal: trace/BPT trap
![image](https://user-images.githubusercontent.com/19526717/144191946-4c00d2a9-51f6-4b90-b93f-cf64e3cce8be.png)

### 2. What did you expect to see? (Required)
Profiling feature can work well for tiflash.

**Comment by flowbehappy** [comment]
Closing it as duplicated with https://github.com/pingcap/tiflash/issues/3553
