### ISSUE TITLE
A tiflash node didn't apply snapshot for a long time in the scenario of mounts of writes

### ISSUE THREAD

**Issue by lilinghai** [pingcap/tiflash#3617]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

tpcc prepare 2000 warehouses ,32 thread
![2ygAvxoZyx](https://user-images.githubusercontent.com/7677963/145193761-5ad0cd8e-86a7-47fd-849f-1fc737ec121a.png)
![middle_img_v2_0cacc769-9632-42e1-9f3d-aaf4cb15e18g](https://user-images.githubusercontent.com/7677963/145198084-37a92b50-41e4-4e5c-8078-d85d2ab0d339.png)
![middle_img_v2_8b4e9d85-f7f7-4d0b-9097-f3082ddfc3fg](https://user-images.githubusercontent.com/7677963/145198133-ee9a4b19-e563-40df-9c38-c9b0b3d7bbb7.png)

### 2. What did you expect to see? (Required)
write flow balance
### 4. What is your TiFlash version? (Required)
5.3

**Comment by flowbehappy** [comment]
Looks like it is an expected behavior. Can we close it? @lilinghai

**Comment by lilinghai** [comment]
> Looks like it is an expected behavior. Can we close it? @lilinghai

ok
