### ISSUE TITLE
TiFlash cop thread pool can not handle request with high QPS

### ISSUE THREAD

**Issue by JaySon-Huang** [pingcap/tiflash#3696]
## Enhancement

One of our users execute queries like ```select count(*) from table where (`url` like 'xxx%') and `uid` in (....)``` in tidb. If the size of `uid` is more than several hundred, tidb choose to route that request to TiFlash, with about 15 QPS. 
![image](https://user-images.githubusercontent.com/4865550/146918701-5a70e61d-fbff-4f19-a9aa-a76c3cd5d9b3.png)

However, TiFlash can not handle those queries quickly, the request is lined up by the coprocessor thread pool. Requests are stacking up while TiDB sees all requests are "timeout" and retry, which makes more requests sent to TiFlash. Finally, it makes TiFlash out of memory.

"cop_dag" means those coprocessor requests are being executing and ...
![image](https://user-images.githubusercontent.com/4865550/146919125-0d4fc353-0d24-4c27-9966-a1da8e513366.png)

"cop" means the sum of those coprocessor requests are being executed and those requests are lined up.
![image](https://user-images.githubusercontent.com/4865550/146919301-6297cbf8-3772-461c-a8e9-0275934c04d7.png)

**Comment by JaySon-Huang** [comment]
Another similar problem from asktug: https://asktug.com/t/topic/694336/24

**Comment by LittleFall** [comment]
closed because https://github.com/pingcap/tiflash/issues/6438 has been basicly implemented
