### ISSUE TITLE
Enable batch cop for all TiFlash cop request by default

### ISSUE THREAD

**Issue by windtalker** [pingcap/tiflash#3751]
## Enhancement
In TiDB, there is a cop request mode named `BatchCop`, in this mode, TiDB will batch all the regions in one TiFlash node together, and only send one `BatchCop` to each TiFlash node. In the tranditional mode, TiDB will send a cop request for each region. If the region number is very big(more than 10k), `BatchCop` mode will reduce the number of RPC greatly. However, by default, TiDB only use Batch cop mode if the cop request contains `aggregation` or `topN`. We need to do some investigations of the `BatchCop` to see if we can enable batch cop for all TiFlash cop request by default.

**Comment by SeaRise** [comment]
Tidb currently uses mpp by default, so this issue can be closed
