### ISSUE TITLE
Support compact all data by SQL

### ISSUE THREAD

**Issue by flowbehappy** [pingcap/tiflash#4145]
## Feature Request
There are chances that the data in TiFlash is not very optimized. Like background GC workload failed to catch up cleaning old data after extending nodes. It causes too much outdate data in old TiFlash nodes, which affect query performance. Currently, we need to use tools like ch client to run SQLs to manually compact the data, which is very inconvenient. 

Consider providing SQL which can execute directly from TiDB:

```
alter table T compact tiflash replica; 
```

**Comment by breezewish** [comment]
Implemented in #4885
