### ISSUE TITLE
Add read_tso as tracing id to DeltaTree engine

### ISSUE THREAD

**Issue by JaySon-Huang** [pingcap/tiflash#4287]
## Enhancement
After https://github.com/pingcap/tiflash/pull/3632, we introduce DynamicThreadPool to reuse threads for handling incoming tasks. Then the "thread_id" record in PageStorage snapshot become less useful.

Add a "tracing_id" to the PageStorage snapshot, and use "read_tso" as the "tracing_id", it is more useful for locating bugs.

**Comment by breezewish** [comment]
Corresponding fields has been added in https://github.com/pingcap/tidb/pull/38191
