### ISSUE TITLE
Provide assertion facilities on both release and debug mode

### ISSUE THREAD

**Issue by fuzhe1989** [pingcap/tiflash#4352]
## Enhancement

For some logic errors just throw is not safe: the process state might be already wrong. `assert` can be only used on debug mode. We might need a new way to assert some conditions on both release and debug mode.

It's output could be redirected to [fatal.log](#4351).

**Comment by breezewish** [comment]
Looks like RUNTIME_CHECK and RUNTIME_ASSERT is not used. Maybe we should migrate current `if (unlikely(...)) { .. }` into this pattern?
