### ISSUE TITLE
TPCH-100 makes TiFlash stuck at read index

### ISSUE THREAD

**Issue by SchrodingerZhu** [pingcap/tiflash#4409]
## Bug Report

Enabling TiFlash Replica during TPCH Prepare.

![image](https://user-images.githubusercontent.com/20108837/159842627-3632947c-358e-4b47-8653-1ce3dff7d1bd.png)

After 9:00. we see a sharp drop at `write block`

![image](https://user-images.githubusercontent.com/20108837/159842747-736313fd-fe3c-41e7-a667-29a98efcaef9.png)

Before that, every query for `count(*) from lineitem` returns normally. After that, TiFlash begins to stuck at query.

![image](https://user-images.githubusercontent.com/20108837/159842878-4e670bf8-7d3b-4b61-bbba-feeaf40963be.png)

**Comment by hehechen** [comment]
Can't reproduce in ecd615f20. It may be caused by environmental factors, such as other people are also using the environment, a node is under high load, or TiKV OOM. I will do a few more experiments to try to reproduce.

**Comment by flowbehappy** [comment]
Close it due to unreproducable.
