### ISSUE TITLE
Infinite loop when hardlink is enabled and exist incomplete writebatch

### ISSUE THREAD

**Issue by JaySon-Huang** [pingcap/tiflash#4426]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

enable hardlink by 
```
profiles.default.dt_storage_pool_log_gc_force_hardlink_rate : 0.8
profiles.default.dt_storage_pool_data_gc_force_hardlink_rate : 0.8
profiles.default.dt_storage_pool_meta_gc_force_hardlink_rate : 0.8
```

restart tiflash and check the logging

### 2. What did you expect to see? (Required)
The hard link optimization can run normally

### 3. What did you see instead (Required)
Infinite loop

```
[2022/03/24 11:22:28.315 +00:00] [WARN] [<unknown>] ["PageFile:[expect_batch_bytes=4160631355] [meta_size=36382152] [file=/data0/db/data/t_71/log/page_1788_3/meta] ignored."] [thread_id=29]
```

![image](https://user-images.githubusercontent.com/4865550/159909119-d3cc09e0-d877-4014-8f38-1024c67b4f6d.png)

**Comment by flowbehappy** [comment]
Hardlink is abandoned, and it is never used in any version. So change the severity to minor.
