### ISSUE TITLE
Support Stale Read

### ISSUE THREAD

**Issue by flowbehappy** [pingcap/tiflash#4483]
## Enhancement
https://docs.google.com/document/d/1ZORyeNAl-lWydU3mUIRMgRTcFKE5IpR2u0tOAyNq89k/edit?n=Follower_to_serve_local%28stale%29_read#heading=h.qn6s8mxylwbg

Benefits:

1. Eliminates read index duration
2. Greatly reduce wait index duration

And I haven't found any significant drawbacks.

**Comment by JaySon-Huang** [comment]
released since v6.6.0
