### ISSUE TITLE
There is no supertype for types Decimal(65,0), Decimal(20,20) because the least supertype is Decimal(85,20)

### ISSUE THREAD

**Issue by fzhedu** [pingcap/tiflash#4519]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
mysql -uroot -P52324 -h172.16.4.97 -D subquery_agg_decimal3000

SELECT    table1 . `col_decimal_65_not_null_key` AS field1 , table2 . `col_decimal_30_10_unsigned_key` AS field2 , table2 . `col_decimal_20_20_unsigned_key` AS field3 FROM ( A AS table1 INNER JOIN B AS table2 ON (( table2 . `col_decimal_65_key` = table1 . `col_decimal_2
    0_20_not_null` ) AND ( table2 . `col_decimal` = table1 . `col_decimal_30_10_key` ) ) ) WHERE ( table1 . `col_decimal_key`  BETWEEN 131 AND ( 131 + 47 ) OR ( table1 . `col_decimal_65_10_key` NOT IN (131, 79, 164, 139) OR table1 . `col_int_key` > 131 AND table1 . `col_int    _key` < ( 131 + 64 ) ) ) OR table1 . `col_decimal_30_not_null` <= -8.16  GROUP BY field1, field2, field3  ORDER BY field1, field2, field3 , table1 . `col_decimal_65_not_null_key`  ;

### 2. What did you expect to see? (Required)
mysql and  tidb+tikv run ok

### 3. What did you see instead (Required)
`ERROR 1105 (HY000) at line 1: other error for mpp stream: DB::Exception: Exchange receiver meet error : DB::Exception: There is no supertype for types Decimal(65,0), Decimal(20,20) because the least supertype is Decimal(85,20)`

### 4. What is your TiFlash version? (Required)
nightly

**Comment by fzhedu** [comment]
https://github.com/pingcap/tiflash/blob/c7510734bf6b57a072e3c67ee602c183440aa990/dbms/src/Flash/Coprocessor/DAGQueryBlockInterpreter.cpp#L447
```
/// ClickHouse require join key to be exactly the same type
/// TiDB only require the join key to be the same category
/// for example decimal(10,2) join decimal(20,0) is allowed in
/// TiDB and will throw exception in ClickHouse
void getJoinKeyTypes(const tipb::Join & join, DataTypes & key_types)
{
    for (int i = 0; i < join.left_join_keys().size(); i++)
    {
        if (!exprHasValidFieldType(join.left_join_keys(i)) || !exprHasValidFieldType(join.right_join_keys(i)))
            throw TiFlashException("Join key without field type", Errors::Coprocessor::BadRequest);
        DataTypes types;
        types.emplace_back(getDataTypeByFieldTypeForComputingLayer(join.left_join_keys(i).field_type()));
        types.emplace_back(getDataTypeByFieldTypeForComputingLayer(join.right_join_keys(i).field_type()));
        DataTypePtr common_type = getLeastSupertype(types);
        key_types.emplace_back(common_type);
    }
}
```
this issue is introduced by design.

**Comment by fzhedu** [comment]
mysql> SELECT ( table2 . `col_decimal_30_10`) AS field1 FROM CC AS table2 INNER JOIN A AS table3 ON table3 . `col_decimal_65_10_key` = table2 . `col_decimal_20_20_not_null`;
ERROR 1105 (HY000): other error for mpp stream: DB::Exception: There is no supertype for types Decimal(20,20), Decimal(65,10) because the least supertype is Decimal(75,20)

**Comment by SeaRise** [comment]
```
create table test.test (
col_decimal_65_10_key decimal(65, 10) not null, 
col_decimal_30_10 decimal(30, 10), 
col_decimal_20_20_not_null decimal(20, 20) NOT NULL
);
select * from
test t1 join test t2 on t1.col_decimal_65_10_key = t2.col_decimal_20_20_not_null;

ERROR 1105 (HY000): other error for mpp stream: From MPP<query:436883374408728577,task:2>: Code: 386, e.displayText() = DB::Exception: There is no supertype for types Decimal(65,10), Decimal(20,20) because the least supertype is Decimal(75,20), e.what() = DB::Exception,
```
