### ISSUE TITLE
After one of the TiFlash nodes was upgraded from 5.2 to 5.3, the results of the MPP query were inconsistent.

### ISSUE THREAD

**Issue by hehechen** [pingcap/tiflash#4579]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

2 TiFlash nodes in 5.2.3, TPCH-100 with 2 TiFlash replicas, upgrade one TiFlash node to 5.3.1,  and execute `q1` query:
` select l_returnflag, l_linestatus, sum(l_quantity) as sum_qty, sum(l_extendedprice) as sum_base_price, sum(l_extendedprice * (1 - l_discount)) as sum_disc_price, sum(l_extendedprice * (1 - l_discount) * (1 + l_tax)) as sum_charge, avg(l_quantity) as avg_qty, avg(l_extendedprice) as avg_price, avg(l_discount) as avg_disc, count(*) as count_order from lineitem where l_shipdate <= date_sub('1998-12-01', interval 108 day) group by l_returnflag, l_linestatus order by l_returnflag, l_linestatus;`

Execute multiple times and see if the results are consistent.

### 2. What did you expect to see? (Required)
 The results are always consistent and correct.

### 3. What did you see instead (Required)
The results are inconsistent and wrong sometimes.
![origin_img_v2_fdef6a34-31f1-4f5e-8cc2-c78e5fd705dg](https://user-images.githubusercontent.com/14118780/161411793-2086d0b4-b346-484e-8d12-3b03779e8319.png)

### 4. What is your TiFlash version? (Required)
5.2.3 upgrade to 5.3.1

**Comment by zanmato1984** [comment]
This issue can't be fixed in code. We put a warning about how to avoid this problem in our doc: https://docs.pingcap.com/zh/tidb/v5.3/upgrade-tidb-using-tiup#%E4%B8%8D%E5%81%9C%E6%9C%BA%E5%8D%87%E7%BA%A7

Closing.
