### ISSUE TITLE
tiflash-proxy compile error

### ISSUE THREAD

**Issue by zhangxi123051** [pingcap/tiflash#4580]
<img width="1085" alt="image" src="https://user-images.githubusercontent.com/4017799/161428697-5f46adec-17d2-4b04-856a-2c541d37559e.png">
![1431648989426_ pic](https://user-images.githubusercontent.com/4017799/161428802-488ba134-95db-4c63-bb25-75a32b878e0c.jpg)

**Comment by fuzhe1989** [comment]
@zhangxi123051 please ensure you are linking the libc++ (not libstdc++).

**Comment by yudongusa** [comment]
@zhangxi123051 thanks for submitting the issue. Here, please make sure to use English in the issue so that all the community may understand. Thanks again~

**Comment by SchrodingerZhu** [comment]
@zhangxi123051 you can set `CXXFLAGS=-w` as a workaround. @fuzhe1989 I think titan stuffs in proxy should be updated.
