### ISSUE TITLE
[TSAN] Data race at Metric Familiy

### ISSUE THREAD

**Issue by SchrodingerZhu** [pingcap/tiflash#4595]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```
cmake /path/to/tiflash -DCMAKE_BUILD_TYPE=TSan -GNinja
ninja gtests_dbms
# run gtests_dbms
```

### 2. What did you expect to see? (Required)

No tsan error.

### 3. What did you see instead (Required)

https://ci.pingcap.net/blue/rest/organizations/jenkins/pipelines/tiflash-sanitizer-daily/runs/145/nodes/78/log/?start=0

### 4. What is your TiFlash version? (Required)

```
master
```

**Comment by Benjamin2037** [comment]
上面链接的tsan结果是不是删除掉了？能访问测试环境么？
