### ISSUE TITLE
The result of having not if null(null >= a) is not correct

### ISSUE THREAD

**Issue by River2000i** [pingcap/tiflash#4639]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```sql
drop table if exists t1;
create table t1 (a int AUTO_INCREMENT primary key, b int);
insert into t1(b) value(null);
insert into t1(b) value(-1);
insert into t1(b) value(0);
insert into t1(b) value(20);
alter table t1 set tiflash replica 1;
set session tidb_isolation_read_engines = 'tiflash';
select count(*) from t1 group by a having not ifnull(null >= `a`, null);
```

### 2. What did you expect to see? (Required)
```sql
mysql> select count(*) from t1 group by a having not ifnull(null >= `a`, null);
Empty set (0.05 sec)

```
### 3. What did you see instead (Required)
```sql
mysql> select count(*) from t1 group by a having not ifnull(null >= `a`, null);
+----------+
| count(*) |
+----------+
|        1 |
|        1 |
|        1 |
|        1 |
+----------+
4 rows in set (0.06 sec)
```
### 4. What is your TiFlash version? (Required)
TiFlash
Release Version: v6.1.0-nightly
Edition:         Community
Git Commit Hash: 26d4f4a38ab296fb38bdb162a07912226c59402c
Git Branch:      heads/refs/tags/v6.1.0-nightly
UTC Build Time:  2022-04-12 22:58:20
Enable Features: jemalloc avx avx512 unwind
Profile:         RELWITHDEBINFO

Raft Proxy
Git Commit Hash:   5874ff95712aedcfd62c4b6f352a3420126cbc9a
Git Commit Branch: HEAD
UTC Build Time:    2022-04-12 23:03:41
Rust Version:      rustc 1.53.0-nightly (16bf626a3 2021-04-14)
Storage Engine:    tiflash
Prometheus Prefix: tiflash_proxy_
Profile:           release

**Comment by xzhangxian1008** [comment]
Reproduce Steps:
```
drop table if exists t1;
create table t1 (a int AUTO_INCREMENT primary key, b int);
insert into t1(b) value(null);
insert into t1(b) value(-1);
insert into t1(b) value(0);
insert into t1(b) value(20);
alter table t1 set tiflash replica 1;
set session tidb_isolation_read_engines = 'tiflash';
select count(*) from t1 group by a having not ifnull(null >= `a`, null);
```

What I see:
```
mysql> drop table if exists t1;
Query OK, 0 rows affected (0.18 sec)

mysql> create table t1 (a int AUTO_INCREMENT primary key, b int);
Query OK, 0 rows affected (0.07 sec)

mysql> insert into t1(b) value(null);
Query OK, 1 row affected (0.01 sec)

mysql> insert into t1(b) value(-1);
Query OK, 1 row affected (0.00 sec)

mysql> insert into t1(b) value(0);
Query OK, 1 row affected (0.00 sec)

mysql> insert into t1(b) value(20);
Query OK, 1 row affected (0.00 sec)

mysql> alter table t1 set tiflash replica 1;
Query OK, 0 rows affected (0.07 sec)

mysql> set session tidb_isolation_read_engines = 'tiflash';
Query OK, 0 rows affected (0.00 sec)

mysql> select count(*) from t1 group by a having not ifnull(null >= `a`, null);
Empty set (0.03 sec)
```

I can't reproduce this bug in the following environment.

mysql> select * from information_schema.cluster_info;
+---------+----------------+-----------------+-------------------------+-----------+
| TYPE    | INSTANCE       | STATUS_ADDRESS  | VERSION                 | GIT_HASH| 
--------------------------------------+---------------------------+----------------+
| tidb    | 127.0.0.1:6003 | 127.0.0.1:18357 | 6.1.0                   | 1a89dec |
| pd      | 127.0.0.1:6000 | 127.0.0.1:6000  | 6.1.0                   | d82f4fa |
| tikv    | 127.0.0.1:6006 | 127.0.0.1:18360 | 6.1.0                   | 080d086 |
| tikv    | 127.0.0.1:6007 | 127.0.0.1:18361 | 6.1.0                   | 080d086 |
| tikv    | 127.0.0.1:6008 | 127.0.0.1:18362 | 6.1.0                   | 080d086 | 
| tiflash | 127.0.0.1:3930 | 127.0.0.1:20292 | 6.2.0-alpha-25-g5b61ae7 | 5b61ae7 |
+---------+----------------+-----------------+-------------------------+-----------+


TiFlash
Release Version: v6.2.0-alpha-25-g5b61ae7
Edition:         Community
Git Commit Hash: 5b61ae70550624d3bf0b5ca6bac89013ed5a6a4b
Git Branch:      issue_4639
UTC Build Time:  2022-06-13 12:45:22
Enable Features: jemalloc failpoints avx avx512 unwind
Profile:         DEBUG

Raft Proxy
Git Commit Hash:   ca2f51f94e55bdd23749dcc02ab4afb94eeb5ae5
Git Commit Branch: HEAD
UTC Build Time:    2022-06-13 12:45:50
Rust Version:      rustc 1.60.0-nightly (1e12aef3f 2022-02-13)
Storage Engine:    tiflash
Prometheus Prefix: tiflash_proxy_
Profile:           release
