### ISSUE TITLE
TiFlash mpp query failed due to `keepalive timeout` randomly

### ISSUE THREAD

**Issue by windtalker** [pingcap/tiflash#4662]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
The same as #4192

**Comment by windtalker** [comment]
closed by #4655

**Comment by zanmato1984** [comment]
comment

**Comment by zanmato1984** [comment]
update

**Comment by zanmato1984** [comment]
update
