### ISSUE TITLE
Single table with 7000 partitioned tables，Sync to tiflash

### ISSUE THREAD

**Issue by buggithubs** [pingcap/tiflash#4676]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

Questions from： https://github.com/pingcap/tidb/issues/34011

### 3. What did you see instead (Required)

From 11:00 to 15:00, the synchronization data progress is approximately equal to 0.14.

![origin_img_v2_299d6abe-69fd-4db1-a113-9a591ccf978g](https://user-images.githubusercontent.com/11624213/163538064-ea00d782-a458-4029-95f6-78eb538625ec.jpg)
![origin_img_v2_28bc9f6b-e1bb-45e2-ade0-de1fce9da53g](https://user-images.githubusercontent.com/11624213/163538079-f9ea228d-3cc9-4435-bf01-94be20fc071f.jpg)
![origin_img_v2_95053440-f825-4e36-b54e-c32cb170134g](https://user-images.githubusercontent.com/11624213/163538085-4dcaf1f8-c0eb-4206-8ad8-f98612cd727e.jpg)
![origin_img_v2_d8f035fe-bca8-457d-9a19-232414f4e94g](https://user-images.githubusercontent.com/11624213/163538095-2cd9bbf8-56e0-4a41-8f02-7275b3cd6cc4.jpg)

### 4. What is your TiFlash version? (Required)

v6.1.0 
e192ce5db1e55b6f14d8a3346327b5a8b245b9e3

**Comment by flowbehappy** [comment]
It is expected. At first there were lots of empty regions. So the number of regions increases fast.
