### ISSUE TITLE
Configuration profiles.default.background_pool_size not take effect.

### ISSUE THREAD

**Issue by JinheLin** [pingcap/tiflash#4684]
### 1. Minimal reproduce step (Required)

Set configuration `profiles.default.background_pool_size: 8`.

### 2. What did you expect to see? (Required)

Create `BackgroundProcessingPool` with 8 threads.

### 3. What did you see instead (Required)

```
[2022/04/15 19:53:55.826 +08:00] [INFO] [<unknown>] ["BackgroundProcessingPool:Create BackgroundProcessingPool with 16 threads"] [thread_id=1]
```

### 4. What is your TiFlash version? (Required)

master

**Comment by flowbehappy** [comment]
So background_pool_size is determined by the actual core number?

**Comment by JinheLin** [comment]
> So background_pool_size is determined by the actual core number?

It is currently hard-coded.
```
#define DBMS_DEFAULT_BACKGROUND_POOL_SIZE 16
```
