### ISSUE TITLE
BackgroundProcessingPool::getThreadIds() misses some thread ids.

### ISSUE THREAD

**Issue by JinheLin** [pingcap/tiflash#4685]
### 1. Minimal reproduce step (Required)

Start TiFlash and query the log.

### 2. What did you expect to see? (Required)

`BackgroundProcessingPool::getThreadIds().size()` equals to `BackgroundProcessingPool::getNumberOfThreads()`.

### 3. What did you see instead (Required)

`BackgroundProcessingPool::getThreadIds().size()` less than `BackgroundProcessingPool::getNumberOfThreads()`.

### 4. What is your TiFlash version? (Required)

master

**Comment by flowbehappy** [comment]
Fixed by
https://github.com/pingcap/tiflash/pull/4686
