### ISSUE TITLE
Better data batching method for Exchange

### ISSUE THREAD

**Issue by fuzhe1989** [pingcap/tiflash#4690]
## Overview

Some potential optimizations:
- [ ] #4693
- [ ] #4694
- [ ] #4695

## Details

Batching is a well-known optimization for data systems. In `StreamingDAGResponseWriter` we could enable batching by setting `batch_send_min_limit` to a large enough value (-1 by default which means disabled).

When batching is enabled, `StreamingDAGResponseWriter` will first gather enough blocks, then apply following operations for each block:
1. Calculate hash values of all rows.
4. Scatter each block to P blocks (P is partition number).
5. Encode each block to a chunk.

Each round `StreamingDAGResponseWriter` will generate P packets, each of which contains multiple chunks, one per block.

This mechanism has some disadvantages:
1. It will generate too many chunks and lead to inefficient calculation due to data fragmentation.
2. It's hard to determine `batch_send_min_limit` since after partitioning different partition will have different rows. A large `batch_send_min_limit` may cause some partitions too large while small `batch_send_min_limit` may exacerbate the data fragmentation.

> Still, the biggest problem is batching is disabled by default.

@riteme introduced a way to batch data per partition in #3787:
1. For each partition, `StreamingDAGResponseWriter` holds a block.
2. Every time `StreamingDAGResponseWriter` receives a block, it will calculate the hash values, then scatter this block, not to P new blocks, but append to P existed blocks. `IColumn::scatterTo` is used for this purpose.
3. When the size of any partition reaches the limit, convert the corresponding block to a packet and send to its peer. Then renew a block for this partition.

This method has extra data copies versus to scatter each block into new blocks. We may need some benchmark for determining which kind of cost is dominate, data copy or data fragmentation.

Besides, we can also gather chunks at receiver side. The current `NativeBlockInputStream` + `SquashingBlockInputStream` solution will write data multiple times, we could combine them into one operator and directly gather multiple chunks into one block.

**Comment by ywqzzy** [comment]
Maybe the first step of the optimization issues is to make the benchmark great again?
