### ISSUE TITLE
Remove some duplicated member functions in Context

### ISSUE THREAD

**Issue by JinheLin** [pingcap/tiflash#4740]
## Enhancement

[Some member functions](https://github.com/pingcap/tiflash/blob/master/dbms/src/Interpreters/Context.h#L296-L302) in `Context` are duplicated.
```
    DatabasePtr getDatabase(const String & database_name) const;
    DatabasePtr getDatabase(const String & database_name);
    DatabasePtr tryGetDatabase(const String & database_name) const;
    DatabasePtr tryGetDatabase(const String & database_name);

    Databases getDatabases() const;
    Databases getDatabases();
```

**Comment by junaire** [comment]
I would like to help~

**Comment by JinheLin** [comment]
> I would like to help~

Thank you very much. Please open a pull request when your code is ready.

**Comment by junaire** [comment]
> > I would like to help~
> 
> Thank you very much. Please open a pull request when your code is ready.

In fact, I have some trouble building the project, I've opend https://github.com/pingcap/tiflash/issues/4771

**Comment by junaire** [comment]
Hey @JinheLin, I think I may have trouble understanding the issue, could you please clarify in which way the methods are duplicated? Do you mean remove the non-const version, or remove `Context::getDatabase` and only use `Context::tryGetDatabase` ?

**Comment by JinheLin** [comment]
> 

Removing the non-const version is enough and there should be no effect on other code.
