### ISSUE TITLE
DeltaMerge return wrong result

### ISSUE THREAD

**Issue by lidezhu** [pingcap/tiflash#4747]
## Bug Report

On a customer environment, select on a table return the following error:
DeltaMerge return wrong result, current handle[8070450532252511967]version[432677394077974556]@read[56]@pos[2022] is expected >= last_handle[8070450532252560947]last_version[432677778184470534]@read[56]@pos[2021] 

### 4. What is your TiFlash version? (Required)
all relase branch influenced

**Comment by lddlww** [comment]
hi， is the issue fixed now？ if so which tiflash version should i use（my product tiflash version is ```v5.3.0```）？

**Comment by JaySon-Huang** [comment]
> hi， is the issue fixed now？ if so which tiflash version should i use（my product tiflash version is `v5.3.0`）？

This bug has been fixed in the latest patch version, v5.3.2+, v5.4.1+, v6.1.0+, v6.5.0+. I would recommend you use the latest patch version of LTS, which is 6.1.3/6.5.0 now.
