### ISSUE TITLE
`MinMaxIndex::read` may throw exception  if `index_file_size ` is 1048592

### ISSUE THREAD

**Issue by hehechen** [pingcap/tiflash#4752]
https://github.com/pingcap/tiflash/blob/c7510734bf6b57a072e3c67ee602c183440aa990/dbms/src/Storages/DeltaMerge/File/DMFilePackFilter.h#L257

`frame_total_size` should be `ChecksumFrameLength` + header_size. If `index_file_size ` is 1048592 (16 + 1048576, 1048576 is the frame length), `MinMaxIndex::read` will throw exception because `bytes_read != bytes_limit`.

**Comment by JaySon-Huang** [comment]
Another related issue: https://github.com/pingcap/tiflash/issues/4778
