### ISSUE TITLE
Refactor FmtBuffer::joinStr

### ISSUE THREAD

**Issue by ywqzzy** [pingcap/tiflash#4755]
## Enhancement
Currently the use of joinStr is not that user friendly.
![BhfTzOvsuJ](https://user-images.githubusercontent.com/26179892/165049086-66baaadf-e99c-4b0c-8b4c-17a058ee89d8.png)

We don't have to pass Fmtbuffer itself to the toStringFunc.

**Comment by fuzhe1989** [comment]
Then how would you keep the append semantic, i.e. always call `FmtBuffer::append`?

**Comment by ywqzzy** [comment]
> Then how would you keep the append semantic, i.e. always call `FmtBuffer::append`?
Maybe can be used like that:
```
  buffer.joinStr(v.cbegin(), v.cend())
        .joinStr(
            v.cbegin(),
            v.cend(),
            [&buffer](const auto & s) { buffer.append(s); buffer.append("t"); },
            ", ");
```
The implementation will be like that:
```
template <typename Iter>
    FmtBuffer & joinStr(
        Iter first,
        Iter end,
        StringRef delimiter)
    {
        auto func = [this](const auto & s) {
            this->append(s);
        };
        return joinStr(first, end, func, delimiter);
    }

    template <typename Iter, typename FF>
    FmtBuffer & joinStr(
        Iter first,
        Iter end,
        FF && toStringFunc, // void (const auto &, FmtBuffer &)
        StringRef delimiter)
    {
        if (first == end)
            return *this;
        toStringFunc(*first);
        ++first;
        for (; first != end; ++first)
        {
            append(delimiter);
            toStringFunc(*first);
        }
        return *this;
    }
```

But in this case, user must pass `&buffer` to the toStringFunc.
IMO, maybe no need to do the change

**Comment by fuzhe1989** [comment]
@ywqzzy your implementation will lead to a wrong result if people forgot to bind/capture a `FmtBuffer` with `toStringFunc`, imagine `toStringFunc` be a pure function.

**Comment by Lloyd-Pottiger** [comment]
How about:
```cpp
FmtBuffer & joinStr(
      Iter first,
      Iter end,
      FF && toStringFunc, // String (const auto &)
      StringRef delimiter)
  {
      for (auto it = first; it != end; ++it)
      {
          fmtAppend(&"%s %s"[2 * (it==first)], delimiter, toStringFunc(*it));
      }
      return *this;
  }
```

**Comment by fuzhe1989** [comment]
@Lloyd-Pottiger then `toStringFunc` must generate a string first, then append it to the buffer, which downgrades the performance.

**Comment by fuzhe1989** [comment]
but yes, your version looks very nice.

**Comment by Lloyd-Pottiger** [comment]
> @Lloyd-Pottiger then `toStringFunc` must generate a string first, then append it to the buffer, which downgrades the performance.

I think the performance difference may be small enough to be negligible. We can write a test to compare the performance. @ywqzzy What is your opinion?

**Comment by ywqzzy** [comment]
> @Lloyd-Pottiger then `toStringFunc` must generate a string first, then append it to the buffer, which downgrades the performance.

I have benched it.
![RppOmqNkQl](https://user-images.githubusercontent.com/26179892/165489467-23cd6414-eddd-4bdc-a125-ab4d7631f4a1.png)

**Comment by ywqzzy** [comment]
> using in this way:
> 
> ```c++
>  buffer..joinStr(
>             v.cbegin(),
>             v.cend(),
>             [](const auto & s) -> String { if (s == 0) return "Y"; else return "N"; },
>             ", ");
> ```

The bench result of the code which is the v2 in benchmark.
![1651063696(1)](https://user-images.githubusercontent.com/26179892/165521702-bc6e56a4-a710-4567-8d05-b5308dd12619.png)

**Comment by Lloyd-Pottiger** [comment]
@fuzhe1989 Do you think it is acceptable? Or any ideas to improve?

**Comment by fuzhe1989** [comment]
@Lloyd-Pottiger hmmm my suggestion is that: the original method could provide higher performance and we'd better keep it as is; the v2 version is easy to use, how about add a new method like `joinStrPure` or something else?

**Comment by Lloyd-Pottiger** [comment]
> @Lloyd-Pottiger hmmm my suggestion is that: the original method could provide higher performance and we'd better keep it as is; the v2 version is easy to use, how about add a new method like `joinStrPure` or something else?

I agree
