### ISSUE TITLE
Adding mysql variable max_threads for TiFlash.

### ISSUE THREAD

**Issue by mengxin9014** [pingcap/tiflash#4794]
## Enhancement
Need adding mysql variable max_threads for TiFlash.

Now if we want change max_threads in TiFlash, we need modify TiFlash config and restart TiFlash.
So we add mysql variable max_threads that we can just set max_threads in TiDB client to make the param go into effect in a session immediately.

**Comment by JaySon-Huang** [comment]
`... and restart TiFlash`

actually, we don't need to restart TiFlash after changing max_threads in the config file. It will be automatically reload once the config file is changed.

https://github.com/pingcap/tiflash/blob/e845908faadb974497836f9e5dc5f1c92e90c86a/dbms/src/Server/Server.cpp#L1250-L1253

**Comment by mengxin9014** [comment]
> 

Maybe it needs to update the config file on each node.
Detailed requirement is here： https://pingcap.feishu.cn/wiki/wikcnHqT9XlW24wHVLRwwyHMLCh#1JcZA7

**Comment by mengxin9014** [comment]
> `... and restart TiFlash`
> 
> actually, we don't need to restart TiFlash after changing max_threads in the config file. It will be automatically reload once the config file is changed.
> 
> https://github.com/pingcap/tiflash/blob/e845908faadb974497836f9e5dc5f1c92e90c86a/dbms/src/Server/Server.cpp#L1250-L1253

Maybe it needs to update the config file on each node.
Detailed requirement is here： https://pingcap.feishu.cn/wiki/wikcnHqT9XlW24wHVLRwwyHMLCh#1JcZA7

**Comment by JaySon-Huang** [comment]
Related TiDB issue: https://github.com/pingcap/tidb/issues/34298
