### ISSUE TITLE
Disable raft-engine in TiKV6.0-based TiFlash proxy

### ISSUE THREAD

**Issue by CalvinNeo** [pingcap/tiflash#4821]
## Enhancement

Currently, we have TiFlash proxy based on tikv/4dd5a13e1b7f4f2141abd79d4e4a7e8b5fb7c1a0. However, TiKV has been experienced some modifications since this commit, including disabling raft-engine, which is a great feature. So we need to merge tikv/release-6.0 again.

TiKV has then disabled raft-engine in TiKV 6.0, so we must disable this in Proxy.

Though we don't support downgrade, however, it will cause problems like
```
[2022/05/05 11:03:59.707 +08:00] [FATAL] [setup.rs:320] ["invalid configuration: Found multiple raft data sets: /data1/jiaqizho/tidb-data-jiaqizho/tiflash-36772/flash/raft, /data1/jiaqizho/tidb-data-jiaqizho/tiflash-36772/flash/raft-engine"]
```

**Comment by JaySon-Huang** [comment]
Does it affect any release version of TiFlash? Or only happen in the master branch?

**Comment by jiaqizho** [comment]
> Does it affect any release version of TiFlash? Or only happen in the master branch?

@JaySon-Huang In fact, this is caused by downgrading first and upgrading later.
