### ISSUE TITLE
TiFlash can't raise the original error sometimes

### ISSUE THREAD

**Issue by lilinghai** [pingcap/tiflash#4823]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

In the ddl case, the tiflash should raise `Exchange receiver meet error : DB::TiFlashException: Table 66 schema version 109 newer than query schema version   108`, but it raise `other error for mpp stream: DB::Exception: query canceled` to the tidb.
### 3. What did you see instead (Required)
raise original error to tidb.
### 4. What is your TiFlash version? (Required)
v5.4.1

**Comment by lilinghai** [comment]
another case `Error 1105: DB::TiFlashException: Failed to register MPP Task MPP<query:435585897354231858,task:29>, reason: query is being aborted`

**Comment by SeaRise** [comment]
Seems has been fixed by https://github.com/pingcap/tiflash/pull/7658
