### ISSUE TITLE
Boolean configuration should support 'true' or 'fasle'

### ISSUE THREAD

**Issue by hehechen** [pingcap/tiflash#4827]
Some boolean configuration in TiFlash don't support `true` or `false`, only support `0` to disable and other number value to enable, for example `enable_ps_v3` and `lazily_init_store`.
https://github.com/pingcap/tiflash/blob/702b7d17ecbb940bbcb49d633983b7c951c84c8f/dbms/src/Server/StorageConfigParser.cpp#L208

In https://github.com/pingcap/tiflash/issues/938, boolean configurations in `profiles.default` have  supported `true` and `false`, I think other configurations should support too. Otherwise it will confuse users. For example, If the user set `enable_ps_v3` to `true`, actually it will be parsed to `0` because `true` is not the number.

**Comment by lidezhu** [comment]
Fixed in https://github.com/pingcap/tiflash/pull/4831
