### ISSUE TITLE
delta tree performance test tool found performance drop

### ISSUE THREAD

**Issue by River2000i** [pingcap/tiflash#4848]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 2. What did you expect to see? (Required)
performance gap less than 5%

### 3. What did you see instead (Required)
uniform workload : 
["Write Speed(rows count) data and diff"] [base=381777] ["this time"=327441] ["diff percentage"=-14.23%] ["standard gap"=5.00%]
incremental workload :
["Write Speed(rows count) data and diff"] [base=224131] ["this time"=197334] ["diff percentage"=-11.96%] ["standard gap"=5.00]

performance data record:
http://perf.pingcap.net/d/t8S6iJ_7k/tiflash-dtworkload-performance?orgId=1&from=now-20d&to=now

### 4. What is your TiFlash version? (Required)
TiFlash Release Version: v6.1.0-nightly 
Edition:         Community 
Git Commit Hash: 4ad156b924c88233bb7d9da43f2f47d249a16cdb 
Git Branch:      heads/refs/tags/v6.1.0-nightly 
UTC Build Time:  2022-05-06 10:57:22 
Enable Features: jemalloc avx avx512 unwind 
Profile:         RELWITHDEBINFO  
Raft Proxy Git Commit Hash:   a03434d3758bee4fa335ce87da5f772eebe8f9cc 
Git Commit Branch: HEAD 
UTC Build Time:    2022-05-06 11:06:05 
Rust Version:      rustc 1.60.0-nightly (1e12aef3f 2022-02-13) 
Storage Engine:    tiflash 
Prometheus Prefix: tiflash_proxy_ 
Profile:           release

**Comment by River2000i** [comment]
more information:
new performance drop:
log : http://rms.pingcap.net:31714/artifacts/testground/plan-exec-786506-rj9q2/plan-exec-786506-rj9q2-3406653061/main-logs
commit:
https://github.com/pingcap/tiflash/commit/f601de130d9f74141f654c2f63813d0aae1830d4
latest success commit:
https://github.com/pingcap/tiflash/commit/2b2750b7dfd7823be7c33e290492e1f8cffe1a76

**Comment by JinheLin** [comment]
According to the metrics, the degradation of performance happened in 2022-05-06 and 2022-05-10 and the performance in 2022-05-08 is normal.

**I guess it may be affected by machine jitter. I think we should refer to the test results a few more times.**

Note: Due to release testing of TiDB, the machine resources are insufficient these days and the performance testing is suspended since 2022-05-10.
