### ISSUE TITLE
Consider use specific compression algorithms for different columns

### ISSUE THREAD

**Issue by fuzhe1989** [pingcap/tiflash#4888]
## Enhancement

1. When persistent on disk.
2. When transmit through network.

**Comment by JaySon-Huang** [comment]
I think @fuzhe1989 filed this issue for the compression algorithm on the specified data type. For example,  run-length encoding on integers, Gorilla on floating numbers [ClickHouse/src/Compression/CompressionCodecGorilla.cpp](https://github.com/ClickHouse/ClickHouse/blob/b1f177e2ae27cd0b9011100568e52f8ce2fc7716/src/Compression/CompressionCodecGorilla.cpp#L25-L30)

**Comment by fuzhe1989** [comment]
@JaySon-Huang yes, e.g.
- https://github.com/lemire/FastPFor
- https://github.com/lemire/streamvbyte
