### ISSUE TITLE
The config of storage.main.capacity may be useless

### ISSUE THREAD

**Issue by lilinghai** [pingcap/tiflash#4899]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

when setting the 2 storage.main.capacity with the capacity 10GB limit, we can see capacity size and available size are as expected from the Grafana, but the tiflash store size is about 90GB which exceeds the limits largely.
![image](https://user-images.githubusercontent.com/7677963/168547131-dd31453d-610b-4e72-bb3c-d2a56a219de6.png)

```
du -h -d 1 /data1/llhtest53/tiflash-9900
4.0K	/data1/llhtest53/tiflash-9900/user_files
38G	/data1/llhtest53/tiflash-9900/flash
47G	/data1/llhtest53/tiflash-9900/data
4.0K	/data1/llhtest53/tiflash-9900/tmp
4.0K	/data1/llhtest53/tiflash-9900/flags
2.4M	/data1/llhtest53/tiflash-9900/page
4.0K	/data1/llhtest53/tiflash-9900/format_schemas
228K	/data1/llhtest53/tiflash-9900/metadata
84G	/data1/llhtest53/tiflash-9900
```
```
50G	/data2/llhtest53/tiflash-9900/data
664K	/data2/llhtest53/tiflash-9900/page
50G	/data2/llhtest53/tiflash-9900
```
### 4. What is your TiFlash version? (Required)
master

**Comment by JaySon-Huang** [comment]
@lilinghai  Do you deploy the 172.16.6.50 node with a 20GB capacity before inserting data? Or after there are already some data on 172.16.6.50 without setting the capacity, then change the capacity to be 20GB?

**Comment by lilinghai** [comment]
deploy the cluster with capacity 20GB, then br restore

**Comment by JaySon-Huang** [comment]
Should be caused by https://github.com/pingcap/tiflash/issues/4906. Please check whether it is fixed or not in the latest version.

**Comment by lilinghai** [comment]
> Should be caused by #4906. Please check whether it is fixed or not in the latest version.

already fixed
