### ISSUE TITLE
Count result may be wrong after a lot of insert and delete

### ISSUE THREAD

**Issue by lidezhu** [pingcap/tiflash#4956]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
Repeated do a lot of insert rows and delete alls.
Keep select count after after every operation.

### 2. What did you expect to see? (Required)
Count result is right.

### 3. What did you see instead (Required)
Count result is wrong.

**Comment by lilinghai** [comment]
> /cc @lilinghai We need to add a test case for this kind of workload

ok. have discussed it with dezhu and I will add a test case.
