### ISSUE TITLE
Remove deprecated apply snapshot method

### ISSUE THREAD

**Issue by JaySon-Huang** [pingcap/tiflash#4998]
## Enhancement

Before v5.1, we apply snapshot by decoding SSTFiles into blocks and flush to the storage layer. Since 5.1, by default we decode SSTFiles into DTFiles and ingest to the storage layer, which consume less memory. https://github.com/pingcap/tiflash/issues/1347

We can remove related code of `SnapshotApplyMethod::Block` now.

https://github.com/pingcap/tiflash/blob/0f56b15a770c60949241bb37fa63f9136d6706f1/etc/config-template.toml#L133-L136

**Comment by hongyunyan** [comment]
您好，邮件已收到！万分感谢！洪韫妍
