### ISSUE TITLE
Some window function unit test need to be modified to close to reality.

### ISSUE THREAD

**Issue by LittleFall** [pingcap/tiflash#5020]
## Enhancement

for example, https://github.com/pingcap/tiflash/blob/master/dbms/src/WindowFunctions/tests/gtest_window_functions.cpp#L221-L230 test four sortitems, but there will only 2 sortitems in this sql.

**Comment by ywqzzy** [comment]
I will try to rewrite the test with mock dagRequest to simplify the json format of sort and window.

**Comment by SeaRise** [comment]
Looks like it's been resolved
