### ISSUE TITLE
error data input for date(CAST(value AS DATETIME)) causing high TiFlash sys CPU

### ISSUE THREAD

**Issue by dbsid** [pingcap/tiflash#5097]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
run a query include date(CAST(rv_EndDateTime.value AS DATETIME)), and make wrong input for the cast function. TiFlash need to do exception handle and capture the unwind(stack) information, which explain the high sys cpu.

with date(CAST(rv_EndDateTime.value AS DATETIME)), the query takes over 10 minutes, and causing TiFlash high sys CPU.
without date(CAST(rv_EndDateTime.value AS DATETIME)), the query take around 300 ms.

```
SELECT
  id,
  module_id,
  rel_namespace,
  owned_by,
  created_by,
  updated_by,
  deleted_by,
  created_at,
  updated_at,
  deleted_at
FROM
  (
    SELECT
      crd.id,
      crd.module_id,
      crd.rel_namespace,
      crd.owned_by,
      crd.created_by,
      crd.updated_by,
      crd.deleted_by,
      crd.created_at,
      crd.updated_at,
      crd.deleted_at,
      row_number() over (PARTITION by id) AS pp_rn
    FROM
      compose_record AS crd
      LEFT JOIN compose_record_value AS rv_ActivityDate ON (
        rv_ActivityDate.record_id = crd.id
        AND rv_ActivityDate.name = 'ActivityDate'
        AND rv_ActivityDate.deleted_at IS NULL
      )
      LEFT JOIN compose_record_value AS rv_EndDateTime ON (
        rv_EndDateTime.record_id = crd.id
        AND rv_EndDateTime.name = 'EndDateTime'
        AND rv_EndDateTime.deleted_at IS NULL
      )
      LEFT JOIN compose_record_value AS rv_Type ON (
        rv_Type.record_id = crd.id
        AND rv_Type.name = 'Type'
        AND rv_Type.deleted_at IS NULL
      )
    WHERE
      crd.module_id = 287514257044686682
      AND crd.rel_namespace = 287514254259603290
      AND crd.deleted_at IS NULL
      AND (
        (
          date(CAST(rv_ActivityDate.value AS DATETIME)) <= '2022-07-10T16:00:00.000Z'
          AND '2022-05-29T16:00:00.000Z' <= date(CAST(rv_EndDateTime.value AS DATETIME))
        )
        AND (rv_Type.value IS NULL)
      )
    ORDER BY
      id ASC
  ) AS base
WHERE
  pp_rn = 1
LIMIT
  501;
```
### 2. What did you expect to see? (Required)
no high cpu

### 3. What did you see instead (Required)
high TiFlash sys CPU

![image](https://user-images.githubusercontent.com/2316425/172900300-8c0c3302-5a58-4b9c-b939-e5d393dfa1ee.png)

![origin_img_v2_28c59784-5f72-4a54-b55b-49761f35a89g](https://user-images.githubusercontent.com/2316425/172899450-d2bab28e-bad1-41c4-9e70-24d1c18d68bb.jpg)

![origin_img_v2_0d0daa81-3a5f-4ef5-8a27-e72ca8533a3g](https://user-images.githubusercontent.com/2316425/172899422-b9cde882-8ec9-4968-ba46-ee5327cf8df2.jpg)

![origin_img_v2_5afbd5d3-4ea4-45de-87fc-ecf296c8c96g](https://user-images.githubusercontent.com/2316425/172899619-cd303cf4-2835-457b-9f4e-f1bc5920b5f6.jpg)

### 4. What is your TiFlash version? (Required)
v6.1

**Comment by zanmato1984** [comment]
We should avoid using exception to pass error during function evaluation. We'd rather use return value to do that.

**Comment by windtalker** [comment]
> 

But here we don't print the stacktrace, it is the stack unwind that causes the hight sys cpu usage.

**Comment by windtalker** [comment]
> @zanmato1984 before achieving this, how about not print stacktrace for normal exceptions (only let BaseDaemon print stacetrace)? Such information is almost useless for debuging if we print enough logs at the throw points.

But here we don't print the stacktrace, it is the stack unwind that causes the hight sys cpu usage.

**Comment by fuzhe1989** [comment]
@windtalker Yes that's what I meant, not print here also means not to unwind.

**Comment by fuzhe1989** [comment]
@windtalker FYI, stacktrace unwind is disabled by default in my previous team (only enabled for fatal errors).
