### ISSUE TITLE
build tiflash error on macos related linking error about libtiflash_proxy

### ISSUE THREAD

**Issue by skyitachi** [pingcap/tiflash#5234]
## General Question

Recently I compiled tiflash failed on macos

![image](https://user-images.githubusercontent.com/3816806/175778716-8198adce-783a-432c-a701-386c81c81a12.png)

I have compiled serval times but endup with same problem, anyone can help?

**Comment by solotzg** [comment]
Did you use llvm environment rather than `CommandLineTools` ?

**Comment by SchrodingerZhu** [comment]
@solotzg this bug has been repeated reported several times. better figure out what is happening.

----

@skyitachi for a temporal fix, try `-DLINKER_NAME=gold` or just some linker other than `lld`.

**Comment by skyitachi** [comment]
on macos I use ld instead, whole cmake command `cmake -DLINKER_NAME=ld -GNinja ..`.
![image](https://user-images.githubusercontent.com/3816806/176065966-7324cbd1-92bd-4cd2-8121-a449ab9001ff.png)

it's wierd, maybe due to -std=gnu++17 ? but I don't change any CMakeLists.txt

**Comment by SchrodingerZhu** [comment]
I remember I have also encountered this once. It should be the case where system re2 headers intertwined with internal ones.

**Comment by solotzg** [comment]
> it's wierd, maybe due to -std=gnu++17 ? but I don't change any CMakeLists.txt

You can try to add cmake option `-DUSE_INTERNAL_RE2_LIBRARY=OFF`.

**Comment by skyitachi** [comment]
@SchrodingerZhu thanks for reminding, grpc, protobuf and boost also have this problem, I compiled successfully and start the journey about learning tiflash.:)

**Comment by skyitachi** [comment]
> 



> > it's wierd, maybe due to -std=gnu++17 ? but I don't change any CMakeLists.txt
> 
> You can try to add cmake option `-DUSE_INTERNAL_RE2_LIBRARY=OFF`.

thanks for your advice, I am not sure system installed library whether compatible with tiflash used internally, so I rm system installed lib and solve this problem.
