### ISSUE TITLE
Big region snapshot adaption and applying snapshot improvement

### ISSUE THREAD

**Issue by flowbehappy** [pingcap/tiflash#5237]
## Enhancement
Applying a snapshot requires writing a delete range and a DTFile to the Delta layer of 1 or more segments. Because the snapshot is relatively large, it will 

- Very likely trigger a delta merge, which causes write amplification.
- A big snapshot will directly cause write stall.

Note that, most of the time, the snapshot is not overlapped with the data in the relative segments. I think we can find a way to avoid writing snapshots to the Delta layer, as LSM-Tree does.

**Comment by breezewish** [comment]
Related TiKV change: https://github.com/tikv/tikv/issues/11515
