### ISSUE TITLE
Need allow empty schema diff when schema version increased.

### ISSUE THREAD

**Issue by jiaqizho** [pingcap/tiflash#5244]
## Enhancement
Before, `update schema version` and `set schema diff` in the same transaction. So after `schema version` grow up, we can get the `schema diff` at same time. 

**For now, We don't allow When `schema version` grow up, `schema diff` can not be read.**

But now, `update schema version` and `set schema diff` not in the same transaction. 

- TIDB can only make sure the `schema diff` from `lastest schema version - 1` is valuable.
   - If the `schema diff` from `lastest schema version - 1` is empty, Then it means may failed in TIDB, in TiFlash, we can skip it.
   - If the `schema diff` from `lastest schema version - 1` is empty, Then Tiflash should direct apply the `schema diff`.
- TIDB can't make sure the `schema diff` with ` lastest schema version` is not empty.

**So we need to allow empty schema diff when schema version increased. **

**Comment by JaySon-Huang** [comment]
related to the feature `concurrent DDL` https://github.com/pingcap/tidb/issues/32031
