### ISSUE TITLE
TiFlash  doesn't support $ in Integration Tests

### ISSUE THREAD

**Issue by lizhenhuan** [pingcap/tiflash#5275]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
cd tests
./run-test.sh fullstack-test/expr/upper.test
This test will success.
vi fullstack-test/expr/upper.test
1.add "insert into test.t values('pi$ng');" after origin insert sql
2.add "PI$NG" in excepted result at last
<img width="1071" alt="image" src="https://user-images.githubusercontent.com/3417765/176918945-44b964cd-09b8-4575-b378-3ead516a7d71.png">

run test again, this test is failed
<img width="865" alt="image" src="https://user-images.githubusercontent.com/3417765/176919188-f76ba9ba-52f4-42ae-b793-3adcaaf26d59.png">

This may because the integration tests framework doesn't support $ .
It may delete $ and the letter followed by $

### 2. What did you expect to see? (Required)
after add $ in upper.test ,this test case still success
### 3. What did you see instead (Required)
after add $ in upper.test ,this test case will fail
### 4. What is your TiFlash version? (Required)
TiFlash master branch

**Comment by Willendless** [comment]
Unfortunately, this seems to also be a security problem. The cause of this phenomena is that the integration test script constructs a mysql client command line to execute each mysql commands in test file, e.g. `os.popen("mysql -u root -P 4000 -h 127.0.0.1 -e "insert into test.t values ('$$')"")`. Then a sh subprocess will execute mysql client with arguments, but before that, sh subprocess will first expand '$$' to be current process's id... Then finally, the read command executed by tidb turns to be `insert into test.t values (current_process_id)`...
