### ISSUE TITLE
support `CastTimeAsDuration` in TiFlash

### ISSUE THREAD

**Issue by windtalker** [pingcap/tiflash#5306]
## Feature Request

**Is your feature request related to a problem? Please describe:**

**Describe the feature you'd like:**

Support `CastTimeAsDuration` in TiFlash
TiDB's implementation:
https://github.com/pingcap/tidb/blob/562bb9f9e2c194c3f398300d5e5e920965da9f47/expression/builtin_cast.go#L1454
**Describe alternatives you've considered:**

**Teachability, Documentation, Adoption, Migration Strategy:**

**Comment by AntiTopQuark** [comment]
Hi, has this job been done by someone?

I want to do this job. But I don't have much experience and I'm a little busy. I may do it for a long time. Is there a Deadline in this job?

**Comment by Willendless** [comment]
> Hi, has this job been done by someone?
> 
> I want to do this job. But I don't have much experience and I'm a little busy. I may do it for a long time. Is there a Deadline in this job?

Hi, feel free to give it a try. There is no hard deadline for this task. I can assign this task to you :)

**Comment by AntiTopQuark** [comment]
Thank you, I will try to do my best to do it well.
