### ISSUE TITLE
Remove the data of PageStorage V2 after all data has been migrated to V3

### ISSUE THREAD

**Issue by flowbehappy** [pingcap/tiflash#5336]
## Enhancement
1. Upgrade to V3
2. Run `alter table xxx compact tiflash replica`, all table's data has been migrated to V3
3. Restart TiFlash

There are some data files left on disk. They should be useless and removed after the 3rd step (Restart TiFlash).
<img width="1030" alt="image" src="https://user-images.githubusercontent.com/2639319/178195030-8b1906b9-c29d-4fd6-8e05-fc92ea90b28e.png">

<img width="658" alt="image" src="https://user-images.githubusercontent.com/2639319/178194785-e5115ec2-1840-4334-b9a1-87a49c9f3028.png">
<img width="649" alt="image" src="https://user-images.githubusercontent.com/2639319/178194810-e8812596-c8f5-4fdc-b734-71225ac745ba.png">

**Comment by lidezhu** [comment]
> Maybe we can do the checking in `doV2Gc` and `restore`, to remove v2 data completely.

If we remove v2 data in `doV2Gc`, we also need to reset a lot of member variables of `StoragePool` like `log_page_reader` which should be a dangerous operation. So I suggest just do it when `restore`.
