### ISSUE TITLE
The performance result of pageworkload is not stable

### ISSUE THREAD

**Issue by JaySon-Huang** [pingcap/tiflash#5456]
## Enhancement

The performance result of pageworkload is not stable, we need to make it more stable and convincing.
command: `/tiflash/tiflash pageworkload -T1000`

**Comment by River2000i** [comment]
same commit: 5e6f620f5cf62ecb03f52c21ea3ad185278a20cb
![c105c2f0-3eba-4a0e-991b-f4bad53ed037](https://user-images.githubusercontent.com/96465211/194687210-3de27e2e-6383-4139-8025-5650c623ac43.jpeg)

**Comment by River2000i** [comment]
read_speed drop more than 10%
![image](https://user-images.githubusercontent.com/96465211/198185165-d4e316c3-edd2-434d-8faa-328d1964b742.png)

**Comment by River2000i** [comment]
write_speed drop more than 10%
![image](https://user-images.githubusercontent.com/96465211/198186139-01e247bb-c6fe-4963-b799-ac5d31aca713.png)

**Comment by River2000i** [comment]
731482ec0bf3240622af854db3170b81eff657bb 22.698

**Comment by River2000i** [comment]
0791cdfb3945a71f552d606a130affef4edd4e01 22.6973
3aa8f85323f7be6dbbe3baae3b3a9b37d407d729 25.6606
40ad20c9439b18221297ed2b87d9d7421d17b174 23.1438

**Comment by River2000i** [comment]
![image](https://user-images.githubusercontent.com/96465211/200986952-ffc769f2-e0b7-40e5-b843-86183846f352.png)
![image](https://user-images.githubusercontent.com/96465211/200987586-6ca2090f-511d-4c07-9307-016890943541.png)
9d7d060e67637e5c1f8854f6ba5e7b89d8570eae 24.4489
35bbaf0695817034d9169c8c997846f73f5c2e69 20.6997
dc194135de55b3b88c348215d24d7f173e9f055b 21.1641

**Comment by JaySon-Huang** [comment]
The performance jitter around Oct 27th is caused by the testing environment issue.

The reading performance degradation around Nov 8th is caused by https://github.com/pingcap/tiflash/pull/6263. We use the `read` without callback (which is actually used in the product).

**Comment by JaySon-Huang** [comment]
I think the root reason caused by #6263 is we need to allocate more memory as a reading buffer after that PR. However, we can NOT see the big difference from the flame graph between different ways of reading data with this [commit](2e7167555a1b20adecf0da755097044fdada2fea).

It is worth a deeper investigation on whether we should use the `read with callback` way for better reading performance. But as we only use `read without callback` way now, it won't cause performance degradation on the product env, we can ignore it now.

**Comment by JaySon-Huang** [comment]
Please update the performance baseline after https://github.com/pingcap/tiflash/pull/6178 merged

**Comment by River2000i** [comment]
update baseline done
read_speed=20.658, write_speed=0.5081
7203151a59ac7c44c673fc5f689fef312c660731 write_speed=0.4547, read_speed=17.0903
a2acd1fad2536181ecd7aaa48d84bd5b26c9005f write_speed=0.4395, read_speed=16.7049
