### ISSUE TITLE
TPCDS Q72 - Exchange receiver meet error: Region 1679 is unavailable:

### ISSUE THREAD

**Issue by Yui-Song** [pingcap/tiflash#5468]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

1. deploy a cluster with 1 TiDB + 3TiKV + 1 TiFlash
2. Import TPCDS 50g data
3. run Query 72
```
select  i_item_desc
      ,w_warehouse_name
      ,d1.d_week_seq
      ,sum(case when p_promo_sk is null then 1 else 0 end) no_promo
      ,sum(case when p_promo_sk is not null then 1 else 0 end) promo
      ,count(*) total_cnt
from catalog_sales
join inventory on (cs_item_sk = inv_item_sk)
join warehouse on (w_warehouse_sk=inv_warehouse_sk)
join item on (i_item_sk = cs_item_sk)
join customer_demographics on (cs_bill_cdemo_sk = cd_demo_sk)
join household_demographics on (cs_bill_hdemo_sk = hd_demo_sk)
join date_dim d1 on (cs_sold_date_sk = d1.d_date_sk)
join date_dim d2 on (inv_date_sk = d2.d_date_sk)
join date_dim d3 on (cs_ship_date_sk = d3.d_date_sk)
left outer join promotion on (cs_promo_sk=p_promo_sk)
left outer join catalog_returns on (cr_item_sk = cs_item_sk and cr_order_number = cs_order_number)
where d1.d_week_seq = d2.d_week_seq
  and inv_quantity_on_hand < cs_quantity
  and d3.d_date > d1.d_date + 5
  and hd_buy_potential = '1001-5000'
  and d1.d_year = 2001
  and cd_marital_status = 'M'
group by i_item_desc,w_warehouse_name,d1.d_week_seq
order by total_cnt desc, i_item_desc, w_warehouse_name, d_week_seq
limit 100;
```

### 2. What did you expect to see? (Required)
The query was executed successfully. 

### 3. What did you see instead (Required)
`ERROR 1105 (HY000): other error for mpp stream: Code: 0, e.displayText() = DB::Exception: Exchange receiver meet error : Code: 0, e.displayText() = DB::Exception: Exchange receiver meet error : Code: 0, e.displayText() = DB::TiFlashException: Region 1679 is unavailable: (while doing learner read for table, logical table_id: 75), e.what() = DB::TiFlashException,, e.what() = DB::Exception,, e.what() = DB::Exception,`
### 4. What is your TiFlash version? (Required)
 6.2.0-alpha-155-ge28911
commit e289119502cb4f2643eb1810dffb4434a611b0a9

**Comment by CalvinNeo** [comment]
same as https://github.com/pingcap/tiflash/issues/5458
