### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by szza** [pingcap/tiflash#5479]
## Bug Report

```bash
/data/work/tiflash/dbms/src/Common/TiFlashBuildInfo.cpp: In function 'std::string TiFlashBuildInfo::getReleaseVersion()':
/data/work/tiflash/dbms/src/Common/TiFlashBuildInfo.cpp:36:12: error: 'TIFLASH_RELEASE_VERSION' was not declared in this scope; did you mean 'TIFLASH_VERSION'?
   36 |     return TIFLASH_RELEASE_VERSION;
      |            ^~~~~~~~~~~~~~~~~~~~~~~
      |            TIFLASH_VERSION
/data/work/tiflash/dbms/src/Common/TiFlashBuildInfo.cpp: In function 'std::string TiFlashBuildInfo::getGitHash()':
/data/work/tiflash/dbms/src/Common/TiFlashBuildInfo.cpp:44:12: error: 'TIFLASH_GIT_HASH' was not declared in this scope
   44 |     return TIFLASH_GIT_HASH;
      |            ^~~~~~~~~~~~~~~~
/data/work/tiflash/dbms/src/Common/TiFlashBuildInfo.cpp: In function 'std::string TiFlashBuildInfo::getGitBranch()':
/data/work/tiflash/dbms/src/Common/TiFlashBuildInfo.cpp:48:12: error: 'TIFLASH_GIT_BRANCH' was not declared in this scope
   48 |     return TIFLASH_GIT_BRANCH;
      |            ^~~~~~~~~~~~~~~~~~
[ 77%] Building CXX object dbms/CMakeFiles/clickhouse_common_io.dir/src/Common/escapeForFileName.cpp.o
```

### tiflash-version
```bash
origin/release-6.2
```
### complie script

```
$ cmake .. -DCMAKE_BUILD_TYPE=DEBUG
$ make tiflash -j 32
```

**Comment by Lloyd-Pottiger** [comment]
seems strange, we have declared those variables [here](https://github.com/pingcap/tiflash/blob/release-6.2/dbms/src/Common/config_version.h.in). Have you revise the Makefile?

**Comment by szza** [comment]
> seems strange, we have declared those variables [here](https://github.com/pingcap/tiflash/blob/release-6.2/dbms/src/Common/config_version.h.in). Have you revise the Makefile?

Do not revise the Makefile. Do you have a docker environment to complie tiflash ?

**Comment by Lloyd-Pottiger** [comment]
> Do not revise the Makefile. Do you have a docker environment to complie tiflash ?

Do not have it until now……, feel free to open a new issue about it. 
And could you please try `ninja` rather than `make` or `make tiflash -j 6`? I think this may caused by the invalid concurrence?

**Comment by Lloyd-Pottiger** [comment]
btw, you can use the materials under https://github.com/pingcap/tiflash/tree/master/release-centos7-llvm to build your environment.

**Comment by ngaut** [comment]
I met the same issue. 
masOS Monterey

**Comment by zanmato1984** [comment]
Cannot reproduce on my MBP M1, macOS Monterey 12.4, a brand new build (building under an empty directory from cmake command).

Maybe you guys can try a brand new build, or rerun cmake command before you run make.
