### ISSUE TITLE
TiFlash crash when high frequency renaming tables

### ISSUE THREAD

**Issue by shuke987** [pingcap/tiflash#5501]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
1. Add a workload with high frequency rename tables
2. Run TiFlash
3. TiFlash will crash after running a period

Root Cause description:
1. When TiFlash syncs all schema with TiDB, it gets TiDB's schema version at first, then pulls all schemas and tables in each schema.
2. Their maybe schema changes between TiFlash getting schema version from TiDB and pulling table info
3. If their is a rename table ddl submitted at this moment, e.g.) rename t1->t2. TiFlash will find t2, but no t1 at all, in syncs.
4. Then TiFlash will crash after it doing incremental sync, due to can not find  original table t1.

### 2. What did you expect to see? (Required)
no crash

### 3. What did you see instead (Required)
crash

### 4. What is your TiFlash version? (Required)
v6.1

**Comment by JaySon-Huang** [comment]
/close 

1. There is no crash backtrace / logging in the issue to locate the bug
2. TiFlash find the table_info by table_id, which is not changed after `RENAME` ddl. So the step 3 and step 4 is not reasonable
3. There is no other issue or stack reporting error like this

I assume this is not a reproducible steps and will close it. Feel free to reopen it if similar issue happens
