### ISSUE TITLE
TiFlash crash when drop table and schema after a column type change.

### ISSUE THREAD

**Issue by shuke987** [pingcap/tiflash#5502]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
1. do a column type change DDL
2. subbmit a  txn to TiDB
3. then drop TiDB schema
4. TiFlash have chance to crash.

Root Cause analysis:
1. After get the txn data, tiflash will sync table
2. But it found the schema is dropped.
3. And the old schema can not decode the data
4. TiFlash crash

### 2. What did you expect to see? (Required)
no crash

### 3. What did you see instead (Required)
crash

### 4. What is your TiFlash version? (Required)
v6.1

**Comment by JaySon-Huang** [comment]
similar to https://github.com/pingcap/tiflash/issues/3777, https://github.com/pingcap/tiflash/issues/1664

**Comment by flowbehappy** [comment]
Close this issue because of duplicate with https://github.com/pingcap/tiflash/issues/3777, https://github.com/pingcap/tiflash/issues/1664
