### ISSUE TITLE
'TiFlash server is terminating' happened after TiFlash restart

### ISSUE THREAD

**Issue by River2000i** [pingcap/tiflash#5504]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

1. Do some query in TiFlash => succeed
2. Restart TiFlash instance.
3. Do some query in TiFlash => Error 1105: other error for mpp stream: Code: 0, e.displayText() = DB::Exception: Exchange receiver meet error : Code: 0, e.displayText() = DB::Exception: Exchange receiver meet error : Code: 0, e.displayText() = DB::TiFlashException: TiFlash server is terminating, e.what() = DB::TiFlashException,, e.what() = DB::Exception,, e.what() = DB::Exception

### 2. What did you expect to see? (Required)
In step 3, query succeed.

### 3. What did you see instead (Required)
In step 3, query failed.

### 4. What is your TiFlash version? (Required)
TiFlash build info: TiFlash
Release Version: v6.2.0
Edition:         Community
Git Commit Hash: aa50505ab6150d4cde9bb97f08d6241ddffad91f
Git Branch:      heads/refs/tags/v6.2.0
UTC Build Time:  2022-07-26 10:05:03
Enable Features: jemalloc avx avx512 unwind thinlto
Profile:         RELWITHDEBINFO

**Comment by Lloyd-Pottiger** [comment]
duplicate with #5458 ?
