### ISSUE TITLE
Cmake fail on mac m1

### ISSUE THREAD

**Issue by Tangruilin** [pingcap/tiflash#5549]
Hello!

I try to cmake tiflash and get the error:

<img width="713" alt="image" src="https://user-images.githubusercontent.com/23651891/183261498-860c96d9-cbe0-4992-af1b-40ac63cc4131.png">

It seems that cmake cannot  parse the regex, but my cmake version is 3.23.2:
<img width="1110" alt="image" src="https://user-images.githubusercontent.com/23651891/183261549-0acea3d6-734a-4b90-acc5-6470bf2d28ba.png">

And I found that the wrong is in `contrib/tiflash-proxy-cmake/CMakeLists.txt:4`, If I exegesis it, I can do cmake successfully.

**Comment by xzhangxian1008** [comment]
Your path include "C++" and '+' is a special character in reg, try to remove all special character in your path and try it again.

**Comment by breezewish** [comment]
Please leave replies if you are still encountering this issue. Thanks!
