### ISSUE TITLE
Data is not consistency when conver tiflash mode to normal

### ISSUE THREAD

**Issue by lilinghai** [pingcap/tiflash#5554]
## Bug Report
convert tiflash mode from fast to normal and check consistency using diff tikv with tiflash, the result is :
result inconsistent tso 435126922503258118, tikv: [2100000], tiflash [4016148]

Please answer these questions before submitting your issue. Thanks!

### 4. What is your TiFlash version? (Required)
6.2

**Comment by JaySon-Huang** [comment]
The root cause is that TiFlash can not fetch the table info after a table has been dropped

similar to
https://github.com/pingcap/tiflash/issues/1664
https://github.com/pingcap/tiflash/issues/3777

**Comment by JaySon-Huang** [comment]
close as we only support fast scan variable instead of table mode since 6.3

ref https://github.com/pingcap/tiflash/pull/5589
