### ISSUE TITLE
How to Constructure AN IBlockInputStream from A table

### ISSUE THREAD

**Issue by atidat** [pingcap/tiflash#5588]
## General Question
I want to Constructure  AN IBlockInputStream by A table. Is there a good solution?

**Comment by ywqzzy** [comment]
Ref to dbms/src/Storages/IStorage.h:BlockInputStreams:read() maybe what you need.

**Comment by atidat** [comment]
> dbms/src/Storages/IStorage.h

seems not support
```c++
virtual BlockInputStreams read(const Names & /*column_names*/,
                                   const SelectQueryInfo & /*query_info*/,
                                   const Context & /*context*/,
                                   QueryProcessingStage::Enum & /*processed_stage*/,
                                   size_t /*max_block_size*/,
                                   unsigned /*num_streams*/)
    {
        throw Exception("Method read is not supported by storage " + getName(), ErrorCodes::NOT_IMPLEMENTED);
    }
````

**Comment by ywqzzy** [comment]
> > dbms/src/Storages/IStorage.h
> 
> seems not support
> 
> ```c++
> virtual BlockInputStreams read(const Names & /*column_names*/,
>                                    const SelectQueryInfo & /*query_info*/,
>                                    const Context & /*context*/,
>                                    QueryProcessingStage::Enum & /*processed_stage*/,
>                                    size_t /*max_block_size*/,
>                                    unsigned /*num_streams*/)
>     {
>         throw Exception("Method read is not supported by storage " + getName(), ErrorCodes::NOT_IMPLEMENTED);
>     }
> ```

This is an interface, you can ref to classes that implement it.

**Comment by SeaRise** [comment]
I closed this issue for now. Feel free to continue discussion.
