### ISSUE TITLE
Log `Start GC` including `<unknown>` let customers confused,hopefully tuning it.

### ISSUE THREAD

**Issue by jansu-dev** [pingcap/tiflash#5619]
## Enhancement
Orginal question:https://asktug.com/t/topic/873121

this is really Ugly about `<unknown>`.
![image](https://user-images.githubusercontent.com/76909042/184569341-1c89d7c1-b757-4974-aa9f-193bfcb7b296.png)

**Comment by Lloyd-Pottiger** [comment]
We have solved this in version 6.x.

<img width="843" alt="image" src="https://user-images.githubusercontent.com/60744015/184812855-64d51fd2-d018-44e9-b551-21afc9f69089.png">

maybe this issue can be closed?

**Comment by jansu-dev** [comment]
thanks for you reply really.
yeah,please close it.
