### ISSUE TITLE
TiFlash COMPILE WORK is soooooo unfriendly

### ISSUE THREAD

**Issue by atidat** [pingcap/tiflash#5626]

**Comment by Lloyd-Pottiger** [comment]
Sorry about that. Could please describe the problem you faced in detail? Also, a pr to enhance this is warmly welcome!

**Comment by atidat** [comment]
> Sorry about that. Could please describe the problem you faced in detail? Also, a pr to enhance this is warmly welcome!

1. dependency download: without vpn, the dependencies in contrib downloaded would be difficult
2. compile: compile progress is not clear and slow. For example, progress is blocked on "Built target kv_client" for hundreds of minutes. Is it in downloading rust dependencies or compiling?

Suggestion
1. could offer some available repositories like gitee for mainland developer?
2. could depend on binary file when compiling tiflash?

**Comment by Lloyd-Pottiger** [comment]
> 1. could offer some available repositories like gitee for mainland developer?

Most of the dependencies have no repo in gitee, it can not help decrease the download time. However, we only need to download once, I think it is acceptable. 

> 2. could depend on binary file when compiling tiflash?

"Built target kv_client" which may means link tiflash-proxy which can only run in single thread, so it is kind of slow. Depending on binary file may cause incompatible, so we do not do in this way. And tiflash support incremental compilation, so the later compile can be faster. Compile time is an issue for most c++ repo, warnly welcome to make a pr if you have better solution.

**Comment by Lloyd-Pottiger** [comment]
I closed this issue for now. Feel free to continue discussion.
