### ISSUE TITLE
Encryption: Support SM4 Cryptographic Hash Algorithm

### ISSUE THREAD

**Issue by lidezhu** [pingcap/tiflash#5714]
## Enhancement

Related tidb issue: https://github.com/pingcap/tidb/issues/36192
Related tikv issue: https://github.com/tikv/tikv/issues/13041

**Comment by dveeden** [comment]
What is needed in TiFlash for this? Is this inter-component TLS? or also something like supporting a `SM3()` function in SQL and pushdown to TiFlash?

**Comment by lidezhu** [comment]
> What is needed in TiFlash for this? Is this inter-component TLS? or also something like supporting a `SM3()` function in SQL and pushdown to TiFlash?

This is to support encrypting tiflash data on disk with SM4 algorithm.(Something similar to AES encryption algorithm)
