### ISSUE TITLE
Build boost fail when using clang15 and libc++15

### ISSUE THREAD

**Issue by fuzhe1989** [pingcap/tiflash#5717]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

Build tiflash using clang15 and libc++15

### 2. What did you expect to see? (Required)

Build pass

### 3. What did you see instead (Required)

tiflash/contrib/boost/boost/container_hash/hash.hpp:131:33: error: no template named 'unary_function' in namespace 'std'; did you mean '__unary_function'?
        struct hash_base : std::unary_function<T, std::size_t> {};
                           ~~~~~^~~~~~~~~~~~~~
                                __unary_function
/usr/lib/llvm-15/bin/../include/c++/v1/__functional/unary_function.h:46:1: note: '__unary_function' declared here
using __unary_function = __unary_function_keep_layout_base<_Arg, _Result>;
^

### 4. What is your TiFlash version? (Required)

master 61e436be45a9df7daa3869fd4794cd155ff9896b

`std::unary_function` is deprecated in C++11 and removed in C++17. From [Boost Macro Reference](https://www.boost.org/doc/libs/1_76_0/libs/config/doc/html/boost_config/boost_macro_reference.html#boost_config.boost_macro_reference.macros_that_describe_features_that_have_been_removed_from_the_standard_) 
 set `BOOST_NO_CXX98_FUNCTION_BASE` could solve this issue.

**Comment by fuzhe1989** [comment]
Other issues:
- have to suppress "unused-but-set-variable" and "deprecated-builtins"

**Comment by cakebytheoceanLuo** [comment]
I confirm this issue of boost falling to be built: https://github.com/boostorg/container_hash/issues/22

**Comment by JaySon-Huang** [comment]
Change the "bug" to be "enhancement" since we do not officially support clang-15 yet
