### ISSUE TITLE
Simple queries use 'mpp' result in integration testing failed 

### ISSUE THREAD

**Issue by JinheLin** [pingcap/tiflash#5747]
After https://github.com/pingcap/tidb/pull/37422 was merged, most of the simple queries will use 'mpp task' instead of 'cop task'. 

Error messages of 'mpp' are slightly different from 'cop' and result in some tests failed.

![image](https://user-images.githubusercontent.com/6143402/187644309-bacf4b9d-a9bb-43f9-a65b-8685fc33c52c.png)

**Comment by windtalker** [comment]
closed by #5752
