### ISSUE TITLE
introduce magic_enum into tiflash

### ISSUE THREAD

**Issue by ywqzzy** [pingcap/tiflash#5758]
## Enhancement
Magic_enum provide static reflection for enums (to string, from string, iteration) for modern C++, work with any enum type without any macro or boilerplate code.
https://github.com/Neargye/magic_enum

**Comment by Ziy1-Tan** [comment]
Just curious, is this a issue about project building? I am interested in this.

**Comment by ywqzzy** [comment]
> Just curious, is this a issue about project building? I am interested in this.

Part of it is related to project building. And we want to replace some of enum toString functions using magic_enum.

**Comment by Ziy1-Tan** [comment]
Looks like a big project?

**Comment by ywqzzy** [comment]
> intro

You are right, just introduce magic_enum, then replace one original enum is ok.
Then we can replace the others later.

**Comment by ywqzzy** [comment]
> Looks like a big project? many places may be modify. Or this issues just intro `magic_enum` to tiflash, But the modification of the original enum and the use of future development are not included in this task?

You are right, just introduce magic_enum, then replace one original enum is ok.
Then we can replace the others later.

**Comment by Ziy1-Tan** [comment]
> > Looks like a big project? many places may be modify. Or this issues just intro `magic_enum` to tiflash, But the modification of the original enum and the use of future development are not included in this task?
> 
> You are right, just introduce magic_enum, then replace one original enum is ok. Then we can replace the others later.

Nice one. I want to change it, I have some experience on MariaDB OLAP Task. Could you give me some guide?very grateful!

**Comment by ywqzzy** [comment]
> > > Looks like a big project? many places may be modify. Or this issues just intro `magic_enum` to tiflash, But the modification of the original enum and the use of future development are not included in this task?
> > 
> > 
> > You are right, just introduce magic_enum, then replace one original enum is ok. Then we can replace the others later.
> 
> Nice one. I want to change it, I have some experience on MariaDB OLAP Features. Could you give me some guide?very grateful!

Wow. You can copy the header of magic_enum into dbms/src/Common. And write some simple test for one of the enum we used in TiFlash. BTW, you can contact me on wechat or qq.

**Comment by ywqzzy** [comment]
> > > > Looks like a big project? many places may be modify. Or this issues just intro `magic_enum` to tiflash, But the modification of the original enum and the use of future development are not included in this task?
> > > 
> > > 
> > > You are right, just introduce magic_enum, then replace one original enum is ok. Then we can replace the others later.
> > 
> > 
> > Nice one. I want to change it, I have some experience on MariaDB OLAP Features. Could you give me some guide?very grateful!
> 
> Wow. You can copy the header of magic_enum into dbms/src/Common. And write some simple test for one of the enum we used in TiFlash. BTW, you can contact me on wechat or qq.

We always welcome your contribution

**Comment by JaySon-Huang** [comment]
> Wow. You can copy the header of magic_enum into dbms/src/Common. 

@ywqzzy I think `contrib` is a better place for third-party libraries.

@Ziy1-Tan I recommend two ways to introduce magic_enum to tiflash
* try to add magic_enum as a submodule in contrib, and add `add_subdirectory` in the `contrib/CMakeLists.txt`
  then we should be able to include the magic_enum header in tiflash
* copy the header of magic_enum into a directory `contrib/magic_enum/` and add it as an interface library
  you can refer to how we introduce cpptoml https://github.com/pingcap/tiflash/blob/067c450072d6628f3cc83e9745a60ede986ca807/contrib/CMakeLists.txt#L152-L155

**Comment by Ziy1-Tan** [comment]
> Neargye/magic_enum

Sound like a good idea. I will try it.

**Comment by JaySon-Huang** [comment]
Some `toString` funcs for these enum class can be simplified after introducing `magic_enum`

* MergeDeltaReason
https://github.com/pingcap/tiflash/blob/aae88b120da5fda1a2f578d8a4cbe33d6e82caff/dbms/src/Storages/DeltaMerge/DeltaMergeStore_InternalBg.cpp

* SegmentWriteType
https://github.com/pingcap/tiflash/blob/aae88b120da5fda1a2f578d8a4cbe33d6e82caff/dbms/src/Storages/DeltaMerge/tests/gtest_dm_segment.cpp#L1181-L1198

* RegionException::RegionReadStatus
https://github.com/pingcap/tiflash/blob/aae88b120da5fda1a2f578d8a4cbe33d6e82caff/dbms/src/Storages/Transaction/RegionException.h#L26-L47

**Comment by SeaRise** [comment]
It looks like most of the code has been replaced with magic enum, so close this issue.
