### ISSUE TITLE
TiFlash should use `DB::Logger` instead of `Poco::Logger`

### ISSUE THREAD

**Issue by windtalker** [pingcap/tiflash#5864]
## Enhancement

We provide `DB::Logger` as an enhancement replace of `Poco::Logger` in https://github.com/pingcap/tiflash/blob/a6bc771f2b3cb1d08c628b649ff9ca796e026932/dbms/src/Common/Logger.h#L28-L38

Some utils macro like `RUNTIME_ASSERT` require the logger to be `DB::LoggerPtr` type, so we should replace `Poco::Logger *` by `DB::LoggerPtr` in TiFlash.

**Comment by SeaRise** [comment]
It seems that this issue can be closed, because most of the logs have been replaced by DB::Logger
