### ISSUE TITLE
delta merge by delete range write stall duration is more than 4s when scale tiflash

### ISSUE THREAD

**Issue by lilinghai** [pingcap/tiflash#5893]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

![origin_img_v2_b6f666a2-bf7e-467b-aec2-2296f65c734g](https://user-images.githubusercontent.com/7677963/190307755-917a5cad-ad68-4002-9803-bdbbfa292e1d.jpg)

### 4. What is your TiFlash version? (Required)
master

**Comment by breezewish** [comment]
In latest master we no longer see such write stalls.
