### ISSUE TITLE
tiflash can't gc completely after set tiflash replica 0

### ISSUE THREAD

**Issue by lilinghai** [pingcap/tiflash#5975]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

![image](https://user-images.githubusercontent.com/7677963/191451119-ea51c0cf-37e5-43d6-8d18-29b217ddac5c.png)
![image](https://user-images.githubusercontent.com/7677963/191451308-f8d9c9b1-318f-4650-96ef-0e6747b96f0f.png)

### 4. What is your TiFlash version? (Required)
master

**Comment by breezewish** [comment]
Since we use a lot of logical split now, the estimated rows and size (which is based on pack statistics) is no longer accurate. The inaccurate rows and size misleads the GC and prevented DTFiles being recycled.

**Comment by JaySon-Huang** [comment]
An example is that a segment with range [27192,30593), while the DMFile in stable contains two packs. The first pack contains rows [16994, 23791) ∪ [33991, 35386) and the second pack contains rows [35386, 37381).

No data is valid under the segment, which is generated by logical split, but now we can not execute gc on segment like this. Now the gc routines use the min-max index for decision-making

https://github.com/pingcap/tiflash/blob/6a305d375bcf9827a35d0ff21c938f4ebd32d8ea/dbms/src/Storages/DeltaMerge/DeltaMergeStore_InternalBg.cpp#L391-L400
https://github.com/pingcap/tiflash/blob/6a305d375bcf9827a35d0ff21c938f4ebd32d8ea/dbms/src/Storages/DeltaMerge/StableValueSpace.cpp#L400-L434
