### ISSUE TITLE
Possible Duplication in Function `IfNull`

### ISSUE THREAD

**Issue by JigaoLuo** [pingcap/tiflash#6037]
## Enhancement

I find two implementation of `IfNull` function:
- one is a reusage in tiflash: https://github.com/pingcap/tiflash/blob/973de13fef5e787be1f2867f2a4fbb4af20ee77d/dbms/src/Flash/Coprocessor/DAGExpressionAnalyzerHelper.cpp#L435-L458
- one is from clickhouse: https://github.com/pingcap/tiflash/blob/master/dbms/src/Functions/FunctionsNull.h + https://github.com/pingcap/tiflash/blob/master/dbms/src/Functions/FunctionsNull.cpp 

I did some experiments to see that the implementation from clickhouse is actually not used at all. But I still not sure if the IfNull from clickhouse can be removed? So we can discuss about it.

**Comment by windtalker** [comment]
Yes, I think it can be removed.
