### ISSUE TITLE
Suppress CMake warnings in 5.4

### ISSUE THREAD

**Issue by CalvinNeo** [pingcap/tiflash#6059]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

Disable this check since bug raised in libtitan

![img_v2_d6d83942-4409-450a-b6f1-06caad55d03g](https://user-images.githubusercontent.com/5670241/192987700-82810cf0-f0bf-4841-bcf7-d91377403416.jpg)

**Comment by JaySon-Huang** [comment]
Done in https://github.com/pingcap/tiflash/pull/6060
