### ISSUE TITLE
Metric 'Cop task memory usage(MemoryTracker)' is larger than actual memory usage when storage read thread enabled

### ISSUE THREAD

**Issue by JinheLin** [pingcap/tiflash#6130]
![a4e5d247-a5c9-4f9e-be9b-7466c8d90c15](https://user-images.githubusercontent.com/6143402/195568268-a5d8ab9b-3b0d-44b0-a9ef-47f1f711ba62.jpeg)

![7e378822-1cbc-4ae2-b554-505dd959d623](https://user-images.githubusercontent.com/6143402/195568287-ef001bc5-cb42-432a-ba2b-a16e6948f8bd.jpeg)

**Comment by flowbehappy** [comment]
Note that this issue affects a cluster with memory limit enabled. i.e.
```
profiles.default.max_memory_usage = 68719476736
profiles.default.max_memory_usage_for_all_queries = 68719476736
```
A simple query `select count(*) from xxx` could throw.

```
Memory limit (total) exceeded caused by 'out of memory quota for data computing' : would use 64.00 GiB for data computing (attempt to allocate chunk of 2097152 bytes), limit of memory for data computing: 64.00 GiB
```
