### ISSUE TITLE
The stress performance test result of dtworkload-uniform workload-read speed drop more than 5%

### ISSUE THREAD

**Issue by River2000i** [pingcap/tiflash#6215]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
`/tiflash/tiflash dtworkload --testing_type=daily_perf --verify_round=100 --log_file=/tmp/dt.log`

![image](https://user-images.githubusercontent.com/96465211/198941179-7bfc83aa-217d-40c7-aaa0-e6685d0fb494.png)

sub_workload = 'uniform'  read_speed 
731482ec0bf3240622af854db3170b81eff657bb 857835
3aa8f85323f7be6dbbe3baae3b3a9b37d407d729 983860
40ad20c9439b18221297ed2b87d9d7421d17b174 878235/897138

**Comment by River2000i** [comment]
![image](https://user-images.githubusercontent.com/96465211/202376039-b364eac4-7d6b-4591-9754-83619645105b.png)
workload = `uniform`
type =  `read_speed`
06fb24a61078d4e1472ee407733540d63f7dd718 867267
e77d01c1b410bd5c94d0b22abc02a8af84fe7dcf  954291
7c4b740e9891f8bc99ee176f3fd6bd43b0890788 938535

**Comment by River2000i** [comment]
![image](https://user-images.githubusercontent.com/96465211/202973249-f7655880-16f9-4040-b7bb-c8a4168a25a8.png)

the result not stable with same commit

**Comment by River2000i** [comment]
![image](https://user-images.githubusercontent.com/96465211/203688439-6ef555f0-0481-4527-b10b-ba26de31e84a.png)
read speed drop periodically😢

**Comment by flowbehappy** [comment]
Looks like this is a false alarm, can we close this issue? @River2000i

**Comment by River2000i** [comment]
> Looks like this is a false alarm, can we close this issue? @River2000i

Yes, the previous conclusion is caused by environmental problems, and we will re-govern the test environment in the near future. We can close the issue.
