### ISSUE TITLE
master code  build error

### ISSUE THREAD

**Issue by lizhenhuan** [pingcap/tiflash#6216]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

git clone master code
git pull origin master
cd tiflash
mkdir cmake-build-debug  # The directory name can be customized
cd cmake-build-debug

cmake .. -GNinja -DCMAKE_BUILD_TYPE=DEBUG
then error happen
<img width="1059" alt="image" src="https://user-images.githubusercontent.com/3417765/198946654-99f9482e-6a44-40c6-99bd-2ac8c331d572.png">

### 2. What did you expect to see? (Required)
source code build success

### 3. What did you see instead (Required)
errors happen
<img width="1059" alt="image" src="https://user-images.githubusercontent.com/3417765/198946756-16c84c64-680d-4cda-8dde-aa5feacfe2f7.png">

### 4. What is your TiFlash version? (Required)
master branch

**Comment by Lloyd-Pottiger** [comment]
@lizhenhuan could you please try #6217
