### ISSUE TITLE
TiFlash failed to generate flamegraph

### ISSUE THREAD

**Issue by CalvinNeo** [pingcap/tiflash#6228]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

After https://github.com/pingcap/tidb-engine-ext/pull/193, we have to move from fp back to dwarf to unwind on x86 platforms. However, after this, flamegraph just can not work.

**Comment by CalvinNeo** [comment]
We have already tried to recover:
1. no-omit-frame-pointer on rust side
2. rebuild std

However, only enable pprof-rs feature can make flamegraph work.

For any other cases, just stop at `backtrace::trace_unsynchronized ` and never forward.

<img width="1432" alt="image" src="https://user-images.githubusercontent.com/5670241/199285434-97ac2648-6c4f-450b-878e-5d61aba042e5.png">

**Comment by CalvinNeo** [comment]
<img width="554" alt="image" src="https://user-images.githubusercontent.com/5670241/199384583-89eeedf7-d8da-4bdf-af4f-06bea5a7cd6c.png">

**Comment by CalvinNeo** [comment]
https://github.com/calvinneo/tidb-engine-ext/tree/pprof-fail-demo

**Comment by CalvinNeo** [comment]
Change debug to 2, no help
```
[profile.test]
opt-level = 0
debug = 2
codegen-units = 16
lto = false
incremental = true
debug-assertions = true
overflow-checks = true
rpath = false
```

**Comment by mornyx** [comment]
Should be resolved by https://github.com/tikv/pprof-rs/pull/172.
