### ISSUE TITLE
6.4.0 fails to start on Phytium arm platform

### ISSUE THREAD

**Issue by jebter** [pingcap/tiflash#6254]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

Start tiflash 6.4.0 on specific arm platforms

### 2. What did you expect to see? (Required)
Started successfully like 6.3.0
![image](https://user-images.githubusercontent.com/4425235/200148857-1502fc09-d367-48a2-a502-c7512db63aa1.png)
### 3. What did you see instead (Required)
Compared with 6.3.0, there are some more link libraries：libgmssl.so    libgmssl.so.3.0 libgmssl.so.3 
![image](https://user-images.githubusercontent.com/4425235/200148860-d3f02825-8ae5-46c6-b1a4-f7f46ffbfa99.png)

### 4. What is your TiFlash version? (Required)
v6.4.0-pre

**Comment by solotzg** [comment]
Cause by https://github.com/pingcap/tiflash/pull/6200. This so called `Phytium` platform has not support armv8.2. QA need tiflash v6.4 can work on it.
