### ISSUE TITLE
Is RSFilter implemented yet? I see that it is in the blog introduction, but the code is empty.

### ISSUE THREAD

**Issue by duanfuxiang0** [pingcap/tiflash#6284]

**Comment by Lloyd-Pottiger** [comment]
We have support minmax index, you can check `dbms/src/Storages/DeltaMerge/Filter` and `dbms/src/Storages/DeltaMerge/File/DMFilePackFilter.h`. And We plan to introduce more types like set, bloomfilter......

**Comment by Lloyd-Pottiger** [comment]
mark it as closed. And if you have more question, for free to discuss.
