### ISSUE TITLE
TiFlash crash on releasing snapshot

### ISSUE THREAD

**Issue by JaySon-Huang** [pingcap/tiflash#6303]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

After `alter table xxx compact tiflash replica`, tiflash (v6.1.0) get crashes with the below stack traces

### 3. What did you see instead (Required)
```
[2022/11/13 18:42:10.426 +08:00] [ERROR] [BaseDaemon.cpp:377] [BaseDaemon:########################################] [thread_id=57]
[2022/11/13 18:42:10.427 +08:00] [ERROR] [BaseDaemon.cpp:378] ["BaseDaemon:(from thread 34) Received signal Segmentation fault(11)."] [thread_id=57]
[2022/11/13 18:42:10.427 +08:00] [ERROR] [BaseDaemon.cpp:408] ["BaseDaemon:Address: 0xb32ed"] [thread_id=57]
[2022/11/13 18:42:10.427 +08:00] [ERROR] [BaseDaemon.cpp:414] ["BaseDaemon:Access: read."] [thread_id=57]
[2022/11/13 18:42:10.427 +08:00] [ERROR] [BaseDaemon.cpp:423] ["BaseDaemon:Address not mapped to object."] [thread_id=57]
[2022/11/13 18:42:12.720 +08:00] [ERROR] [BaseDaemon.cpp:570] ["BaseDaemon:
       0x1ed2681    faultSignalHandler(int, siginfo_t*, void*) [tiflash+32319105]
                    libs/libdaemon/src/BaseDaemon.cpp:221
  0x7fc13a0875d0    <unknown symbol> [libpthread.so.0+62928]
       0x76fc3a6    void std::__1::__hash_table<std::__1::__hash_value_type<unsigned long, unsigned long>, std::__1::__unordered_map_hasher<unsigned long, std::__1::__hash_value_type<unsigned long, unsigned long>, std::__1::hash<unsigned long>, std::__1::equal_to<unsigned long>, true>, std::__1::__unordered_map_equal<unsigned long, std::__1::__hash_value_type<unsigned long, unsigned long>, std::__1::equal_to<unsigned long>, std::__1::hash<unsigned long>, true>, std::__1::allocator<std::__1::__hash_value_type<unsigned long, unsigned long> > >::__assign_multi<std::__1::__hash_const_iterator<std::__1::__hash_node<std::__1::__hash_value_type<unsigned long, unsigned long>, void*>*> >(std::__1::__hash_const_iterator<std::__1::__hash_node<std::__1::__hash_value_type<unsigned long, unsigned long>, void*>*>, std::__1::__hash_const_iterator<std::__1::__hash_node<std::__1::__hash_value_type<unsigned long, unsigned long>, void*>*>) [tiflash+124765094]
                    /usr/local/bin/../include/c++/v1/__hash_table:1769
       0x7a1b9ba    DB::PS::V2::PageEntriesForDelta::compactDeltaAndBase(std::__1::shared_ptr<DB::PS::V2::PageEntriesForDelta> const&, std::__1::shared_ptr<DB::PS::V2::PageEntriesForDelta> const&) [tiflash+128039354]
                    dbms/src/Storages/Page/V2/PageEntries.h:578
       0x7a1946b    DB::PS::V2::PageEntriesVersionSetWithDelta::compactOnDeltaRelease(std::__1::shared_ptr<DB::PS::V2::PageEntriesForDelta>) [tiflash+128029803]
                    dbms/src/Storages/Page/V2/VersionSet/PageEntriesVersionSetWithDelta.cpp:214
       0x7a1f4da    DB::PS::V2::PageEntriesVersionSetWithDelta::Snapshot::~Snapshot() [tiflash+128054490]
                    dbms/src/Storages/Page/V2/VersionSet/PageEntriesVersionSetWithDelta.h:143
       0x78aca6f    DB::DM::DeltaValueSpace::compact(DB::DM::DMContext&) [tiflash+126536303]
                    dbms/src/Storages/DeltaMerge/Delta/DeltaValueSpace.cpp:270
       0x77d3f1a    DB::DM::Segment::compactDelta(DB::DM::DMContext&) [tiflash+125648666]
                    dbms/src/Storages/DeltaMerge/Segment.cpp:1338
       0x7799d54    DB::DM::DeltaMergeStore::handleBackgroundTask(bool) [tiflash+125410644]
                    dbms/src/Storages/DeltaMerge/DeltaMergeStore.cpp:1607
       0x76d16e1    DB::BackgroundProcessingPool::threadFunction() [tiflash+124589793]
                    dbms/src/Storages/BackgroundProcessingPool.cpp:233
       0x76d2061    void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, DB::BackgroundProcessingPool::BackgroundProcessingPool(int)::$_2> >(void*) [tiflash+124592225]
                    /usr/local/bin/../include/c++/v1/thread:291
  0x7fc13a07fdd5    start_thread [libpthread.so.0+32213]"] [thread_id=57]

[2022/11/13 18:42:12.721 +08:00] [ERROR] [BaseDaemon.cpp:406] ["BaseDaemon:Address: NULL pointer."] [thread_id=57]
[2022/11/13 18:42:12.721 +08:00] [ERROR] [BaseDaemon.cpp:414] ["BaseDaemon:Access: read."] [thread_id=57]
[2022/11/13 18:42:12.721 +08:00] [ERROR] [BaseDaemon.cpp:426] ["BaseDaemon:Unknown si_code."] [thread_id=57]
[2022/11/13 18:42:12.721 +08:00] [ERROR] [BaseDaemon.cpp:369] ["BaseDaemon:(from thread 19) Terminate called after throwing an instance of std::length_error what(): vector Stack trace:
       0x1d272f3    StackTrace::StackTrace() [tiflash+30569203]
                    dbms/src/Common/StackTrace.cpp:23
       0x1ed22af    terminate_handler() [tiflash+32318127]
                    libs/libdaemon/src/BaseDaemon.cpp:634
  0x7fc13dee1a13    std::__terminate(void (*)()) [libc++abi.so.1+236051]
  0x7fc13dee19b8    std::terminate() [libc++abi.so.1+235960]
       0x1d10ebb    __clang_call_terminate [tiflash+30478011]
       0x7a1f5c7    DB::PS::V2::PageEntriesVersionSetWithDelta::Snapshot::~Snapshot() [tiflash+128054727]
                    dbms/src/Storages/Page/V2/VersionSet/PageEntriesVersionSetWithDelta.h:149
       0x78aca6f    DB::DM::DeltaValueSpace::compact(DB::DM::DMContext&) [tiflash+126536303]
                    dbms/src/Storages/DeltaMerge/Delta/DeltaValueSpace.cpp:270
       0x77d3f1a    DB::DM::Segment::compactDelta(DB::DM::DMContext&) [tiflash+125648666]
                    dbms/src/Storages/DeltaMerge/Segment.cp"] [thread_id=57]
[2022/11/13 18:42:12.721 +08:00] [ERROR] [BaseDaemon.cpp:377] [BaseDaemon:########################################] [thread_id=57]
[2022/11/13 18:42:12.721 +08:00] [ERROR] [BaseDaemon.cpp:378] ["BaseDaemon:(from thread 19) Received signal Aborted(6)."] [thread_id=57]
[2022/11/13 18:42:12.722 +08:00] [ERROR] [BaseDaemon.cpp:369] ["BaseDaemon:(from thread 27) Terminate called after throwing an instance of std::length_error what(): vector Stack trace:
       0x1d272f3    StackTrace::StackTrace() [tiflash+30569203]
                    dbms/src/Common/StackTrace.cpp:23
       0x1ed22af    terminate_handler() [tiflash+32318127]
                    libs/libdaemon/src/BaseDaemon.cpp:634
  0x7fc13dee1a13    std::__terminate(void (*)()) [libc++abi.so.1+236051]
  0x7fc13dee19b8    std::terminate() [libc++abi.so.1+235960]
       0x1d10ebb    __clang_call_terminate [tiflash+30478011]
       0x7a1f5c7    DB::PS::V2::PageEntriesVersionSetWithDelta::Snapshot::~Snapshot() [tiflash+128054727]
                    dbms/src/Storages/Page/V2/VersionSet/PageEntriesVersionSetWithDelta.h:149
       0x78aca6f    DB::DM::DeltaValueSpace::compact(DB::DM::DMContext&) [tiflash+126536303]
                    dbms/src/Storages/DeltaMerge/Delta/DeltaValueSpace.cpp:270
       0x77d3f1a    DB::DM::Segment::compactDelta(DB::DM::DMContext&) [tiflash+125648666]
                    dbms/src/Storages/DeltaMerge/Segment.cp"] [thread_id=57]
[2022/11/13 18:42:12.722 +08:00] [ERROR] [BaseDaemon.cpp:377] [BaseDaemon:########################################] [thread_id=57]
```
### 4. What is your TiFlash version? (Required)
v6.1.0

**Comment by lidezhu** [comment]
There are also some stack which is not related to releasing tiflash snapshot:
[2022/11/14 23:30:23.045 +08:00] [ERROR] [BaseDaemon.cpp:377] [BaseDaemon:########################################] [thread_id=56]
[2022/11/14 23:30:23.045 +08:00] [ERROR] [BaseDaemon.cpp:378] ["BaseDaemon:(from thread 57) Received signal Segmentation fault(11)."] [thread_id=56]
[2022/11/14 23:30:23.045 +08:00] [ERROR] [BaseDaemon.cpp:406] ["BaseDaemon:Address: NULL pointer."] [thread_id=56]
[2022/11/14 23:30:23.045 +08:00] [ERROR] [BaseDaemon.cpp:414] ["BaseDaemon:Access: read."] [thread_id=56]
[2022/11/14 23:30:23.045 +08:00] [ERROR] [BaseDaemon.cpp:426] ["BaseDaemon:Unknown si_code."] [thread_id=56]
[2022/11/14 23:30:23.052 +08:00] [ERROR] [BaseDaemon.cpp:570] ["BaseDaemon:
       0x1ed2681\tfaultSignalHandler(int, siginfo_t*, void*) [tiflash+32319105]
                \tlibs/libdaemon/src/BaseDaemon.cpp:221
  0x7f89142525d0\t<unknown symbol> [libpthread.so.0+62928]
  0x7f89176491ef\trocksdb::MemTable::KeyComparator::operator()(char const*, rocksdb::Slice const&) const [libtiflash_proxy.so+44941807]
  0x7f8917647584\trocksdb::DoublySkipList<rocksdb::MemTableRep::KeyComparator const&>::InsertPrevListCAS(rocksdb::DoublySkipList<rocksdb::MemTableRep::KeyComparator const&>::Node*, rocksdb::DoublySkipList<rocksdb::MemTableRep::KeyComparator const&>::Splice*, rocksdb::Slice const&) [libtiflash_proxy.so+44934532]
  0x7f8917647292\tbool rocksdb::DoublySkipList<rocksdb::MemTableRep::KeyComparator const&>::Insert<true>(char const*, rocksdb::DoublySkipList<rocksdb::MemTableRep::KeyComparator const&>::Splice*, bool) [libtiflash_proxy.so+44933778]
  0x7f8917646477\trocksdb::(anonymous namespace)::SkipListRep<rocksdb::DoublySkipList>::InsertKeyConcurrently(void*) [libtiflash_proxy.so+44930167]
  0x7f8917649a15\trocksdb::MemTable::Add(unsigned long, rocksdb::ValueType, rocksdb::Slice const&, rocksdb::Slice const&, bool, rocksdb::MemTablePostProcessInfo*) [libtiflash_proxy.so+44943893]
  0x7f8917790b08\trocksdb::MemTableInserter::PutCFImpl(unsigned int, rocksdb::Slice const&, rocksdb::Slice const&, rocksdb::ValueType) [libtiflash_proxy.so+46283528]
  0x7f891778ee04\trocksdb::MemTableInserter::PutCF(unsigned int, rocksdb::Slice const&, rocksdb::Slice const&) [libtiflash_proxy.so+46276100]
  0x7f891778ab12\trocksdb::WriteBatch::Iterate(rocksdb::WriteBatch::Handler*) const [libtiflash_proxy.so+46258962]
  0x7f891778e258\trocksdb::WriteBatchInternal::InsertInto(rocksdb::WriteThread::Writer*, unsigned long, rocksdb::ColumnFamilyMemTables*, rocksdb::FlushScheduler*, bool, unsigned long, rocksdb::DB*, bool, bool, unsigned long, bool) [libtiflash_proxy.so+46273112]
  0x7f89178a1658\trocksdb::DBImpl::PipelinedWriteImpl(rocksdb::WriteOptions const&, rocksdb::WriteBatch*, rocksdb::WriteCallback*, unsigned long*, unsigned long, bool, unsigned long*) [libtiflash_proxy.so+47400536]
  0x7f891789b858\trocksdb::DBImpl::WriteImpl(rocksdb::WriteOptions const&, rocksdb::WriteBatch*, rocksdb::WriteCallback*, unsigned long*, unsigned long, bool, unsigned long*, unsigned long, rocksdb::PreReleaseCallback*) [libtiflash_proxy.so+47376472]
  0x7f891789b328\trocksdb::DBImpl::Write(rocksdb::WriteOptions const&, rocksdb::WriteBatch*) [libtiflash_proxy.so+47375144]
  0x7f8917617a67\tcrocksdb_write [libtiflash_proxy.so+44739175]
  0x7f89159af842\tengine_rocks::raft_engine::_$LT$impl$u20$engine_traits..raft_engine..RaftEngine$u20$for$u20$engine_rocks..engine..RocksEngine$GT$::consume::hf6ee5ed393aad2a3 [libtiflash_proxy.so+14952514]
  0x7f89159af94d\tengine_rocks::raft_engine::_$LT$impl$u20$engine_traits..raft_engine..RaftEngine$u20$for$u20$engine_rocks..engine..RocksEngine$GT$::consume_and_shrink::hfb711f9c27030b7e [libtiflash_proxy.so+14952781]
  0x7f89167f1ba2\traftstore::store::async_io::write::Worker$LT$EK$C$ER$C$N$C$T$GT$::write_to_db::hdb8b8f65063fed69 [libtiflash_proxy.so+29903778]
  0x7f89163399ec\tbatch_system::batch::Poller$LT$N$C$C$C$Handler$GT$::poll::hd6ab13beb1469de7 [libtiflash_proxy.so+24955372]
  0x7f89169effbe\tstd::sys_common::backtrace::__rust_begin_short_backtrace::h716f8f3468ff30a3 [libtiflash_proxy.so+31993790]
  0x7f891622a0a7\tcore::ops::function::FnOnce::call_once$u7b$$u7b$vtable.shim$u7d$$u7d$::he4699ce7755d8105 [libtiflash_proxy.so+23842983]
  0x7f8916c00fca\tstd::sys::unix::thread::Thread::new::thread_start::hd39c5f08bdcda277 [libtiflash_proxy.so+34160586]
  0x7f891424add5\tstart_thread [libpthread.so.0+32213]"] [thread_id=56]
[2022/11/14 23:30:23.052 +08:00] [ERROR] [BaseDaemon.cpp:377] [BaseDaemon:########################################] [thread_id=56]

**Comment by flowbehappy** [comment]
This issue only occurs in a user's environment, and is likely caused by OOM killed https://github.com/pingcap/tiflash/issues/6407. Since it is a corner case and very difficult to reproduce, I suggest change to `severity/major`.

**Comment by flowbehappy** [comment]
Close because can not reproduce.
