### ISSUE TITLE
Write stall cause memory usage peak

### ISSUE THREAD

**Issue by flowbehappy** [pingcap/tiflash#6332]
## Enhancement

Keep writing into an increasing PK(without shard_rows_bit) table with large throughput(over 15MB/s). The Avg_row_length  is 1764.  
Then try to restart tiflash:

1. The memory peak is most significant after restarting.
2. Write stall during the normal phase also causes high memory usage

![c7d583e9-9417-4919-9acb-79f3b737708a](https://user-images.githubusercontent.com/2639319/202595156-80c8b006-dad4-4c1a-8e77-72678e770bea.jpeg)
![1504e39b-4f61-49a8-8e5b-8b7dd9492bb8](https://user-images.githubusercontent.com/2639319/202595171-383c3226-d006-4a3b-bf08-eddc08ddb7fd.jpeg)

**Comment by flowbehappy** [comment]
To do:
1. Accurate metrics about memory consumption of each part.
2. Control memory usage to a reasonable level.

**Comment by hongyunyan** [comment]
It's the same as https://github.com/pingcap/tiflash/issues/6399, thus close this issue.
