### ISSUE TITLE
Reduce the object number of schema(Block)

### ISSUE THREAD

**Issue by flowbehappy** [pingcap/tiflash#6333]
## Enhancement

There is one schema instance for each Segment and each DeltaMergeStorage. Most of the schema instances are identical inside a table. And partitions of a table typically share the same schema. Many schema instances cause a lot of memory.

The program below causes 680MB on my laptop.

```
TEST(SchemaSize, XXX)
{
    auto set = std::list<BlockPtr>();
    for(int i = 0; i < 20000; i ++)
    {
        auto schema = std::make_shared<Block>();
        for (size_t col_id = 1; col_id < 144; ++col_id)
        {
            schema->insert(ColumnWithTypeAndName({}, DataTypeFactory::instance().get("String"), "latest_scan_franchisee_code", col_id));
        }
        set.push_back(schema);
    }

    auto log = Logger::get("SchemaSize");
    LOG_INFO(log, "Done!=====================");

    std::this_thread::sleep_for(std::chrono::milliseconds(1000 * 60 * 5));
}
```

**Comment by Lloyd-Pottiger** [comment]
in master, seems there is no schema instance in segment?

https://github.com/pingcap/tiflash/blob/a2acd1fad2536181ecd7aaa48d84bd5b26c9005f/dbms/src/Storages/DeltaMerge/Segment.h#L534-L557

**Comment by JaySon-Huang** [comment]
@Lloyd-Pottiger  The schema instance is mainly stored by the `ColumnFile` object

**Comment by JaySon-Huang** [comment]
Supplementary: The `colid_to_offset` should be stored in the `schema` instance to save more unnecessary memory.
https://github.com/pingcap/tiflash/blob/7203151a59ac7c44c673fc5f689fef312c660731/dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFileTiny.h#L30-L49
