### ISSUE TITLE
thread_pool_active is not 400 after stopping query for some time

### ISSUE THREAD

**Issue by lilinghai** [pingcap/tiflash#6337]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

random failpoint test
![image](https://user-images.githubusercontent.com/7677963/202969159-4d39381d-041b-4c26-bfaa-a4b017470064.png)

### 4. What is your TiFlash version? (Required)
master

**Comment by SeaRise** [comment]
close by https://github.com/pingcap/endless/pull/1182
