### ISSUE TITLE
tiflash_regression_test_daily fails on release-6.5

### ISSUE THREAD

**Issue by jebter** [pingcap/tiflash#6419]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

https://ci.pingcap.net/blue/organizations/jenkins/tiflash_regression_test_daily/detail/tiflash_regression_test_daily/3599/pipeline/#step-76-log-1171

### 2. What did you expect to see? (Required)
pass
### 3. What did you see instead (Required)
![image](https://user-images.githubusercontent.com/4425235/205562161-6e9ea6d4-ecfb-4a17-9c44-a6cb2200cb84.png)

### 4. What is your TiFlash version? (Required)
v6.5.0

**Comment by MimeLyc** [comment]
update status
