### ISSUE TITLE
Refine cop thread pool's waiting logic: add `waitFor` method and `queued_size` method

### ISSUE THREAD

**Issue by LittleFall** [pingcap/tiflash#6440]
## Enhancement

when we want to submit a job to cop-pool, we can only use the `schedule` method now.

we should add a waitFor or waitUntil interface, set a timeout for it.

this can be done after https://github.com/pingcap/tiflash/issues/6439.

and then we can check the `max_queued_duration_seconds` limit outer of thread pool.

**Comment by SeaRise** [comment]
closed by https://github.com/pingcap/tiflash/pull/8168
