### ISSUE TITLE
MPPTask GTest might fail due to column prune

### ISSUE THREAD

**Issue by yibin87** [pingcap/tiflash#6442]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

Create a MPPTask gtest, 
`        
context.addMockTable(
            {"test_db", "test_table_2"},
            {{"s1", TiDB::TP::TypeLong}, {"s2", TiDB::TP::TypeString}, {"s3", TiDB::TP::TypeString}},
            {toNullableVec<Int32>("s1", {0, 0, 0}), toNullableVec<String>("s2", {"1", "11", "8"}), toNullableVec<String>("s3", {"4", "9", "99"})});

auto request = context
                           .scan("test_db", "test_table_2")
                           .aggregation({Max(col("s3"))}, {col("s1")});`
Build the request with buildMPPTasks, and run it with related API.

### 2. What did you expect to see? (Required)
max(s3) is "99"

### 3. What did you see instead (Required)
max(s3) is "8"

### 4. What is your TiFlash version? (Required)
Latest

The problem is introduced in three steps:
1. columePrune when buildMPPTasks will prune TableScan's output columns to {"s1", "s3"}
https://github.com/pingcap/tiflash/blob/8d406ba86848a48eb0fd04903bee66eccaee5def/dbms/src/TestUtils/mockExecutor.cpp#L133
2. AggregationBinder will calculate the column idx, 1 for "s3", and saved it in tidb's executor
3. However, in PhysicalMockTableScan.cpp, it gets all columns {"s1", "s2", "s3"} instead of {"s1", "s3"}, and thus aggregator will use "s2" column to do max aggregation.
https://github.com/pingcap/tiflash/blob/8d406ba86848a48eb0fd04903bee66eccaee5def/dbms/src/Flash/Planner/plans/PhysicalMockTableScan.cpp#L52

**Comment by ywqzzy** [comment]
MockStorage didn't follow the column prune process, I will fix it.
