### ISSUE TITLE
TiFlash crash after restart

### ISSUE THREAD

**Issue by hehechen** [pingcap/tiflash#6552]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
Restart TiFlash when syncing data.

### 2. What did you expect to see? (Required)
TiFlash restart successfully.
### 3. What did you see instead (Required)
TiFlash crash and can't restart.

[2022/12/23 06:41:59.228 +00:00] [ERROR] [Exception.cpp:89] ["Code: 49, e.displayText() = DB::Exception: Restore position from BlobStat failed, the space/subspace is already being used [offset=168374367] [buf_size=167043] [blob_id=95], e.what() = DB::Exception, Stack trace:

       0x1721fce\tDB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) [tiflash+24256462]
                \tdbms/src/Common/Exception.h:46
       0x6c8b577\tDB::PS::V3::BlobStats::BlobStat::restoreSpaceMap(unsigned long, unsigned long) [tiflash+113816951]
                \tdbms/src/Storages/Page/V3/Blob/BlobStat.cpp:331
       0x6c8b2e4\tDB::PS::V3::BlobStats::restoreByEntry(DB::PS::V3::PageEntryV3 const&) [tiflash+113816292]
                \tdbms/src/Storages/Page/V3/Blob/BlobStat.cpp:47
       0x6c4f975\tDB::PS::V3::PageDirectoryFactory::createFromReader(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::shared_ptr<DB::PS::V3::WALStoreReader>, std::__1::unique_ptr<DB::PS::V3::WALStore, std::__1::default_delete<DB::PS::V3::WALStore> >) [tiflash+113572213]
                \tdbms/src/Storages/Page/V3/PageDirectoryFactory.cpp:69
       0x6c4e651\tDB::PS::V3::PageDirectoryFactory::create(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::shared_ptr<DB::FileProvider>&, std::__1::shared_ptr<DB::PSDiskDelegator>&, DB::PS::V3::WALConfig) [tiflash+113567313]
                \tdbms/src/Storages/Page/V3/PageDirectoryFactory.cpp:37
       0x6c64eb1\tDB::PS::V3::PageStorageImpl::restore() [tiflash+113659569]
                \tdbms/src/Storages/Page/V3/PageStorageImpl.cpp:73
       0x69b54fb\tDB::DM::GlobalStoragePool::restore() [tiflash+110843131]
                \tdbms/src/Storages/DeltaMerge/StoragePool.cpp:124
       0x620c08e\tDB::Context::initializeGlobalStoragePoolIfNeed(DB::PathPool const&) [tiflash+102809742]
                \tdbms/src/Interpreters/Context.cpp:1589
       0x178419a\tDB::Server::main(std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&) [tiflash+24658330]
                \tdbms/src/Server/Server.cpp:1092
       0x712c29a\tPoco::Util::Application::run() [tiflash+118669978]
                \tcontrib/poco/Util/src/Application.cpp:335
       0x7135e24\tPoco::Util::ServerApplication::run(int, char) [tiflash+118709796]
                \tcontrib/poco/Util/src/ServerApplication.cpp:618
       0x179068d\tmainEntryClickHouseServer(int, char) [tiflash+24708749]
                \tdbms/src/Server/Server.cpp:1398
       0x170e3dc\tmain [tiflash+24175580]
                \tdbms/src/Server/main.cpp:167
  0x7f09a70c3555\t__libc_start_main [libc.so.6+140629]
       0x15040a9\t<unknown symbol> [tiflash+22036649]"] [source="bool DB::Context::initializeGlobalStoragePoolIfNeed(const DB::PathPool &)"] [thread_id=1]
### 4. What is your TiFlash version? (Required)
v6.5.0 41c08dbe20901f6cfd28ce642b39ce53f35ef48a

**Comment by flowbehappy** [comment]
Downgrade the severity to major since can not reproduce.
