### ISSUE TITLE
Mpp tracing log pattern changed that trace tool doesn't work now

### ISSUE THREAD

**Issue by yibin87** [pingcap/tiflash#6587]
Due to #6080 and #6459, mpp tracing log pattern changed from 
""mpp_task_tracing:MPP<query:438542035654017025,task:1>" 
to
"mpp_task_tracing MPP<query:<query_ts:1672898715463452291, local_query_id:24, server_id:2059159, start_ts:438540360860565580>,task_id:9>"
And the trace tool uses pattern like "", thus failed to work.
Besides, the new query id "query_ts:1672898715463452291, local_query_id:24, server_id:2059159, start_ts:438540360860565580" is not valid json format.

**Comment by hehechen** [comment]
I think this issue doesn't affect 6.4 or 6.5?
