### ISSUE TITLE
IPV6 support: TiFlash should be able to listen on IPv6 address instead of IPv4 if set IPv6 as default for 8234 and 9000

### ISSUE THREAD

**Issue by mayjiang0203** [pingcap/tiflash#6598]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
config k8s cluster as following.
ipFamilyPolicy: PreferDualStack
ipFamilies:

IPv6
IPv4

### 2. What did you expect to see? (Required)
sh-4.2# netstat -anp
Active Internet connections (servers and established)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      :::8234            0.0.0.0:*               LISTEN      1/tiflash
tcp        0      :::9000            0.0.0.0:*               LISTEN      1/tiflash
tcp        0      :::8123            0.0.0.0:*               LISTEN      1/tiflash

### 3. What did you see instead (Required)
sh-4.2# netstat -anp
Active Internet connections (servers and established)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 0.0.0.0:8234            0.0.0.0:*               LISTEN      1/tiflash
tcp        0      0 0.0.0.0:9000            0.0.0.0:*               LISTEN      1/tiflash
tcp        0      0 0.0.0.0:8123            0.0.0.0:*               LISTEN      1/tiflash
tcp        0      0 100.96.1.50:45006       39.155.141.16:80        TIME_WAIT   -
tcp        0      0 100.96.1.50:41712       210.28.130.3:80         TIME_WAIT   -
tcp        0      0 100.96.1.50:45010       39.155.141.16:80        TIME_WAIT   -
tcp        0      0 100.96.1.50:42652       45.125.0.6:80           TIME_WAIT   -
tcp        0      0 100.96.1.50:45004       39.155.141.16:80        TIME_WAIT   -
tcp        0      0 100.96.1.50:40774       103.109.101.20:80       TIME_WAIT   -
tcp        0      0 100.96.1.50:56804       101.71.33.11:80         TIME_WAIT   -
tcp        0      0 100.96.1.50:56796       101.71.33.11:80         TIME_WAIT   -
tcp        0      0 100.96.1.50:55850       124.70.125.153:80       TIME_WAIT   -
tcp        0      0 100.96.1.50:40612       101.6.15.130:80         TIME_WAIT   -
tcp        0      0 100.96.1.50:56802       101.71.33.11:80         TIME_WAIT   -
tcp        0      0 100.96.1.50:42138       210.44.151.62:80        TIME_WAIT   -
tcp        0      0 100.96.1.50:56800       101.71.33.11:80         TIME_WAIT   -
tcp        0      0 100.96.1.50:56806       101.71.33.11:80         TIME_WAIT   -
tcp        0      0 100.96.1.50:49754       202.201.2.130:80        TIME_WAIT   -
tcp        0      0 100.96.1.50:51024       180.209.95.9:80         TIME_WAIT   -
tcp        0      0 100.96.1.50:38896       202.38.97.230:80        TIME_WAIT   -
tcp        0      0 100.96.1.50:44574       218.104.71.170:80       TIME_WAIT   -
tcp        0      0 100.96.1.50:42714       211.68.71.121:80        TIME_WAIT   -
tcp        0      0 100.96.1.50:40776       103.109.101.20:80       TIME_WAIT   -
tcp        0      0 100.96.1.50:40614       101.6.15.130:80         TIME_WAIT   -
tcp        0      0 100.96.1.50:42654       45.125.0.6:80           TIME_WAIT   -
tcp        0      0 100.96.1.50:42140       210.44.151.62:80        TIME_WAIT   -
tcp        0      0 100.96.1.50:53044       42.200.151.138:80       TIME_WAIT   -
tcp        0      0 100.96.1.50:51026       180.209.95.9:80         TIME_WAIT   -
tcp        0      0 100.96.1.50:53042       42.200.151.138:80       TIME_WAIT   -
tcp6       0      0 :::3930                 :::*                    LISTEN      1/tiflash
tcp6       0      0 :::20292                :::*                    LISTEN      1/tiflash
tcp6       0      0 :::20170                :::*                    LISTEN      1/tiflash
tcp6      17      0 fd00:100:96:1::32:34428 fd00:100:96:2::49:2379  ESTABLISHED 1/tiflash
tcp6       0      0 fd00:100:96:1::32:51414 fd00:100:96:2::4d:20160 ESTABLISHED 1/tiflash
tcp6       0      0 fd00:100:96:1::32:34426 fd00:100:96:2::49:2379  ESTABLISHED 1/tiflash
tcp6       0      0 fd00:100:96:1::32:20292 fd00:100:96:1::34:50858 ESTABLISHED 1/tiflash
tcp6       0      0 fd00:100:96:1::32:46256 fd00:100:96:2::4a:2379  ESTABLISHED 1/tiflash
tcp6       0      0 fd00:100:96:1::32:59538 fd00:100:96:1::33:20160 ESTABLISHED 1/tiflash
tcp6       0      0 fd00:100:96:1::32:50788 fd00:100:64::3faf:2379  ESTABLISHED 1/tiflash
tcp6       0      0 fd00:100:96:1::32:20292 fd00:100:96:2::4e:56544 ESTABLISHED 1/tiflash

### 4. What is your TiFlash version? (Required)
v6.5.0

This issue may cause two tiflash related system table can't be accessed, and no data can be get from monitor.
mysql> select * from TIFLASH_SEGMENTS;
ERROR 1105 (HY000): Get "http://basic-tiflash-1.basic-tiflash-peer.user-py.svc:8123?default_format=JSONCompact&query=SELECT+%2A+FROM+system.dt_segments+LIMIT+0%2C+1024": dial tcp [fd00:100:96:2::54]:8123: connect: connection refused

![image](https://user-images.githubusercontent.com/9443637/211003530-58da2959-759b-45db-a9cf-277c242e128a.png)

**Comment by ywqzzy** [comment]
Will be fixed in tidb-operator

**Comment by dveeden** [comment]
> Will be fixed in tidb-operator

Do you have a link to the tidb-operator issue for this?

It looks like `tiup playground --without-monitor --host ::1 v6.5.0` works for TiDB and TiKV, but not for TiFlash. Is that another IPv6 issue?
