### ISSUE TITLE
Exchange operator enhancement

### ISSUE THREAD

**Issue by solotzg** [pingcap/tiflash#6620]
## Enhancement

For now, exchange sender & receiver can occupy huge network bandwidth if there is lots of data to be shuffled(like tpch q9, q5, q18, .etc). A typical server ethernet profile is like
```
Ethernet
  - Speed: 10000Mb/s
  - Duplex: Full
  - upper bound:
    - net/recv 1250MB
    - net/send 1250MB

Memory: DDR4, 2133 MT/s ≈ 17064 MB/s
```

The limited network transfer speed may become bottleneck easily and make other operator after exchange receiver wait. The resource usage about CPU will be quit low. To accelerate exchange operator, an optional way is to use data compression.

#### Starrocks
Set compression type according to query options. If transmission_compression_type is not set, use compress_rowbatches to check if compress transmitted data. Default value of compress_rowbatches is TRUE. Default compress method is LZ4.
- [compress_rowbatches](https://github.com/StarRocks/starrocks/blob/41f46a60c13721f049a809998d4a2d7fa012e30b/docs/administration/Configuration.md): TRUE
  - The boolean value to control if to compress the row batches in RPCs between BEs. This configuration item is used for the data transmission between query layers. The value true indicates to compress the row batches. The value false indicates not to compress the row batches.
  - [CONF_mDouble(rpc_compress_ratio_threshold, "1.1");](https://github.com/StarRocks/starrocks/blob/234dbe483c9df63a783e9580d674d619f47c74d1/be/src/common/config.h#L191-L193)
    - Compress ratio when shuffle row_batches in network, not in storage engine.If ratio is less than this value, use uncompressed data instead.
- [exchange_sink_operator.cpp#L381-L388 / ExchangeSinkOperator::prepare](https://github.com/StarRocks/starrocks/blob/465c43bcaf22debe4b0f646289ee7c07e3752725/be/src/exec/pipeline/exchange/exchange_sink_operator.cpp#L381-L388)
  - LZ4 compress method
  - [exchange_sink_operator.cpp#L687-L693](https://github.com/StarRocks/starrocks/blob/465c43bcaf22debe4b0f646289ee7c07e3752725/be/src/exec/pipeline/exchange/exchange_sink_operator.cpp#L687-L693)
    - if compress_ratio > config::rpc_compress_ratio_threshold
      - dst->set_compress_type(_compress_type);
- [data_stream_sender.cpp#L420-L432 / DataStreamSender::prepare](https://github.com/StarRocks/starrocks/blob/465c43bcaf22debe4b0f646289ee7c07e3752725/be/src/runtime/data_stream_sender.cpp#L420-L432)

#### Clickhouse
- No exchange between instances

#### Presto
Page is the data structure which holds data and is transferred between Presto physical execution operators: upstream operator produces output through getOutput().
Just like Block, Page also needs to serialized & deserialized, serialization happens when data needs to transferred between workers. When Page is serialized, it will first encode the Blocks using corresponding BlockEncoding, and then if a compressor is available, it will try to compress the encoded block data. If compression works well(have encoding rate lower than 0.8), it will use compressed data, otherwise uncompressed data is used. The encoded block data will be put into a class named SerializedPage along with some statistic information: the byte size of the page before & after compression.

### Investigation

Env
- TPCH-100
- TiFlash x 3
- TIFLASH REPLICA x 3

  | NONE | LZ4 | ZSTD | NET/IO Reduce(LZ4)/(NONE)-1.0 | NET/IO Reduce(ZSTD)/(NONE)-1.0
-- | -- | -- | -- | -- | --
Total Exchange Size(GB) | 267.186 | 117.836 | 63.269 | 55.90% | 76.32%
Total Exchange Size By NET (GB) | 178.124 | 78.557 | 42.179 |   |  

- Approximate Compress Codec Throughput Per CPU Core:
  - NONE
    - Input: 2169.3 MB/s
    - Output: 2169.3 MB/s
  - LZ4
    - Input: 210.9 MB/s
    - Output: 78.0 MB/s
  - ZSTD
    - Input: 126.0 MB/s
    - Output: 18.9 MB/s
- Expected Performance Improvement About TPCH-100 By Compression Method:
  - 3 x TiFlash: 9.17%(LZ4)
  - More TiFlash stores, better performance improvement
  - Average CPU usage is higher than the original way
- Expected NET/IO Reduce TPCH-100 By Compression Method:
  - 3 x TiFlash:
    - LZ4: 99.567 GB (178.124-78.557)
    - ZSTD: 135.945 GB (178.124-42.179)
  - Approximate 56.00%(LZ4), 76.67%(ZSTD)

### Progress

- [ ] https://github.com/pingcap/tidb/pull/40132
- [x] https://github.com/pingcap/kvproto/pull/1027
- [x] https://github.com/pingcap/tipb/pull/285
- [ ] https://github.com/pingcap/tiflash/pull/6596

### Benchmark

- TPCH-100
- TiFlash x 3
- TIFLASH REPLICA x 3
- Base branch:
  - TiDB: e1a2b5865
  - TiFash: [b930bd82d](https://github.com/pingcap/tiflash/commit/b930bd82d)

Time(s) | NONE | FAST(LZ4) | HC(ZSTD) | Improvement: (Original) / (FAST) - 1.0 | Improvement: (Original) / (HC) - 1.0
-- | -- | -- | -- | -- | --
Q1 | 3.25 | 2.92 | 2.99 | 11.30% | 8.70%
Q2 | 1.44 | 1.24 | 1.51 | 16.13% | -4.64%
Q3 | 3.39 | 3.12 | 3.05 | 8.65% | 11.15%
Q4 | 2.65 | 2.58 | 2.52 | 2.71% | 5.16%
Q5 | 7.89 | 6.61 | 7.55 | 19.36% | 4.50%
Q6 | 0.7 | 0.7 | 0.7 | 0.00% | 0.00%
Q7 | 3.39 | 2.99 | 3.39 | 13.38% | 0.00%
Q8 | 6.01 | 5.27 | 4.93 | 14.04% | 21.91%
Q9 | 22.31 | 19.03 | 21.71 | 17.24% | 2.76%
Q10 | 4.6 | 4.4 | 4.46 | 4.55% | 3.14%
Q11 | 1.24 | 0.91 | 0.91 | 36.26% | 36.26%
Q12 | 1.71 | 1.78 | 1.71 | -3.93% | 0.00%
Q13 | 3.79 | 3.52 | 3.72 | 7.67% | 1.88%
Q14 | 0.84 | 0.84 | 0.84 | 0.00% | 0.00%
Q15 | 1.85 | 1.85 | 1.78 | 0.00% | 3.93%
Q16 | 1.11 | 1.11 | 1.17 | 0.00% | -5.13%
Q17 | 7.21 | 6.95 | 7.28 | 3.74% | -0.96%
Q18 | 8.62 | 7.42 | 8.42 | 16.17% | 2.38%
Q19 | 1.85 | 1.85 | 1.98 | 0.00% | -6.57%
Q20 | 1.44 | 1.38 | 1.51 | 4.35% | -4.64%
Q21 | 9.76 | 9.23 | 9.7 | 5.74% | 0.62%
Q22 | 0.7 | 0.7 | 0.77 | 0.00% | -9.09%
SUM | 95.75 | 86.4 | 92.6 | 10.82% |  3.40%

**Comment by xzhangxian1008** [comment]
No performance regression is found. [benchmark here](https://pingcap.feishu.cn/wiki/wikcnyWs8QFG6mrarjLdrFZoM5d?table=tblc8QI60qvMWEvD&view=vewJ1KLsrK)
