### ISSUE TITLE
Use thread_id in RWLock instead of thread name

### ISSUE THREAD

**Issue by hehechen** [pingcap/tiflash#6631]
## Enhancement
https://github.com/pingcap/tiflash/blob/9b8503bca9665b66ffcfef39f3c406dcf560c709/dbms/src/Storages/Transaction/PartitionStreams.cpp#L83 use thread name to get RWLock. But the thread name of different threads may be same, because the max length of thread name is 16, but some proxy thread name has exceeded 16.
![image](https://user-images.githubusercontent.com/14118780/211972161-d7819f4b-6491-4d00-b383-71a4de6c3ffc.png)
So the thread names of different threads obtained through `getThreadName` may be the same.
I think we should use thread_id in RWLock instead of thread name to avoid exception when get RWlock.

**Comment by JaySon-Huang** [comment]
I think we can use `${thread_name}_${thread_id}` as the table RWLock query_id. The `thread_name` should be helpful for debugging, we can improve the error message inside RWLock.
