### ISSUE TITLE
TiFlash V6.5.0 produce much core.* full the disk space then can not startup

### ISSUE THREAD

**Issue by tkavenh** [pingcap/tiflash#6675]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
ALTER DATABASE bench_tpch SET TIFLASH REPLICA 1;

### 4. What is your TiFlash version? (Required)
TiFlash
Release Version: v6.5.0
Edition:         Community
Git Commit Hash: 41c08dbe20901f6cfd28ce642b39ce53f35ef48a
Git Branch:      heads/refs/tags/v6.5.0
UTC Build Time:  2022-12-21 12:03:40
Enable Features: jemalloc sm4(GmSSL) avx2 avx512 unwind thinlto
Profile:         RELWITHDEBINFO

Raft Proxy
Git Commit Hash:   ea48821d77b57a276ce3a1363de8875c07d96756
Git Commit Branch: HEAD
UTC Build Time:    2022-12-21 12:08:30
Rust Version:      rustc 1.67.0-nightly (96ddd32c4 2022-11-14)
Storage Engine:    tiflash
Prometheus Prefix: tiflash_proxy_
Profile:           release

[tiflash-9000.zip](https://github.com/pingcap/tiflash/files/10506180/tiflash-9000.zip)
https://drive.google.com/file/d/1CVZs8csdmZ1HePfgKwkxZ55iGnnMLWKF/view?usp=share_link

**Comment by Lloyd-Pottiger** [comment]
Could you please check whether `avx2` is supported in your machine?

> To deploy TiFlash under the Linux AMD64 architecture, the CPU must support AVX2 instruction sets. Use cat /proc/cpuinfo | grep avx2 to confirm that there is output. By using such CPU instruction sets, TiFlash's vectorization engine can deliver better performance.
https://docs.pingcap.com/tidb/dev/tiflash-overview#architecture

**Comment by Lloyd-Pottiger** [comment]
It's been a long time without more discussion, so close the issue, feel free to discuss here when you still meet the error.
