### ISSUE TITLE
Thread leak in random failpoint test

### ISSUE THREAD

**Issue by lilinghai** [pingcap/tiflash#6692]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```
    Expected
        <model.Vector | len:0, cap:0>: []
    to match the expected result of PromQLExpr [Tiflash active thread pool size equals 0: tiflash_thread_count{type="thread_pool_active"} == 0]
        <nil Scalar or empty Vector>
```
![img_v2_e38fbb36-19ad-44d3-af33-c58c5342621g](https://user-images.githubusercontent.com/7677963/215408449-bd6a1ffb-f355-4db5-8a2f-2232a01f4e0f.jpg)

### 4. What is your TiFlash version? (Required)
master

**Comment by yibin87** [comment]
After PR 6690, stil thread leak, thus continue to locate the problem.
![07E029D2-0CBA-4948-9B01-52D4219EE1BE](https://user-images.githubusercontent.com/12403562/215940376-8fb9f6e4-9453-4596-b163-899edf5e09fa.jpeg)
