### ISSUE TITLE
SQL in `tiup tiflash client` will meet ERROR "Code: 261. DB::Exception: Received from 127.0.0.1:9000. DB::Exception: Unknown BlockInfo field number: 1."

### ISSUE THREAD

**Issue by hongyunyan** [pingcap/tiflash#6696]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

1. tiup playground nightly
2. tiup tiflash client --host 127.0.0.1
3. show databases;

### 2. What did you expect to see? (Required)

work normally

### 3. What did you see instead (Required)

Received exception from server (version 1.1.54381):
Code: 261. DB::Exception: Received from 127.0.0.1:9000. DB::Exception: Unknown BlockInfo field number: 1.

![image](https://user-images.githubusercontent.com/26538495/215659384-84164044-5fcc-489e-a13a-11a892f39b26.png)

### 4. What is your TiFlash version? (Required)

nightly

**Comment by windtalker** [comment]
The server version is nightly(v6.6), but the client version is v6.5, in #6633, it deleted the `over_flow_row` in BlockInfo, so the old client meet this error. Use the latest client should avoid this error.
