### ISSUE TITLE
CARTESIAN (left outer) (anti) semi join may cause OOM even if right table is not very large

### ISSUE THREAD

**Issue by gengliqi** [pingcap/tiflash#6730]
## Bug Report

For CARTESIAN (left outer) (anti) semi join, each row in the left table's block must be combined with all of the rows in the right table's block in order to execute `other_conditions` expression or/and `other_eq_conditions_from_in` expression.

After that, according to the result of expressions, each row in the left table's block will only produce one or zero number of rows to the result block through `filter` function as below.
https://github.com/pingcap/tiflash/blob/4206a522521d19d918ae0483a482874f727da30e/dbms/src/Interpreters/Join.cpp#L1460

https://github.com/pingcap/tiflash/blob/4206a522521d19d918ae0483a482874f727da30e/dbms/src/Interpreters/Join.cpp#L1545
&nbsp;
Then the issue comes. The allocated memory size of these columns may be much greater than the used memory size of them because `filter` will use the size of source column to reserve.
https://github.com/pingcap/tiflash/blob/4206a522521d19d918ae0483a482874f727da30e/dbms/src/Columns/IColumn.h#L215-L222

&nbsp;
For example, suppose the number of rows in the right table is 50k, `left_rows_per_iter` will be only 1 when `max_block_size_for_cross_join` is 64k.
https://github.com/pingcap/tiflash/blob/4206a522521d19d918ae0483a482874f727da30e/dbms/src/Interpreters/Join.cpp#L1890-L1898
So in each iteration, there should be only one or zero number of rows in the result block while the allocated memory size is approximately equal to the memory of 50k rows. 

If there are 64k rows in this block of the left table, there are 64k result blocks and the allocated memory size is approximately equal to the memory of 50k * 64k = 3276800k rows, which is likely to make TiFlash OOM.

**Comment by LittleFall** [comment]
Please remove the may-affect-** tag as needed or convert it to a definitive affect-** tag to make pr pass the ci check
