### ISSUE TITLE
gcTrySegmentMergeDelta/gcTrySegmentMerge don't check the expected segments

### ISSUE THREAD

**Issue by hongyunyan** [pingcap/tiflash#6775]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 2. What did you expect to see? (Required)

we check the expected segments in gcTrySegmentMergeDelta/gcTrySegmentMerge.

### 3. What did you see instead (Required)

we check the abondoned segments in gcTrySegmentMergeDelta/gcTrySegmentMerge.

### 4. What is your TiFlash version? (Required)

nightly

**Comment by JaySon-Huang** [comment]
Confirm this bug does not affect the release-6.1 branch.
https://github.com/pingcap/tiflash/blob/release-6.1/dbms/src/Storages/DeltaMerge/DeltaMergeStore.cpp#L1840-L1845
