### ISSUE TITLE
DiagnosticsService can not filter filename by datatime 

### ISSUE THREAD

**Issue by hongyunyan** [pingcap/tiflash#6829]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

1. make a cluster up
2. add a new log file like 'tiflash_tikv-2023-01-30T02-00-12.039.log' in tiflash/log
3. do log search in dashboard with time selection

### 2. What did you expect to see? (Required)

we read the log match the time selection.

### 3. What did you see instead (Required)

we read all log files in tiflash/log(when there are quite a lot of log files , search will be very slow)
![image](https://user-images.githubusercontent.com/26538495/219031339-ad8f4d08-44d9-4130-95c1-bb3e3db6d6e5.png)

This problem is related to the code FilterFileByDatetime in LogSearch.cpp, the filter function is not appropriate with the log file's name now.

### 4. What is your TiFlash version? (Required)
nightly

**Comment by hehechen** [comment]
It's because the format of TiKV log filename has been modified in 
https://github.com/tikv/tikv/pull/11657/files.

**Comment by hehechen** [comment]
This bug was introduced in v5.4.
https://github.com/pingcap/tidb-engine-ext/blob/c15322fd615c518b0fa2d2204dbdf32dd0b4cfdf/components/server/src/setup.rs#L42
