### ISSUE TITLE
Too many logging cause slow queries

### ISSUE THREAD

**Issue by JaySon-Huang** [pingcap/tiflash#6845]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

Deployed on 8 vcore machine.

A short query slows down from 0.5s to 6 seconds when concurrency increases from 1 to 32. While the maximum CPU usage is only 550.

### 3. What did you see instead (Required)

the short query slow down from 0.5s to 6 seconds when concurrency increase from 1 to 32.

After tuning these config, the performance is much better. One of the reasons is that printing too many logs takes up disk bandwidth and causes slow queries

tidb_max_tiflash_threads = 1
task_scheduler_active_set_soft_limit = 80
async_pollers_per_cq = 8

tiflash log = error 

### 4. What is your TiFlash version? (Required)
6.5

**Comment by SeaRise** [comment]
how about https://github.com/pocoproject/poco/blob/5c3f827c8639a996dd0d27a77f48d343ed6fe524/Foundation/include/Poco/AsyncChannel.h?

**Comment by JaySon-Huang** [comment]
link https://github.com/pingcap/tiflash/pull/7285
