### ISSUE TITLE
[Performance] The CPU utilization rate is low in high concurrency scenes

### ISSUE THREAD

**Issue by NightStarSoul** [pingcap/tiflash#6975]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

Test SQL and data amount used

Data of TPCH SF 10.

select l_suppkey from lineitem where l_shipdate >= '1996-12-01'and l_shipdate < date_add('1996-12-01', interval '1' month);

The plan is shown in the figure below
![image](https://user-images.githubusercontent.com/9307143/223311342-01be5f87-7fca-43e4-b52e-cf46e0fe8b86.png)

Physical topical
The cluster formed by 3 Tifash nodes.

Problem phenomenon
In the 40 parallel scene, the utilization of the CPU continues to fluctuate around 10%, and it will not come up.
![image](https://user-images.githubusercontent.com/9307143/223311382-dc723a1c-df3b-4a13-bf15-f4bfacb5d69b.png)

![image](https://user-images.githubusercontent.com/9307143/223311626-01ddf274-4fec-4d19-8973-fb1948dc6067.png)

The system parameters use the default parameters.
![image](https://user-images.githubusercontent.com/9307143/223311424-869cdf1a-b0df-4ed5-9a4b-33cf4f1dd4c8.png)

### 2. What did you expect to see? (Required)
CPU full.

### 4. What is your TiFlash version? (Required)
tiflash v6.5.0

**Comment by xzhangxian1008** [comment]
Please set `active_set_soft_limit` to 10 times of your core number and try it again.

**Comment by NightStarSoul** [comment]
<img width="644" alt="image" src="https://user-images.githubusercontent.com/9307143/224216053-3964ffa4-6e0f-43f4-ad21-a0c6aabacb4f.png">

<img width="1427" alt="image" src="https://user-images.githubusercontent.com/9307143/224216108-47c20fba-7650-4084-a138-bd2d011cbdce.png">

从结果和监控上来看，效果不理想。

**Comment by xzhangxian1008** [comment]
Could you show me the `explain analyze` result?

**Comment by windtalker** [comment]
set `task_scheduler_active_set_soft_limit` to 400 may exceed the hard limit of it, you can refer 
https://github.com/pingcap/tiflash/blob/65b800f433a844f29803ba5a80572fce5ba4cdf4/dbms/src/Flash/Mpp/MinTSOScheduler.cpp#L39
to set a max value according to you cluster's cpu cores.

**Comment by NightStarSoul** [comment]
> Could you show me the `explain analyze` result?

`MySQL [tpch]> explain analyze  select l_suppkey from lineitem where l_shipdate >= '1996-12-01'and l_shipdate < date_add('1996-12-01', interval '1' month);
+------------------------------+-------------+----------+--------------+----------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------+---------+------+
| id                           | estRows     | actRows  | task         | access object  | execution info                                                                                                                                                                                                                                                                                                                                                                                | operator info                                                                                                      | memory  | disk |
+------------------------------+-------------+----------+--------------+----------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------+---------+------+
| TableReader_15               | 778152.67   | 772803   | root         |                | time:121.9ms, loops:922, cop_task: {num: 488, max: 0s, min: 0s, avg: 0s, p95: 0s, copr_cache_hit_ratio: 0.00}                                                                                                                                                                                                                                                                                 | MppVersion: 1, data:ExchangeSender_14                                                                              | 39.3 KB | N/A  |
| └─ExchangeSender_14          | 778152.67   | 772803   | mpp[tiflash] |                | tiflash_task:{proc max:60.9ms, min:30.5ms, avg: 44.3ms, p80:60.9ms, p95:60.9ms, iters:984, tasks:3, threads:71}                                                                                                                                                                                                                                                                               | ExchangeType: PassThrough                                                                                          | N/A     | N/A  |
|   └─Projection_5             | 778152.67   | 772803   | mpp[tiflash] |                | tiflash_task:{proc max:60.9ms, min:30.5ms, avg: 44.3ms, p80:60.9ms, p95:60.9ms, iters:984, tasks:3, threads:71}                                                                                                                                                                                                                                                                               | tpch.lineitem.l_suppkey                                                                                            | N/A     | N/A  |
|     └─Selection_13           | 778152.67   | 772803   | mpp[tiflash] |                | tiflash_task:{proc max:60.9ms, min:30.5ms, avg: 44.3ms, p80:60.9ms, p95:60.9ms, iters:984, tasks:3, threads:71}                                                                                                                                                                                                                                                                               | ge(tpch.lineitem.l_shipdate, 1996-12-01 00:00:00.000000), lt(tpch.lineitem.l_shipdate, 1997-01-01 00:00:00.000000) | N/A     | N/A  |
|       └─TableFullScan_12     | 59986052.00 | 59986052 | mpp[tiflash] | table:lineitem | tiflash_task:{proc max:52.9ms, min:26.5ms, avg: 38.9ms, p80:52.9ms, p95:52.9ms, iters:984, tasks:3, threads:71}, tiflash_scan:{dtfile:{total_scanned_packs:7441, total_skipped_packs:0, total_scanned_rows:59986052, total_skipped_rows:0, total_rs_index_load_time: 1ms, total_read_time: 1103ms}, total_create_snapshot_time: 0ms, total_local_region_num: 131, total_remote_region_num: 0} | keep order:false                                                                                                   | N/A     | N/A  |
+------------------------------+-------------+----------+--------------+----------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------+---------+------+`

**Comment by NightStarSoul** [comment]
> set `task_scheduler_active_set_soft_limit` to 400 may exceed the hard limit of it, you can refer
> 
> https://github.com/pingcap/tiflash/blob/65b800f433a844f29803ba5a80572fce5ba4cdf4/dbms/src/Flash/Mpp/MinTSOScheduler.cpp#L39-L43
> 
> 
> to set a max value according to you cluster's cpu cores.

Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                80
On-line CPU(s) list:   0-79
Thread(s) per core:    2
Core(s) per socket:    20
座：                 2
NUMA 节点：         2
厂商 ID：           GenuineIntel
CPU 系列：          6
型号：              85
型号名称：        Intel(R) Xeon(R) Gold 6133 CPU @ 2.50GHz
步进：              4
CPU MHz：             2501.000
CPU max MHz:           2501.0000
CPU min MHz:           1000.0000
BogoMIPS：            4999.98
虚拟化：           VT-x
L1d 缓存：          32K
L1i 缓存：          32K
L2 缓存：           1024K
L3 缓存：           28160K
NUMA 节点0 CPU：    0-19,40-59
NUMA 节点1 CPU：    20-39,60-79
Flags:                 fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf eagerfpu pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch epb intel_pt tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm cqm mpx avx512f avx512dq rdseed adx smap clflushopt clwb avx512cd avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc dtherm ida arat pln pts

**Comment by xzhangxian1008** [comment]
set task_scheduler_thread_soft_limit = 9000, set task_scheduler_active_set_soft_limit = 400 and run 
```sql
explain analyze select l_suppkey, L_ORDERKEY*L_PARTKEY, L_SUPPKEY*L_LINENUMBER, L_QUANTITY*L_EXTENDEDPRICE, L_DISCOUNT*L_TAX, regexp_substr(L_COMMENT, ".*the.*"), regexp_substr(L_SHIPINSTRUCT, ".*the.*"), regexp_substr(L_COMMENT, ".* [a-z]{4} .*"), regexp_substr(L_SHIPINSTRUCT, ".* [A-Z]{4} .*"), l_shipdate >= '1992-12-01', l_shipdate >= '1993-12-01', l_shipdate >= '1994-12-01', l_shipdate >= '1995-12-01', l_shipdate >= '1996-12-01', l_shipdate < date_add('1996-12-01', interval '1' month) from lineitem where l_shipdate >= '1996-12-01'and l_shipdate < date_add('1996-12-01', interval '1' month);
```

The origin sql's compute task is not heavy and maybe the storage layer can't catch up with the compute layer.

I tried the above sql on my local environment and the cpu usage could be high.

**Comment by xzhangxian1008** [comment]
We try to reproduce this but get the following phenomenon:

we set task_scheduler_active_set_soft_limit = 100 and run
```sql
explain analyze select l_suppkey from lineitem where l_shipdate >= '1996-12-01'and l_shipdate < date_add('1996-12-01', interval '1' month);
```
the cpu utilization is always around about 50%
![origin](https://github.com/pingcap/tiflash/assets/15918072/eb7337e5-36af-468b-886f-217d4b292679)

then we run
```sql
explain analyze select l_suppkey, L_ORDERKEY*L_PARTKEY, L_SUPPKEY*L_LINENUMBER, L_QUANTITY*L_EXTENDEDPRICE, L_DISCOUNT*L_TAX, regexp_substr(L_COMMENT, ".*the.*"), regexp_substr(L_SHIPINSTRUCT, ".*the.*"), regexp_substr(L_COMMENT, ".* [a-z]{4} .*"), regexp_substr(L_SHIPINSTRUCT, ".* [A-Z]{4} .*"), l_shipdate >= '1992-12-01', l_shipdate >= '1993-12-01', l_shipdate >= '1994-12-01', l_shipdate >= '1995-12-01', l_shipdate >= '1996-12-01', l_shipdate < date_add('1996-12-01', interval '1' month) from lineitem where l_shipdate >= '1996-12-01'and l_shipdate < date_add('1996-12-01', interval '1' month);
```

the cpu utilization is always around about 50%
![aa](https://github.com/pingcap/tiflash/assets/15918072/94ea4f35-a185-4570-98c0-cbbd74f64469)

I think you need to add `explain analyze` before sql as this sql will return a large amount of data and this may cause the low cpu utilization.

**Comment by xzhangxian1008** [comment]
I can reproduce this phenomenon by removing `explain analyze` and the cpu utilization is ver low.
