### ISSUE TITLE
support <engine_role, write> for disaggregated tiflash 

### ISSUE THREAD

**Issue by guo-shaoge** [pingcap/tiflash#6980]
## Enhancement
We want support `non-disaggregated tiflash` and `disaggregated tiflash` in one cluster.
So for disaggregated-tiflash, compute node should dispatch MPPTask to tiflash whose label contains `<engine, tiflash>` and `<engine_role, write>`.

And for non-disaggregated tiflash, cop task will send to tiflash whose label contains `<engine, tiflash>` but not contain `<engine_role, write>`.

**Comment by JaySon-Huang** [comment]
Changes to TiDB's client-go https://github.com/tikv/client-go/pull/728
