### ISSUE TITLE
use cte sql by tikv and tiflah return different result

### ISSUE THREAD

**Issue by dmf1721511982** [pingcap/tiflash#6994]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

CREATE TABLE abc (
dec1 DECIMAL(28,4),
dec2 DECIMAL(28,4)
)

INSERT INTO abc
(dec1, dec2)
VALUES (176.9900, 176.1100);

ALTER TABLE abc SET tiflash replica 1;

WITH kc AS(
SELECT CAST(IFNULL(dec1,0) - IFNULL(dec2,0) AS DECIMAL(28,2)) book_sum_1
FROM test.abc
)
SELECT * FROM kc;

WITH kc AS(
SELECT /*+ read_from_storage(tiflash[mi]) */CAST(IFNULL(dec1,0) - IFNULL(dec2,0) AS DECIMAL(28,2)) book_sum_1
FROM test.abc mi
)
SELECT * FROM  kc;
### 2. What did you expect to see? (Required)
return the same result
### 3. What did you see instead (Required)
use tikv return 0.88 and use tiflash return 0.89
### 4. What is your TiFlash version? (Required)
6.5.0

**Comment by windtalker** [comment]
Seems there is a bug in decimal cast
