### ISSUE TITLE
DB::Exception: Check res.find(executor_id) == res.end() failed

### ISSUE THREAD

**Issue by Mini256** [pingcap/tiflash#7102]
## Enhancement

In my project, I occasionally an error message appears:

```
DB::Exception: Check res.find(executor_id) == res.end() failed
```

But I can't reproduce it, but judging from the log query, this error has occurred multiple times:

```sql
select date(created_at) AS d, COUNT(*) AS cnt
from explorer_questions
where error like '%res.find(executor_id) == res.end()%'
group by date(created_at)
order by date(created_at)
```

<img width="332" alt="image" src="https://user-images.githubusercontent.com/5086433/226232559-7422dca8-ea32-4be4-b7c5-d9ad3c6a2ce1.png">

One of links: https://ossinsight.io/explore/?id=9b2334d4-722c-4944-9269-1ef26d90b4e4

I want to know what might be the cause of the error and how to avoid it.

In addition, can it improve this error message.

**Comment by SeaRise** [comment]
Which version of tidb and tiflash?

**Comment by SeaRise** [comment]
It should be that the executor sent by tidb to tiflash has a duplicate executor id, which is not expected.

**Comment by Mini256** [comment]
TiDB version:

```
tidb_version() | Release Version: v6.6.0-serverless
Edition: Community
Git Commit Hash: ba65916645254bc350c5f815eb9521981015e607
Git Branch: release-6.6-serverless
UTC Build Time: 2023-03-13 09:34:56
GoVersion: go1.19.4
Race Enabled: false
TiKV Min Version: 6.1.0
Check Table Before Drop: false
Store: tikv
```

Sorry, I did not find the way to check the Tiflash version on Cloud Serverless.

**Comment by SeaRise** [comment]
I think this is a issue with tidb, which sends out executors with duplicate executor_id's.
Tiflash could improve the error message by bringing the bad request err code.

**Comment by Mini256** [comment]
> I think this is an issue with tidb, which sends out executors with duplicate executor_id's.

Is there an issue to track the problem on the TiDB side now ?

**Comment by SeaRise** [comment]
> > I think this is an issue with tidb, which sends out executors with duplicate executor_id's.
> 
> Is there an issue to track the problem on the TiDB side now ?

None at present.
Perhaps more useful information could be provided to help investigate the problem, such as the plan of the failed query, or the tidb logs associated with the failure, etc...

**Comment by SeaRise** [comment]
Because of duplicate executor id.
![img_v2_3f3e3c1e-8e3e-41ea-a772-43253e99d03g](https://user-images.githubusercontent.com/24507159/228588958-b8d9fc0a-f668-4748-ac4a-3de72cc74b6e.jpg)
![img_v2_3fc06f9e-e77d-4bb5-a7d3-d2826c0f594g](https://user-images.githubusercontent.com/24507159/228589020-29a12a24-ab65-4f84-881e-9271af55698e.jpg)
![img_v2_7c8578d3-4a52-41cc-9f46-9f08664aec4g](https://user-images.githubusercontent.com/24507159/228589048-b7dd1913-827c-48df-a3d0-5b8865bfa0e7.jpg)
