### ISSUE TITLE
TiFlash with s3 raise DB::Exception: Check num_msg_consumed <= num_msg_to_consume failed

### ISSUE THREAD

**Issue by lilinghai** [pingcap/tiflash#7303]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

ch workload and deploy tiflash with s3 using minio
### 3. What did you see instead (Required)
query failed for ```Error 1105: other error for mpp stream: From MPP<query:<query_ts:1681742080327309388, local_query_id:611, server_id:2259244, start_ts:440858595893182715>,task_id:1>: Code: 49, e.displayText() = DB::Exception: Code: 49, e.displayText() = DB::Exception: Check num_msg_consumed <= num_msg_to_consume failed, e.what() = DB::Exception, e.what() = DB::Exception```
### 4. What is your TiFlash version? (Required)
master

**Comment by JaySon-Huang** [comment]
[0418-ch-num_msg_consumed.tar.gz](https://github.com/pingcap/tiflash/files/11269162/0418-ch-num_msg_consumed.tar.gz)
