### ISSUE TITLE
tests/tidb-ci/fullstack-test-dt/issue_1425.test fail

### ISSUE THREAD

**Issue by Lloyd-Pottiger** [pingcap/tiflash#7334]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```
mysql> create table test.t (id int, value decimal(7,4), c1 int, c2 int);

mysql> insert into test.t values (1,1.9285,54,28), (1,1.9286,54,28);

mysql> alter table test.t set tiflash replica 1;

mysql> use test; set session tidb_isolation_read_engines='tiflash'; select * from t where value = 54/28;
```

### 2. What did you expect to see? (Required)

nothing

### 3. What did you see instead (Required)

```
+------+--------+------+------+
| id   | value  | c1   | c2   |
+------+--------+------+------+
|    1 | 1.9286 |   54 |   28 |
+------+--------+------+------+
```

### 4. What is your TiFlash version? (Required)
master

**Comment by yibin87** [comment]
Create a tidb issue to track the incorrect result: https://github.com/pingcap/tidb/issues/43311

**Comment by yibin87** [comment]
However, for
select * from t where value = c1 / c2;
TiKV returns empty set which is aligned with mysql, while tiflash returns one row:
mysql> select * from t where value = c1 / c2;
+------+--------+------+------+
| id   | value  | c1   | c2   |
+------+--------+------+------+
|    1 | 1.9286 |   54 |   28 |
+------+--------+------+------+
1 row in set (0.13 sec)

**Comment by Lloyd-Pottiger** [comment]
closed by https://github.com/pingcap/tidb/pull/43329
