### ISSUE TITLE
Unstable unit test: `WriteLimiterTest.Rate`

### ISSUE THREAD

**Issue by SeaRise** [pingcap/tiflash#7390]
https://ci.pingcap.net/blue/rest/organizations/jenkins/pipelines/tiflash-ghpr-unit-tests/runs/9633/nodes/75/steps/80/log/?start=0

```
Expected: (actual_rate / target) >= (0.80), actual: 0.792306 vs 0.8
```

**Comment by Lloyd-Pottiger** [comment]
close by #7392

**Comment by SeaRise** [comment]
> And `ReadLimiterTest.ReadMany` https://ci.pingcap.net/blue/rest/organizations/jenkins/pipelines/tiflash-ghpr-unit-tests/runs/9638/nodes/75/steps/80/log/?start=0

https://ci.pingcap.net/blue/rest/organizations/jenkins/pipelines/tiflash-ghpr-unit-tests/runs/9764/nodes/75/steps/80/log/?start=0
```
Expected: (req_ms) < (1100), actual: 1137 vs 1100
```
