### ISSUE TITLE
MPP Task hang in spill random fail point

### ISSUE THREAD

**Issue by xzhangxian1008** [pingcap/tiflash#7440]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 2. What did you expect to see? (Required)

mpp task is released quickly.

### 3. What did you see instead (Required)

https://clinic.pingcap.com.cn/grafana/d/SVbh2xUWkoperatormaster/tiflash-summary-cluster-clinic?orgId=1&var-tidb_cluster=7227604775299467630&var-instance=All&var-store=All&from=1682807849000&to=1682813931000&var-tidb_version=master&var-org=31&refresh=15m

![image](https://user-images.githubusercontent.com/15918072/236985818-12cbc3fd-f991-4bd4-896f-369cc40eb725.png)

**Comment by windtalker** [comment]
reopen and change severity to critical
