### ISSUE TITLE
the same primary row return multiple rows with different versions in fast scan mode

### ISSUE THREAD

**Issue by bestwoody** [pingcap/tiflash#7634]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

**Comment by SeaRise** [comment]
Please avoid adding non-public information such as `ONCALL-6266` and add some relevant information

**Comment by hongyunyan** [comment]
In fast scan mode, it matches expectation that the result contains the multi-version data.

**Comment by JaySon-Huang** [comment]
Update the doc to describe more details about the behavior of FastScan https://github.com/pingcap/docs-cn/pull/14190

**Comment by windtalker** [comment]
Close this issue since it is the expected behavior in fast mode.
