### ISSUE TITLE
Enhance log info when leaner read meet error

### ISSUE THREAD

**Issue by lilinghai** [pingcap/tiflash#7647]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

6 tiflash, 2 replica, stop a tiflash and always execute query with tiflash
raise 2 errors after stop a tiflash `Error 1105 (HY000): [FLASH:Coprocessor:BadRequest] Income key ranges is illegal for region: 326: (while doing learner read for table, logical table_id: 2593)`
### 4. What is your TiFlash version? (Required)
master

**Comment by windtalker** [comment]
The root cause is https://github.com/pingcap/tidb/issues/44622
