### ISSUE TITLE
The result of `upper()` and `lower()` is different with TiDB

### ISSUE THREAD

**Issue by Defined2014** [pingcap/tiflash#7695]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```
mysql> drop table t;
Query OK, 0 rows affected (0.34 sec)

mysql> create table t(a char(20));
Query OK, 0 rows affected (0.15 sec)

mysql> insert into t values ('𞤀');
Query OK, 1 row affected (0.01 sec)

mysql> ALTER TABLE t set tiflash replica 1;
Query OK, 0 rows affected (0.14 sec)

mysql> set @@session.tidb_isolation_read_engines = 'tiflash';
Query OK, 0 rows affected (0.00 sec)

mysql> select * from t where lower(a) = '𞤀';
+------+
| a    |
+------+
| 𞤀     |
+------+
1 row in set (0.07 sec)

mysql> set @@session.tidb_isolation_read_engines = 'tikv';
Query OK, 0 rows affected (0.01 sec)

mysql> select * from t where lower(a) = '𞤀';
Empty set (0.00 sec)
```

### 2. What did you expect to see? (Required)
```
Same as TiDB and TiKV
```

### 3. What did you see instead (Required)

```
Result not same
```

### 4. What is your TiFlash version? (Required)

2023-06-24 nightly

**Comment by Defined2014** [comment]
The root case is that the unicode version in `poco` is 7.0.0, which is different from golang's 13.0.0.

https://github.com/pocoproject/poco/blob/ead93baadf0b632d0563d66cc5e0c926b151816f/Foundation/include/Poco/Unicode.h#L88

https://github.com/golang/go/blob/e827d41c0a2ea392c117a790cdfed0022e419424/src/unicode/tables.go#L6

**Comment by windtalker** [comment]
Change the severity to major since it is a corner case, and we will investigate if TiFlash can upgrade the unicode version to 13.0.0

**Comment by windtalker** [comment]
> where lower(a) = '𞤀'

Actually, TiFlash translate the golang's implementation of toCase in
https://github.com/pingcap/tiflash/blob/57c0c57e91a1e95f2ff4a13597a2898409ce11de/dbms/src/Functions/CharUtil.h#L235

The different behavior in TiDB and TiFlash is caused by golang's upgrade.

**Comment by joey-yez** [comment]
The character in the case is from Adlam, one language in west africa. https://www.compart.com/en/unicode/U+1E900#UNC_DB
