### ISSUE TITLE
workload report “execute run failed, err execute query q22 failed Error 1105: other error for mpp stream: Poco::Exception. Code: 1000, e.code() = 2, e.displayText() = Exception: EstablishDisaggTask Failed4: Deadline Exceeded, e.what() = Exception”  run go-tpc ch

### ISSUE THREAD

**Issue by Lily2025** [pingcap/tiflash#7759]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
1、br restore data
2、run ch
"go-tpc ch run -D tpcc --host tc-tidb.endless-ha-test-tps-1815226-1-478 -P4000 --warehouses 2000 -T 32 --acThreads 1 --queries q22 --ignore-error '2013,1213,1105,1205,8022,8028,9004,9007,1062' --time 36000m --user root --password '' --interval '10s'

### 2. What did you expect to see? (Required)
no error

### 3. What did you see instead (Required)
workload always report “execute run failed, err execute query q22 failed Error 1105: other error for mpp stream: Poco::Exception. Code: 1000, e.code() = 2, e.displayText() = Exception: EstablishDisaggTask Failed4: Deadline Exceeded, e.what() = Exception” 

### 4. What is your TiFlash version? (Required)
git hash：f08e4d66ec09b2fb6ea727a23bc7956c15caae40

**Comment by JaySon-Huang** [comment]
We have added more detail logging and some timeout about this problem. Will dive deep into it if a similar issue happens again.

* https://github.com/pingcap/tiflash/pull/8795
* https://github.com/pingcap/tiflash/pull/8807
