### ISSUE TITLE
another tiflash_write node oom after inject one tiflash_write node failure for 50m and recover

### ISSUE THREAD

**Issue by Lily2025** [pingcap/tiflash#7761]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
1、run ch
go-tpc ch run -D tpcc --host tc-tidb.endless-ha-test-tps-1815226-1-478 -P4000 --warehouses 2000 -T 32 --acThreads 1 --queries q16 --ignore-error '2013,1213,1105,1205,8022,8028,9004,9007,1062' --time 36000m --user root --password '' --interval '10s'
2、inject one of  tiflash_write node failure for 50m
3、after 48m，one tiflash_write node oom and workload always report error as below：
    err execute query q16 failed Error 1105: other error for mpp stream: Poco::Exception. Code: 1000, e.code() = 15, e.displayText() = Exception: no alive tiflash, cannot dispatch BatchCopTask, e.what() = Exception

### 2. What did you expect to see? (Required)
no error report after 2m when fault injection
no oom

### 3. What did you see instead (Required)
![2edf829b-0d39-4904-afa8-baf8f194b862](https://github.com/pingcap/tiflash/assets/84712107/ca879f5a-fbf1-4f6f-b0d5-d8a7dcc3c5c8)
workload report “err execute query q16 failed Error 1105: other error for mpp stream: Poco::Exception. Code: 1000, e.code() = 15, e.displayText() = Exception: no alive tiflash, cannot dispatch BatchCopTask, e.what() = Exception” after inject one tiflash_write node failure for 50m

### 4. What is your TiFlash version? (Required)
git hash：f08e4d66ec09b2fb6ea727a23bc7956c15caae40

**Comment by JaySon-Huang** [comment]
Seems this bug is caused by
TiKV leader will **NOT** send `CompactLog` when one TiFlash write node is down. It leads to the number of RaftLog in the other TiFlash write node grows rapidly. It finally cause the TiFlash write node OOM cause by too many pages in UniPS.
