### ISSUE TITLE
TiFlash has less rows than TiKV

### ISSUE THREAD

**Issue by flowbehappy** [pingcap/tiflash#7762]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
A use report that TiFlash has less rows than TiKV.

The root cause is that  the range of some regions are in illegal format. For example:
table id: 283
start: 7480000000000001FF1B5F728000000000FF11BDC00000000000FA
end: 7480000000000001FF1B5F728000000000FF11BDC00000000000FB

![img_v2_25807fb2-a231-4b30-927e-895e33d2adcg](https://github.com/pingcap/tiflash/assets/2639319/2c72e75b-4567-439d-99bd-86f80ce5150d)

We don't know how the data is ingested into TiFlash. But we need to make some checks on TiFlash side to prevent data lost.

**Comment by breezewish** [comment]
Removed affect-6.6 ~ affect-7.1, since the check is already there for these versions.

**Comment by CalvinNeo** [comment]
It may panic like
```
Detected illegal region boundary:
```
