### ISSUE TITLE
workload report “execute query q6 failed Error 1105: other error for mpp stream: Poco::Exception. Code: 1000, e.code() = 2, e.displayText() = Exception: EstablishDisaggTask Failed4: Deadline Exceeded, e.what() = Exception” after inject one of tiflash write node network partition and recover

### ISSUE THREAD

**Issue by Lily2025** [pingcap/tiflash#7763]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
1、 run workload
    go-tpc ch run -D tpcc --host tc-tidb.endless-ha-test-tps-1815226-1-478 -P4000 --warehouses 2000 -T 32 --acThreads 1 --queries q6 --ignore-error '2013,1213,1105,1205,8022,8028,9004,9007,1062' --time 36000m --user root --password '' --interval '10s'
2、inject one of tiflash write node network partition
3、 after 10m ，recover fault

### 2. What did you expect to see? (Required)
o error report after 2m when fault injection

### 3. What did you see instead (Required)
after inject fault even if recovering the fault，workload always report error
execute query q6 failed Error 1105: other error for mpp stream: Poco::Exception. Code: 1000, e.code() = 2, e.displayText() = Exception: EstablishDisaggTask Failed4: Deadline Exceeded, e.what() = Exception

### 4. What is your TiFlash version? (Required)
git hash：f08e4d66ec09b2fb6ea727a23bc7956c15caae40

**Comment by JaySon-Huang** [comment]
Duplicated with https://github.com/pingcap/tiflash/issues/8806
Should be fixed by https://github.com/pingcap/tiflash/pull/8807 https://github.com/pingcap/tiflash/pull/8795
