### ISSUE TITLE
TiFlash may crash when illegal data is imported

### ISSUE THREAD

**Issue by breezewish** [pingcap/tiflash#7766]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

Import using lightning.

### 2. What did you expect to see? (Required)

TiFlash keep running.

### 3. What did you see instead (Required)

TiFlash may crash, when region range is illegal.

### 4. What is your TiFlash version? (Required)

master

**Comment by JaySon-Huang** [comment]
link https://github.com/pingcap/tiflash/issues/3099
