### ISSUE TITLE
Improve performance of IN type RS operator

### ISSUE THREAD

**Issue by elsa0520** [pingcap/tiflash#7781]
## Enhancement

Currently RS Operator of IN predicate type is too inefficient when matching min max index. 

As a result, although the filter is pushed down and the min max index matches to filter out a large number of packs and save a lot of IO, the performance of the overall table scan is slowed down due to the low execution efficiency of the RS operator.

For example
TPC-DS query 16

**If the filter push down and enable IN rsoperator**
Skipped packs: 8471
Skipped rows: 68622105
Time: 66ms

```
|                     │             └─TableFullScan_51         | 71997669.00 | 3375564  | mpp[tiflash] | table:cs1              | tiflash_task:{time:66ms, loops:54, threads:16}, tiflash_scan:{dtfile:{total_scanned_packs:415, total_skipped_packs:8471, total_scanned_rows:3375564, total_skipped_rows:68622105, total_rs_index_load_time: 1ms, total_read_time: 142ms}, total_create_snapshot_time: 0ms, total_local_region_num: 194, total_remote_region_num: 0}     | pushed down filter:empty, keep order:false, runtime filter:1[IN] -> tpcds50.catalog_sales.cs_ship_date_sk, 2[IN] -> tpcds50.catalog_sales.cs_ship_addr_sk, 3[IN] -> tpcds50.catalog_sales.cs_call_center_sk       | N/A     | N/A  |
```

However
**Less skipped packs**
Skipped packs: 181
Skipped rows: 1475258
Time: 39ms

```
|                     │             └─TableFullScan_51         | 71997669.00 | 71997669 | mpp[tiflash] | table:cs1              | tiflash_task:{time:39.1ms, loops:1155, threads:16}, tiflash_scan:{dtfile:{total_scanned_packs:8888, total_skipped_packs:181, total_scanned_rows:72014053, total_skipped_rows:1475258, total_rs_index_load_time: 9ms, total_read_time: 2678ms}, total_create_snapshot_time: 0ms, total_local_region_num: 194, total_remote_region_num: 0} | pushed down filter:empty, keep order:false
```

The less rows read **skipped packs from 181 to 8471** but the more time costs ** from 39ms to 66ms **

**The performance IN RS operator should be improved**

**Comment by Lloyd-Pottiger** [comment]
It root cause is not RSOperator, check the `total_rs_index_load_time`

```
total_rs_index_load_time: 1ms
```

```
total_rs_index_load_time: 9ms
```

**Comment by elsa0520** [comment]
Actually, the `equalCheck` of  IN operator can more quickly. 
Instead of comparing the values in one by one, we can compare all the values together.

The logic as following:
```
// compute min max and hash values
for (all in values) {
   // compute min max 
  // compute hash value
}

if (in_max < pack_min || in_min > pack_max) 
  {return none} 
else if (pack min = max and equal one one in value) 
  {return all} 
elsa {return some}
```

**Comment by Lloyd-Pottiger** [comment]
> Actually, the `equalCheck` of IN operator can more quickly. Instead of comparing the values in one by one, we can compare all the values together.
> 
> The logic as following:
> 
> ```
> // compute min max and hash values
> for (all in values) {
>    // compute min max 
>   // compute hash value
> }
> 
> if (in_max < pack_min || in_min > pack_max) 
>   {return none} 
> else if (pack min = max and equal one one in value) 
>   {return all} 
> elsa {return some}
> ```

Seems that can not handle the second case. 🤔 

```
    // values is sorted in ascending order
    //      min    max
    // ------|------|------
    //  | |                  <- values.back() < min || values.front() > max, return None
    //  |  |           |     <- for each v in values, v < min || v > max, return None
      |  |  |  |  |  |     <- have v in values, v >= min && v <= max, return Some
```
