### ISSUE TITLE
Functions that traverse the IProfilingBlockInputStream tree may have performance issues when the tree contains `SharedQueryBlockInputStream`

### ISSUE THREAD

**Issue by windtalker** [pingcap/tiflash#7810]
## Bug Report
The same issue as #4494
The root cause is when IProfilingBlockInputStream tree contains `SharedQueryBlockInputStream`, the tree is actually a DAG, and when traverse the DAG as a tree, it need much redundant traverse, at worst case, the time complexity become O(m^n), where n is the number of `SharedQueryBlockInputStream` in the DAG, m is the number of children for the tree node.
Currently, the functions that may have this problem inlcudes:
- `IProfilingBlockInputStream::setProcessListElement`
- `IProfilingBlockInputStream::setProgressCallback`

**Comment by SeaRise** [comment]
It looks like collectCPUTimeNsImpl won't have this problem because cpu_time_ns_collected is used in collectCPUTimeNs to avoid calling collectCPUTimeNsImpl repeatedly

**Comment by windtalker** [comment]
OK, I've update the issue description.

**Comment by yibin87** [comment]
Can we fix the issue by override these interfaces in SharedQueryBlockInputStream, and check if redundant ops?

**Comment by SeaRise** [comment]
> Can we fix the issue by override these interfaces in SharedQueryBlockInputStream, and check if redundant ops?

Because these two functions are useless in TiFlash, they can be omitted.
