### ISSUE TITLE
When the join key is a string, the join result may be incorrect under certain conditions

### ISSUE THREAD

**Issue by mengxin9014** [pingcap/tiflash#7834]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```sql
create table t (str char(32));
alter table t set tiflash replica 1;
insert into t values ("aaa"), ("aaa ");
select * from t a join t b on a.str =b.str;
```

### 2. What did you expect to see? (Required)
```sql
+------+------+
| str  | str  |
+------+------+
| aaa  | aaa  |
| aaa  | aaa  |
+------+------+
```

### 3. What did you see instead (Required)
```sql
+------+------+
| str  | str  |
+------+------+
| aaa  | aaa  |
| aaa  | aaa  |
| aaa  | aaa  |
| aaa  | aaa  |
+------+------+
```

### 4. What is your TiFlash version? (Required)
nightly

**Comment by xzhangxian1008** [comment]
MySQL has the same behaviour, so it's not a bug. I will close it.

**Comment by Lloyd-Pottiger** [comment]
Both MySQL and PostgreSQL have the same behaviour, so close this issue.
