### ISSUE TITLE
SQL failed because table is not created.

### ISSUE THREAD

**Issue by hongyunyan** [pingcap/tiflash#7846]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
1. add a failpoint in InterpreterCreateQuery::createTable before res->startup();
2. start a cluster and make the failpoint enabled.
3. ```drop table if exists test.t;create table test.t(a int);alter table test.t set tiflash replica 1;set session tidb_isolation_read_engines='tiflash'; select * from test.t;```
4. and run the sql ```set session tidb_isolation_read_engines='tiflash'; select * from test.t;``` in another seesion

### 2. What did you expect to see? (Required)
ERROR 1105 (HY000): other error for mpp stream: Code: 0, e.displayText() = DB::TiFlashException: Table 111 doesn't exist., e.what() = DB::TiFlashException,

### 3. What did you see instead (Required)
sql not return when failpoint enabled.

### 4. What is your TiFlash version? (Required)
master

**Comment by JaySon-Huang** [comment]
change the severity from critical to major as the error will automatically disappear if user retry the query
