### ISSUE TITLE
Enhance the memory usage of mark cache and minmax index cache

### ISSUE THREAD

**Issue by hongyunyan** [pingcap/tiflash#8050]
## Enhancement
Currently, in minmax_index_cache and mark_cache we use the long file name as the key, which occupy much memory, especially when the memory cost of value is small(with a little pack number).

Besides, we statistic memory overhead of mark cache size, but only counted about the memory cost of MarksInCompressedFile, but not consider the memory cost of keys, and the structual cost of LRUCache, which cause a misleading of memory usage. 

Thus, we should optimize the memory usage of these caches, and make a better memory statistical  for these memory usage of caches.

**Comment by JaySon-Huang** [comment]
Change the type from enhancement to bug because it leads to much more memory consumption than expected under some senario
