### ISSUE TITLE
Memory usage for data computing is not accurate in MemoryTracker

### ISSUE THREAD

**Issue by Lloyd-Pottiger** [pingcap/tiflash#8119]
## Bug Report

<img width="1273" alt="image" src="https://github.com/pingcap/tiflash/assets/60744015/0fa83b67-386a-4a81-ab85-97a88308ac01">

there are only 40GiB memory left for query, but the peak memory usage is 100+GiB, which is impossible.

**Comment by jebter** [comment]
@wuhuizuo PTAL

**Comment by Lloyd-Pottiger** [comment]
similar to https://github.com/pingcap/tiflash/issues/8128, closed
