### ISSUE TITLE
tiflash-v7.1.1-存算分离

### ISSUE THREAD

**Issue by lee1988well** [pingcap/tiflash#8150]
## Bug Report

[2023/09/26 01:48:55.096 +00:00] [ERROR] [DiagnosticsService.cpp:57] 
["TiFlashRaftProxyHelper is null, `DiagnosticsService::server_info` is useless"] 
[source=DiagnosticsService] [thread_id=351]

日志中一直报这个错误；
目前只有tiflash计算节点上有报错信息；
表都是重新同步的，状态都是可用；
在PD节点上有告警
[grpclog.go:60] [“transport: http2Server.HandleStreams failed to read frame: read tcp 10.60.71.229:2379->10.60.76.129:47208: read: connection reset by peer”]

**Comment by JaySon-Huang** [comment]
The disagg architecture is not stable in v7.1 versions. If you want to have a try, you can deploy the nightly version or wait for the coming v7.4 version

**Comment by JaySon-Huang** [comment]
I will close it, please feel free to reopen the issue if you have any more questions.
