### ISSUE TITLE
[Dynamic Regions] AVAILABLE is always 0 when query information_schema.tiflash_replica after br restore tiflash data with 2 replicas

### ISSUE THREAD

**Issue by Lily2025** [pingcap/tiflash#8163]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
1、/br restore db --send-credentials-to-tikv=true --db tpcc --pd http://tc-pd.endless-ha-test-htap-tps-2880160-1-720:2379/ --storage s3://nfs/tiflash/ch-2k-flash2-collation --s3.endpoint http://minio.pingcap.net:9000/ --check-requirements=false
2、select * from information_schema.tiflash_replica
[{"AVAILABLE":"0","LOCATION_LABELS":"","PROGRESS":"0","REPLICA_COUNT":"2","TABLE_ID":"2759","TABLE_NAME":"supplier","TABLE_SCHEMA":"tpcc"},{"AVAILABLE":"0","LOCATION_LABELS":"","PROGRESS":"0","REPLICA_COUNT":"2","TABLE_ID":"2725","TABLE_NAME":"warehouse","TABLE_SCHEMA":"tpcc"},{"AVAILABLE":"0","LOCATION_LABELS":"","PROGRESS":"0","REPLICA_COUNT":"2","TABLE_ID":"2735","TABLE_NAME":"orders","TABLE_SCHEMA":"tpcc"},{"AVAILABLE":"0","LOCATION_LABELS":"","PROGRESS":"0","REPLICA_COUNT":"2","TABLE_ID":"2727","TABLE_NAME":"district","TABLE_SCHEMA":"tpcc"},{"AVAILABLE":"0","LOCATION_LABELS":"","PROGRESS":"0","REPLICA_COUNT":"2","TABLE_ID":"2737","TABLE_NAME":"order_line","TABLE_SCHEMA":"tpcc"},{"AVAILABLE":"0","LOCATION_LABELS":"","PROGRESS":"0","REPLICA_COUNT":"2","TABLE_ID":"2729","TABLE_NAME":"customer","TABLE_SCHEMA":"tpcc"},{"AVAILABLE":"0","LOCATION_LABELS":"","PROGRESS":"0","REPLICA_COUNT":"2","TABLE_ID":"2731","TABLE_NAME":"history","TABLE_SCHEMA":"tpcc"},{"AVAILABLE":"0","LOCATION_LABELS":"","PROGRESS":"0","REPLICA_COUNT":"2","TABLE_ID":"2755","TABLE_NAME":"nation","TABLE_SCHEMA":"tpcc"},{"AVAILABLE":"0","LOCATION_LABELS":"","PROGRESS":"0","REPLICA_COUNT":"2","TABLE_ID":"2739","TABLE_NAME":"stock","TABLE_SCHEMA":"tpcc"},{"AVAILABLE":"0","LOCATION_LABELS":"","PROGRESS":"0","REPLICA_COUNT":"2","TABLE_ID":"2741","TABLE_NAME":"item","TABLE_SCHEMA":"tpcc"},{"AVAILABLE":"0","LOCATION_LABELS":"","PROGRESS":"0","REPLICA_COUNT":"2","TABLE_ID":"2733","TABLE_NAME":"new_order","TABLE_SCHEMA":"tpcc"},{"AVAILABLE":"0","LOCATION_LABELS":"","PROGRESS":"0","REPLICA_COUNT":"2","TABLE_ID":"2757","TABLE_NAME":"region","TABLE_SCHEMA":"tpcc"}]"]

### 2. What did you expect to see? (Required
AVAILABLE is 1 after br restore tiflash data with 2 replicas

### 3. What did you see instead (Required)
AVAILABLE is always 0 when query information_schema.tiflash_replica after br restore tiflash data with 2 replicas

### 4. What is your TiFlash version? (Required)
git hash：6918946196d8bdb4fc32ebf535b8765f4ed05658

**Comment by JaySon-Huang** [comment]
Close as the "Dynamic Region" aka "Partitioned Raft KV" has been stopped for a long time
