### ISSUE TITLE
LAC::consumeResource may introduce performance regression

### ISSUE THREAD

**Issue by guo-shaoge** [pingcap/tiflash#8270]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

https://github.com/pingcap/tiflash/blob/master/dbms/src/Storages/DeltaMerge/SkippableBlockInputStream.h#L224 and https://github.com/pingcap/tiflash/blob/master/dbms/src/Storages/DeltaMerge/ColumnFile/ColumnFileSetReader.cpp#L194 will consume resource for storage layer, but there are situations that the calling of `LAC::consumeResource` are too frequent, which may introduce significant regression.

**Comment by Yui-Song** [comment]
As the issue causes a 17%- 31% performance regression in CH benchmark, which will block the release of v7.5.0. Adjust its severity to critical.
/remove-severity major
/severity critical
