### ISSUE TITLE
"number of enum overflow enum boundary" TiFlash does not handle the case of SQL_MODE without STRICT_TRANS_TABLES

### ISSUE THREAD

**Issue by Mini256** [pingcap/tiflash#8311]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```sql
CREATE TABLE `t1` (
  `id` bigint(20) NOT NULL AUTO_RANDOM,
  `type` enum('A','B') DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

-- Notice: Rmove `STRICT_TRANS_TABLES` flag allow insert invalid value.
SET SESSION SQL_MODE = 'ONLY_FULL_GROUP_BY,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION';

-- Insert a valid value, TiDB will not throw a error, but filled in with a blank value.
INSERT INTO t1(type) VALUES('C');

ALTER TABLE t1 SET TIFLASH REPLICA 1;

-- Error
SELECT /*+ READ_FROM_STORAGE(tiflash[t1]) */ COUNT(DISTINCT type) FROM t1;
```

### 2. What did you expect to see? (Required)

Work well like TiKV storage engine?

### 3. What did you see instead (Required)

Source of the issue:

https://ask.pingcap.com/t/error-1105-hy000-flashinternal-number-of-enum-overflow-enum-boundary/750

Encountered an error:

```
ERROR 1105 (HY000): [FLASH:Coprocessor:Internal] number of enum overflow enum boundary
```

### 4. What is your TiFlash version? (Required)

v7.1.1

**Comment by Lloyd-Pottiger** [comment]
https://github.com/pingcap/tiflash/blob/70c4bd055d790e30f178a62b40befa969f2b38f3/dbms/src/Flash/Coprocessor/ArrowColCodec.cpp#L343

maybe we should allow `enum_value == 0`?

**Comment by zanmato1984** [comment]
Adjusting severity.

**Comment by chaitairpay** [comment]
Hello @zanmato1984 

Is this issue resolved ? When it will be available in community version ?
