### ISSUE TITLE
Stopwatch::elapsedFromLastTime may return negative value

### ISSUE THREAD

**Issue by guo-shaoge** [pingcap/tiflash#8336]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
test pr: https://github.com/pingcap/tiflash/pull/8335/files

You can see the  the argument of `inc_value` of function `ResourceControlQueue::updateStatistics(inc_value)` is -1, which is unexpected. Because `inc_value` means the cpu time of a pipeline tasks used.
![Oy9qTM5geI](https://github.com/pingcap/tiflash/assets/7493273/682decc0-bd9d-4696-bb18-a34d5398e664)

**Comment by JaySon-Huang** [comment]
The function is added by https://github.com/pingcap/tiflash/pull/4537 since v6.1
