### ISSUE TITLE
Spill filename too long error

### ISSUE THREAD

**Issue by yibin87** [pingcap/tiflash#8399]
other error for mpp stream: Code: 0, e.displayText() = DB::Exception: Failed to spill blocks to disk for file /data0/tmp/tmp_MPP_gather_id__gather_id_1__query_
ts_1700522319105637023__local_query_id_13__server_id_1453__start_ts_445781716263239681__resource_group__default__conn_id__3047162128__conn_alias____task_id_5__Aggregation_HashAgg_80
_AggregationBuild_HashAgg_80_aggregation_partition_0_1749, error: Code: 76, e.displayText() = DB::Exception: Cannot open file /data0/tmp/tmp_MPP_gather_id__gather_id_1__query_ts_170
0522319105637023__local_query_id_13__server_id_1453__start_ts_445781716263239681__resource_group__default__conn_id__3047162128__conn_alias____task_id_5__Aggregation_HashAgg_80_Aggre
gationBuild_HashAgg_80_aggregation_partition_0_1749, errno: 36, strerror: File name too long, e.what() = DB::Exception, e.what() = DB::Exception

**Comment by JaySon-Huang** [comment]
I think this issue may also affects release-7.5? @windtalker

**Comment by windtalker** [comment]
It should not affects release-7.5 because the related pr is https://github.com/pingcap/tiflash/pull/8348
