### ISSUE TITLE
TiFlash may be OOM when scanning many partition tables with stream model

### ISSUE THREAD

**Issue by gengliqi** [pingcap/tiflash#8505]
## Enhancement

https://github.com/pingcap/tiflash/pull/4988 was intended to improve the performance of the partition table. However, it also introduces an issue that many read pools of different partition tables will be running simultaneously, which may lead to TiFlash OOM.

**Comment by JaySon-Huang** [comment]
> many read pools of different partition tables will be running simultaneously, which may lead to TiFlash OOM

The reason why TiFlash OOM should related to https://github.com/pingcap/tiflash/issues/8564
