### ISSUE TITLE
all tiflash compute crash when kill one of tiflash wn

### ISSUE THREAD

**Issue by Lily2025** [pingcap/tiflash#8515]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
1、run ch
2、 kill one of tiflash wn （tc-tiflash-1）

### 2. What did you expect to see? (Required)
no crash

### 3. What did you see instead (Required)
all tiflash compute crash when kill one of tiflash wn

![img_v3_0264_1440726f-45dc-435b-9bfc-2bba81a4569g](https://github.com/pingcap/tiflash/assets/84712107/e8fc61a3-9276-42f1-a5e1-4228df593745)

### 4. What is your TiFlash version? (Required)
git hash：6f4deccd645ecdf9cc341c6e1bf4fcc3a1bbd55b

**Comment by JaySon-Huang** [comment]
does not affects 7.5
