### ISSUE TITLE
tiflash cn always crash after kill this tiflash cn

### ISSUE THREAD

**Issue by Lily2025** [pingcap/tiflash#8589]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
1、run ch
2、 kill one of tiflash cn （secondary-tc-tiflash-0）

### 2. What did you expect to see? (Required)
no crash

### 3. What did you see instead (Required)
tiflash cn always crash after kill this tiflash cn
![image](https://github.com/pingcap/tiflash/assets/84712107/7ba76ed0-eef0-4546-8f82-f984c1bdbb15)
![img_v3_026g_3616ccb9-c575-4318-8ae7-6355a5df750g](https://github.com/pingcap/tiflash/assets/84712107/43262c21-71e9-4223-9ea6-19f7fb7cc11b)

[2023/12/26 15:05:00.453 +08:00] [FATAL] [[config.rs:437](http://config.rs:437/)] ["invalid configuration: Cannot find raft data set."] [thread_id=0x5]

### 4. What is your TiFlash version? (Required)
git hash：963b1e352bfa3aa98b91fb83338d75533f76e76e

**Comment by SeaRise** [comment]
Will it related to https://github.com/pingcap/tiflash/issues/8550?
/cc @guo-shaoge

**Comment by JaySon-Huang** [comment]
reopen because it happens when upgrade from v7.5 to master @CalvinNeo
