### ISSUE TITLE
`AsyncTasksTest.AsyncTasksCommon` may hangs

### ISSUE THREAD

**Issue by JaySon-Huang** [pingcap/tiflash#8765]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```
./dbms/gtests_dbms --gtest_filter='*AsyncTasksCommon*' --gtest_repeat=1000
```

### 2. What did you expect to see? (Required)
The case successfully exit

### 3. What did you see instead (Required)
Sometime the case hangs forever

### 4. What is your TiFlash version? (Required)
master

**Comment by CalvinNeo** [comment]
We have this test to make sure a task could be canceled. However, there is a rare case that a task could actually finish.
This is because the task itself can finish before the main loop sleeps for 100ms.
