### ISSUE TITLE
TiFlash result is wrong

### ISSUE THREAD

**Issue by lilinghai** [pingcap/tiflash#8904]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

prepare some data
do random dml and check `select count(*)` using tiflash and tikv
upgrade from 6.17 to master, when one tiflash version is 6.1.7 and another is master, query from tiflash is wrong
```
mysql> begin;
Query OK, 0 rows affected (0.04 sec)

mysql> set tidb_isolation_read_engines='tiflash';
Query OK, 0 rows affected (0.03 sec)

mysql> select count(*) from t;
+----------+
| count(*) |
+----------+
| 15284754 |
+----------+
1 row in set (0.17 sec)

mysql> set tidb_isolation_read_engines='tikv';
Query OK, 0 rows affected (0.03 sec)

mysql> select count(*) from t;
+----------+
| count(*) |
+----------+
| 16117328 |
+----------+
1 row in set (0.15 sec)

mysql> commit;
Query OK, 0 rows affected (0.04 sec)
```

**Comment by JaySon-Huang** [comment]
Confirm it is introduced by https://github.com/pingcap/tiflash/pull/8909. Has been revert in the master
