### ISSUE TITLE
Queries with no segment get stuck

### ISSUE THREAD

**Issue by JinheLin** [pingcap/tiflash#9108]
```
["Segment read tasks build done, cost=0ms sorted_ranges=3 n_tasks_before_split=0 n_tasks_final=0 n_ranges_final=0"]

["Added, pool_id=47739 table_id=2907 block_slots=3 segment_count=0 pool_count=1 cost=2330ns do_add_cost=2120ns"]
```

**Comment by JaySon-Huang** [comment]
Note: The issue is fixed by previous PRs
* master branch: https://github.com/pingcap/tiflash/pull/9027
* release-8.1 branch: https://github.com/pingcap/tiflash/pull/9111
* release-7.5 branch: https://github.com/pingcap/tiflash/pull/9026
