### ISSUE TITLE
Grpc error after TiFlash restarts for a while

### ISSUE THREAD

**Issue by yibin87** [pingcap/tiflash#9159]
After https://github.com/pingcap/tidb/pull/53698 which updates several dependecies including grpc from 1.63.2 to 1.64, several tiflash regression test failed constantly due to GRPC error:
rpc error: code = DeadlineExceeded desc = received context error while waiting for new LB policy update: context deadline exceeded
rpc error: code = Unavailable desc = connection error: desc = \\\"transport: Error while dialing: dial tcp 10.200.86.26:3930: i/o timeout

These errors always happen after TiFlash retarts for a while.

**Comment by JaySon-Huang** [comment]
@yibin87 Can we close this issue?

**Comment by yibin87** [comment]
Yeah, fix already.

**Comment by ekexium** [comment]
Will this issue block us from upgrading grpc forever?

**Comment by yibin87** [comment]
> Will this issue block us from upgrading grpc forever?

Next time we want to upgrade grpc, we need to analyze and fix this tiflash issue.

**Comment by 3AceShowHand** [comment]
Is there any update, what's the root cause behind it, is bugs comes from gRPC or unstable case comes from tiflash?
