### ISSUE TITLE
The actows information of the mpp operator part is all 0

### ISSUE THREAD

**Issue by Chad20N13** [pingcap/tiflash#9303]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```
*************************** 1. row ***************************
       Table: orders
Create Table: CREATE TABLE `orders` (
  `id` bigint(20) NOT NULL,
  `book_id` bigint(20) NOT NULL,
  `user_id` bigint(20) NOT NULL,
  `quality` tinyint(4) NOT NULL,
  `ordered_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`) /*T![clustered_index] CLUSTERED */,
  KEY `orders_book_id_idx` (`book_id`),
  KEY `idx_ordered_at` (`ordered_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;


select /*+ read_from_storage(tiflash[orders]) */ date_format(concat(date(ordered_at),
                          ' ',
                          HOUR(ordered_at)),
                   '%Y-%m-%d %H') as CREATED_DATETIME,
       count(if((book_id is not null) AND
                (user_id IS NOT NULL) AND
                (quality is not null) AND
                (user_id <> 1),
                ID,
                NULL)) AS IDOS_DS_TI_BLK_LIST_REC_BenDiHeiMingDanjuJueLiang_jianfuzhang
  from orders
 where (ordered_at >= '2010-08-08 20:00:00')
   and (ordered_at < '2020-08-09 20:00:00')
 group by date_format(concat(date(ordered_at),
                             ' ',
                             HOUR(ordered_at)),
                      '%Y-%m-%d %H') limit 1000;
```

![img_v3_02dj_ef70cb91-c9a0-442e-a653-c91e16c6fa5g](https://github.com/user-attachments/assets/9ba2bc9f-df3e-42c6-b1aa-c2e38b1e9b51)

![img_v3_02dj_79c5d2c6-f1c0-4e26-b95a-aede88dc3fdg](https://github.com/user-attachments/assets/6a575b92-09c6-4307-9413-223a40b2dc93)

### 2. What did you expect to see? (Required)

The actows information of the mpp operator part is all 0

### 3. What did you see instead (Required)

The actows information of the mpp operator part is real , no 0.

### 4. What is your TiFlash version? (Required)

```
TiFlash
Release Version: v6.5.3
Edition:         Community
Git Commit Hash: e63e24991079fff1e5afe03e859f743cbb6cf4a7
Git Branch:      heads/refs/tags/v6.5.3
UTC Build Time:  2023-06-05 07:21:11
Enable Features: jemalloc sm4(GmSSL) avx2 avx512 unwind thinlto
Profile:         RELWITHDEBINFO

Raft Proxy
Git Commit Hash:   37eb1f1a09576a984f07a04fe7d9f2373935657a
Git Commit Branch: HEAD
UTC Build Time:    2023-06-05 07:28:04
Rust Version:      rustc 1.67.0-nightly (96ddd32c4 2022-11-14)
Storage Engine:    tiflash
Prometheus Prefix: tiflash_proxy_
Profile:           release
```

**Comment by Chad20N13** [comment]
MySQL [chad]> select /*+ read_from_storage(tiflash[orders]) */ count(*) from  orders
    ->  where (ordered_at >= '2010-08-08 20:00:00')
    ->    and (ordered_at < '2020-08-09 20:00:00');
+----------+
| count(*) |
+----------+
| 68102870 |
+----------+
1 row in set (0.38 sec)

**Comment by Chad20N13** [comment]
MySQL [chad]> desc orders;
+------------+------------+------+------+-------------------+-----------------------------------------------+
| Field      | Type       | Null | Key  | Default           | Extra                                         |
+------------+------------+------+------+-------------------+-----------------------------------------------+
| id         | bigint(20) | NO   | PRI  | NULL              |                                               |
| book_id    | bigint(20) | NO   | MUL  | NULL              |                                               |
| user_id    | bigint(20) | NO   |      | NULL              |                                               |
| quality    | tinyint(4) | NO   |      | NULL              |                                               |
| ordered_at | datetime   | NO   | MUL  | CURRENT_TIMESTAMP | DEFAULT_GENERATED on update CURRENT_TIMESTAMP |
+------------+------------+------+------+-------------------+-----------------------------------------------+
5 rows in set (0.01 sec)

**Comment by Chad20N13** [comment]
MySQL [chad]> explain analyze select /*+ read_from_storage(tiflash[orders]) */ date_format(concat(date(ordered_at),
    ->                           ' ',
    ->                           HOUR(ordered_at)),
    ->                    '%Y-%m-%d %H') as CREATED_DATETIME,
    ->        count(if((book_id is not null) AND
    ->                 (user_id IS NOT NULL) AND
    ->                 (quality is not null) AND
    ->                 (user_id <> 1),
    ->                 ID,
    ->                 NULL)) AS IDOS_DS_TI_BLK_LIST_REC_BenDiHeiMingDanjuJueLiang_jianfuzhang
    ->   from orders
    ->  where (ordered_at >= '2010-08-08 20:00:00')
    ->    and (ordered_at < '2020-08-09 20:00:00')
    ->  group by date_format(concat(date(ordered_at),
    ->                              ' ',
    ->                              HOUR(ordered_at)),
    ->                       '%Y-%m-%d %H') limit 1000;
+--------------------------------------------+--------------+---------+--------------+---------------+--------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------+------+
| id                                         | estRows      | actRows | task         | access object | execution info                                                                       | operator info                                                                                                                                                                                                                                                                                  | memory   | disk |
+--------------------------------------------+--------------+---------+--------------+---------------+--------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------+------+
| Projection_8                               | 1000.00      | 1000    | root         |               | time:11.5s, loops:2, Concurrency:OFF                                                 | date_format(cast(concat(cast(date(chad.orders.ordered_at), var_string(10)),  , cast(hour(cast(chad.orders.ordered_at, time)), var_string(20))), datetime(6) BINARY), %Y-%m-%d %H)->Column#7, Column#6                                                                                          | 16.5 KB  | N/A  |
| └─Limit_11                                 | 1000.00      | 1000    | root         |               | time:11.5s, loops:2                                                                  | offset:0, count:1000                                                                                                                                                                                                                                                                           | N/A      | N/A  |
|   └─TableReader_32                         | 1000.00      | 1024    | root         |               | time:11.5s, loops:1, cop_task: {num: 1, max: 0s, proc_keys: 0, copr_cache: disabled} | data:ExchangeSender_31                                                                                                                                                                                                                                                                         | 686.3 KB | N/A  |
|     └─ExchangeSender_31                    | 1000.00      | 0       | mpp[tiflash] |               |                                                                                      | ExchangeType: PassThrough                                                                                                                                                                                                                                                                      | N/A      | N/A  |
|       └─Projection_27                      | 1000.00      | 0       | mpp[tiflash] |               |                                                                                      | Column#6, chad.orders.ordered_at                                                                                                                                                                                                                                                               | N/A      | N/A  |
|         └─HashAgg_28                       | 1000.00      | 0       | mpp[tiflash] |               |                                                                                      | group by:Column#12, funcs:sum(Column#13)->Column#6, funcs:firstrow(Column#14)->chad.orders.ordered_at                                                                                                                                                                                          | N/A      | N/A  |
|           └─ExchangeReceiver_30            | 1000.00      | 0       | mpp[tiflash] |               |                                                                                      |                                                                                                                                                                                                                                                                                                | N/A      | N/A  |
|             └─ExchangeSender_29            | 1000.00      | 0       | mpp[tiflash] |               |                                                                                      | ExchangeType: HashPartition, Hash Cols: [name: Column#12, collate: utf8mb4_general_ci]                                                                                                                                                                                                         | N/A      | N/A  |
|               └─HashAgg_16                 | 1000.00      | 0       | mpp[tiflash] |               |                                                                                      | group by:Column#23, funcs:count(Column#21)->Column#13, funcs:firstrow(Column#22)->Column#14                                                                                                                                                                                                    | N/A      | N/A  |
|                 └─Projection_44            | 68288170.06  | 0       | mpp[tiflash] |               |                                                                                      | if(and(1, ne(chad.orders.user_id, 1)), chad.orders.id, <nil>)->Column#21, chad.orders.ordered_at, date_format(cast(concat(cast(date(chad.orders.ordered_at), var_string(10)),  , cast(hour(cast(chad.orders.ordered_at, time)), var_string(20))), datetime(6) BINARY), %Y-%m-%d %H)->Column#23 | N/A      | N/A  |
|                   └─Selection_26           | 68288170.06  | 0       | mpp[tiflash] |               |                                                                                      | ge(chad.orders.ordered_at, 2010-08-08 20:00:00.000000), lt(chad.orders.ordered_at, 2020-08-09 20:00:00.000000)                                                                                                                                                                                 | N/A      | N/A  |
|                     └─TableFullScan_25     | 100000000.00 | 0       | mpp[tiflash] | table:orders  |                                                                                      | keep order:false                                                                                                                                                                                                                                                                               | N/A      | N/A  |
+--------------------------------------------+--------------+---------+--------------+---------------+--------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------+------+
12 rows in set (11.49 sec)

**Comment by Lloyd-Pottiger** [comment]
An known issue: https://github.com/pingcap/tidb/issues/37047

**Comment by Lloyd-Pottiger** [comment]
Duplicate with https://github.com/pingcap/tidb/issues/37047, so I will close this issue. If you have other comments, posting them here is still welcome.
