### ISSUE TITLE
DB::CompressionCodecFactory::getStaticCodec(const CompressionSetting &): Assertion `inserted' failed

### ISSUE THREAD

**Issue by JinheLin** [pingcap/tiflash#9336]
### Error
```
gtests_dbms: /home/jenkins/agent/workspace/tiflash-build-common/tiflash/dbms/src/IO/Compression/CompressionCodecFactory.cpp:97: static CompressionCodecPtr DB::CompressionCodecFactory::getStaticCodec(const CompressionSetting &): Assertion `inserted' failed.
```

https://github.com/pingcap/tiflash/blob/5500b35dfc3c5b317d895cf3eae244bcc6f3a76a/dbms/src/IO/Compression/CompressionCodecFactory.cpp#L81-L99

1. Two threads with the same `level` acquire shared lock of `lz4_mutex` and read `lz4_map` concurrently and both failed because codec of `level` not exist.
2. Thread1 acquire unique lock of `lz4_mutex`, insert codec of `level` and `assert(inserted)` successfully.
3. Thread2 acquire unique lock of `lz4_mutex`, but insert codec of `level` failed, and `assert(inserted)` will crash the process in debug mode.

**Comment by Lloyd-Pottiger** [comment]
I have fixed this in https://github.com/pingcap/tiflash/pull/9312.

> Can we just create a static object when the server start? @Lloyd-Pottiger

No, `dt_compression_level` needs to be dynamically changeable.
