### ISSUE TITLE
query count(*) failed

### ISSUE THREAD

**Issue by giant-panda666** [pingcap/tiflash#9472]
A table stored in TiFlash, using this query sometimes works, sometimes not.
![image](https://github.com/user-attachments/assets/d1100927-f140-411d-bc7b-fe56f12151e8)
![image](https://github.com/user-attachments/assets/6b7a109d-1180-486d-8bec-be36b0be8dc6)

**Comment by JaySon-Huang** [comment]
Hi @giant-panda666, thank you for pointing out that such an issue exists. Can you provide more information? For example: 
* the tidb cluster version
* the related error message contains check failure logging in tiflash.log

**Comment by giant-panda666** [comment]
1. tidb cluster version is v7.5.2 deployed by tidb operator on k8s.
2. 
[logs.txt](https://github.com/user-attachments/files/17157622/logs.txt)

**Comment by Lloyd-Pottiger** [comment]
@giant-panda666 The following is a workaround:

```sql
set tidb_opt_enable_late_materialization = off; <query>; set tidb_opt_enable_late_materialization = on;
```

Could you please provide the table schema?

**Comment by giant-panda666** [comment]
> @giant-panda666 The following is a workaround:
> 
> ```sql
> set tidb_opt_enable_late_materialization = off; <query>; set tidb_opt_enable_late_materialization = on;
> ```
> 
> Could you please provide the table schema?

The table structure contains sensitive data. Can I obfuscate the field names and enum values before providing them? For example, I can rename the ‘price’ field to ‘a’. Also, could you explain why disabling late materialization can temporarily resolve this issue?

**Comment by Lloyd-Pottiger** [comment]
> The table structure contains sensitive data. Can I obfuscate the field names and enum values before providing them? For example, I can rename the ‘price’ field to ‘a’. 

Yes.

> Also, could you explain why disabling tidb_opt_enable_late_materialization can temporarily resolve this issue?

Only late materialization will call `hstackBlocks`.

**Comment by giant-panda666** [comment]
> > The table structure contains sensitive data. Can I obfuscate the field names and enum values before providing them? For example, I can rename the ‘price’ field to ‘a’.
> 
> Yes.

CREATE TABLE `separate_order` (
  `id` bigint(20) unsigned NOT NULL,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `c0` enum('DEFAULT','E1','E2','E3','E4','E5','E6') NOT NULL DEFAULT 'DEFAULT',
  `c1` bigint(20) unsigned NOT NULL DEFAULT '0' ,
  `c2` tinyint(4) NOT NULL DEFAULT '0',
  `c3` bigint(20) unsigned NOT NULL DEFAULT '0',
  `c4` bigint(20) unsigned NOT NULL DEFAULT '0',
  `c5` enum('DEFAULT','E1','E2','E3','E4','E5','E6','E6') NOT NULL DEFAULT 'DEFAULT',
  `c6` bigint(20) unsigned NOT NULL DEFAULT '0',
  `c7` varchar(512) NOT NULL DEFAULT '',
  `c8` varchar(512) NOT NULL DEFAULT '',
  `c9` enum('DEFAULT','E1','E2','E3','E4','E5','E6','E7','E8','E9') NOT NULL DEFAULT 'DEFAULT',
  `c10` bigint(20) unsigned NOT NULL DEFAULT '0',
  `c11` enum('DEFAULT','BALANCE','WX_MCH','GLOBAL_DEPOSIT_ACCOUNT') NOT NULL DEFAULT 'DEFAULT',
  `c12` timestamp NULL DEFAULT NULL,
  `c13` bigint(20) unsigned NOT NULL DEFAULT '0',
  `c14` timestamp NULL DEFAULT NULL ,
  `c15` decimal(20,4) NOT NULL DEFAULT '0.0000',
  `c16` decimal(20,4) NOT NULL DEFAULT '0.0000',
  `c17` decimal(20,4) NOT NULL DEFAULT '0.0000',
  `c18` enum('E0','E1','E2','E3','E4','E5','E6','E7','E8') NOT NULL DEFAULT 'E0',
  `c19` int(11) NOT NULL DEFAULT '0',
  `c20` varchar(1024) NOT NULL DEFAULT '',
  `c21` varchar(256) NOT NULL DEFAULT '',
  `c22` smallint(5) unsigned NOT NULL DEFAULT '0',
  `c23` bigint(20) unsigned NOT NULL DEFAULT '0',
  `c24` bigint(20) unsigned NOT NULL DEFAULT '0',
  `c25` bigint(20) unsigned NOT NULL DEFAULT '0',
  `c26` enum('DEFAULT','E1','E2') NOT NULL DEFAULT 'DEFAULT',
  `c27` enum('DEFAULT','E1','E2') NOT NULL DEFAULT 'DEFAULT',
  `c28` enum('DEFAULT','E1','E2') NOT NULL DEFAULT 'DEFAULT',
  `c29` enum('DEFAULT','E1','E2') NOT NULL DEFAULT 'DEFAULT',
  PRIMARY KEY (`id`) /*T![clustered_index] NONCLUSTERED */,
  KEY `idx_c1` (`c1`),
  KEY `idx_c10` (`c10`),
  KEY `idx_c13` (`c13`),
  KEY `idx_created_at` (`created_at`),
  KEY `idx_updated_at` (`updated_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin

**Comment by Lloyd-Pottiger** [comment]
@giant-panda666 Thanks, you may also need to transform the query.

**Comment by giant-panda666** [comment]
> @giant-panda666 Thanks, you may also need to transform the query.

SELECT   COUNT(*) FROM   `separate_order` WHERE   `c18` = "E7"   AND `c5` = "E4"   AND `c9` = "E5"   AND `c12` IS NULL   AND `updated_at` > date_add(curdate(), INTERVAL - 2 day);

**Comment by Lloyd-Pottiger** [comment]
Has fixed by https://github.com/pingcap/tiflash/pull/9361

**Comment by giant-panda666** [comment]
So updating to [v7.5.3](https://github.com/pingcap/tiflash/releases/tag/v7.5.3) will be ok?

**Comment by Lloyd-Pottiger** [comment]
> So updating to [v7.5.3](https://github.com/pingcap/tiflash/releases/tag/v7.5.3) will be ok?

Sorry, I made a mistake, I am still working on it.

**Comment by giant-panda666** [comment]
It's ok, looking forward to the next version release. Thank you!
