### ISSUE TITLE
Simplify compile toolchain and dependencies or offer some options to control it?

### ISSUE THREAD

**Issue by sumory** [pingcap/tiflash#9502]
When I use a specified version of llvm to compile tiflash (our compile env for production: debian10+llvm16+gcc10 c ++ lib), I find it very difficult, especially when I need to link different versions of glibc, the situation becomes more complicated.

In addition, tiflash has a huge set of third-party dependencies, which exacerbates the impact of compile issues. For rapid development needs, it seems unnecessary to introduce so many dependencies during the compile phase (such as AWS-related libraries?)

**Comment by CalvinNeo** [comment]
Is it helpful if you try to create a container to build TiFlash?
NIT and FYI: AWS related libraries are related to disaggregated TiFlash in which you can deploy TiFlash in seperated Compute Node and Storage Node.

**Comment by JaySon-Huang** [comment]
Hi @sumory ,

For the compile environment, there are two ways to get a suitable compile toolchain. One is to build a Docker image. You can try to build a Docker image according to the docker files in the [release-centos7-llvm](/release-centos7-llvm) directory. Or you can try to build a toolchain in the host machine using the script in [release-centos7-llvm/env](/release-centos7-llvm/env). We use the later one for development and the Docker image for release build. There are README files in those directories.

**Comment by JaySon-Huang** [comment]
For rapid development needs, some features may not be interesting to some developers, but introduce many third-party libraries. For example, the compute and storage disaggregated arch requires AWS-related libraries. The vector search feature requires HNSW related libraries. Sure someone can introduce compile options to turn off some code dependencies and make it moe easier to be compiled and develop on TiFlash. However, we do not have a certain plan to introduce such options. 

If you or someone else are interested in introducing such options to TiFlash, I'd be glad to review the code changes :)

**Comment by sumory** [comment]
As mentioned above, there are several combinations in our actual production environment (such as llvm14 + gcc11 STL, llvm16 + gcc13 STL, etc.), so it would be best if we can customize the compile environment. However, I understand that as an open source project, there is no obligation for TiFlash to provide such flexible combinations.

So, I'll just close this issue. Looking forward to any enhancements in these cases :)
