### ISSUE TITLE
OALP perftest  tpch-2tiflash-50g& tpch-tiflash-50g result with total-avg-latency raise 15-20%

### ISSUE THREAD

**Issue by stevenayu** [pingcap/tiflash#9586]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
Deploy a tidb cluster with 3 TiDB (16c,48G) + 3 TiKV (16c,48G) + 2 TiFlash (16c,80G)
Compare the performance of v8.4.0 and v8.3.0 with TPCH benchmark

### 2. What did you expect to see? (Required)
No performance regression

### 3. What did you see instead (Required)
total-avg-latency raise 15-20%.
![image](https://github.com/user-attachments/assets/cbe9c3e3-f0b6-487f-8bf7-0734f2b2f84d)

### 4. What is your TiFlash version? (Required)
v8.4.0 (cea728d5d2bad7766dfc5e97cdf8ef16fe4a791f)

**Comment by wuhuizuo** [comment]
/close

it is not caused by codes, but the llvm toolchain in building env.

**Comment by JaySon-Huang** [comment]
Caused by when the CI pipeline base image migrate from centos 7 to rockylinux 8, the LLVM

* https://github.com/PingCAP-QE/ci/pull/3187

Fixed by rebuilding the base image using the scripts in "/release-linux-llvm" and update the CI pipline

* https://github.com/PingCAP-QE/ci/pull/3219/files
