### ISSUE TITLE
Improve the vector search performance with rows in the delta-layer

### ISSUE THREAD

**Issue by JaySon-Huang** [pingcap/tiflash#9600]
When there are updates to the table with vector index, the QPS of vector search will drop quickly. One of the reason is there is no vector index built on top of the delta layer. So it takes lots of disk IO and CPU to load and compute the distance.
Building vector index on the delta-layer could help improve the vector search performance with updates.

**Comment by Lloyd-Pottiger** [comment]
Now the main bottleneck of vector search is MVCC, track #9616
