### ISSUE TITLE
Start TiFlash on arm failed and report cannot find libssl.so.10 

### ISSUE THREAD

**Issue by lidezhu** [pingcap/tiflash#997]
![tiflash_start_error](https://user-images.githubusercontent.com/47731263/89855303-b67fea80-dbc8-11ea-84be-984de85c9115.png)

Change
`export LD_LIBRARY_PATH=/tidb-deploy/tiflash-9000/bin/tiflash:$LD_LIBRARY_PATH`
to
`export LD_LIBRARY_PATH=/tidb-deploy/tiflash-9000/bin/tiflash:/tidb-deploy/tiflash-9000/bin/tiflash/flash_cluster_manager/:$LD_LIBRARY_PATH`
solve the problem.
We need to check the cause of the problem and find why the solution works.

**Comment by zanmato1984** [comment]
Should have gone. Closing.
